### ISSUE TITLE
Issues reading Diablo II MPQs 

### ISSUE THREAD

**Issue by JacobPersi** [ladislav-zezula/StormLib#101]
Hey there,

Going out on a limb here, as it seems this project isn't heavily maintained. I'm creating a utility to render Diablo II assets. My goal is to export game sprites to a more accessible file format. 

I've compiled the latest version of StormLib (as Release, Unicode, Single-Threaded), and imported the DLL into my project. I've written some test code to simply open a MPQ archive, however it doesn't seem to be working as I would expect. 

Both MPQs are in the same directory as the executable. I've written additional code to open each file using the standard file stream, and everything works fine - so I'm confident the files are where they are expected to be.

When attempting to open `d2data.mpq`, I receive the following error:
`Error Parsing MPQ:
	The system cannot find the file specified.`

However, when attempting to open `d2music.mpq`, I receive a different error:
`Error Parsing MPQ:
	The filename, directory name, or volume label syntax is incorrect.`

The fact that I'm receiving different errors depending on the file makes me think I must be doing something wrong. 

My code is very simply:
`if (!SFileOpenArchive(filePath, 0, MPQ_OPEN_READ_ONLY, &mpqHandle)) 
    errorCode = GetLastError();`

Am I missing something? Any input would be greatly appreciated. 

Thanks,
Jacob

**Comment by wheybags** [comment]
I seem to be using a slightly different read only mode define :
https://github.com/wheybags/freeablo/blob/master/components/faio/faio.cpp#L42

That said, I'm using an older version atm. It may sound stupid, but are you
sure you're using a correct file path? Also, the library is very well
maintained, ladik responds pretty quickly to queries generally, it's just
not very active because it's effectively "finished". Mpq format isn't
changing because Blizzard have stopped using it, and the library works, so
of it ain't broke don't fix it.

**Comment by jleclanche** [comment]
@JacobPersi Stormlib is maintained, it just needs very little of it because there's nothing new happening in the MPQ world now that Blizzard is no longer using them at all.

**Comment by Lectem** [comment]
I had no issues with Diablo II .mpqs when using stormlib, you can check https://github.com/Lectem/Worldstone/blob/master/source/system/src/MpqArchive.cpp#L28 . As @wheybags said, you probably are missing the read only flag.
Side node for @JacobPersi : I've been working on reading Diablo2 assets for a while, I started open sourcing here https://github.com/Lectem/Worldstone but sadly by lack of time / motivation, not much has been made available yet. Feel free to contact me for more information
