### ISSUE TITLE
Change compress type in mpqeditor not working?

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#102]
Create new ruleset = error.

Change compress type in mpqeditor not working?

I try to set ZLIB/PKWARE/BZIP2 , but file size allways same.

**Comment by ladislav-zezula** [comment]
I added a slightly fixed version here:
http://www.zezula.net/download/mpqediten32_test.zip
Can you check if it works for you? And if not, can you describe the steps that led to your problem?

**Comment by Karaulov** [comment]
Not working, i test Zlib/Pkware/Bzip2 , file size not changed!

Do I choose the right one?
http://i.imgur.com/dxZKp9i.png

**Comment by ladislav-zezula** [comment]
You edited the custom ruleset. You also need to set it by in the "Game Compatibility" dialog.
Maybe I should make it more clear from the dialog layout.

**Comment by Karaulov** [comment]
How to select another compress type for Warcraft III ?

I see Warcraft III support "Zlib/Pkware/Bzip2" ??? I try to change it, but file size allways same.

**Comment by ladislav-zezula** [comment]
Can't change builtin game rules. They are demanded by the game itself.
If you want your own, edit a custom ruleset.

**Comment by Karaulov** [comment]
Not working, i select custom ruleset, select zlib/pkware/bzip2 but file size not changed.

**Comment by Karaulov** [comment]
WORKS ONLY FOR NEW FILES!!!

if press "rebuild" button, mpq file size not changed, but if I add new file to mpq, then mpq file changed.

please fix, need works allways

**Comment by ladislav-zezula** [comment]
Yes, it is supposed to work like that. Changing game rules does not affect files that are already in the archive.

**Comment by Karaulov** [comment]
Is there any logic in this?

**Comment by ladislav-zezula** [comment]
Yes. You are supposed to setup the compressions and then build your MPQ.
Anyway, MPQ format is dead and it's only used for W3 maps, no point in putting effort into MPQ editor(s).

**Comment by Karaulov** [comment]
Okay, how to create new W3X archive ?
