### ISSUE TITLE
MPQ Editor Compatibility Issues

### ISSUE THREAD

**Issue by LucianBuFan** [ladislav-zezula/StormLib#106]
( I have sented a email in the same title, but just in case, I think it's better to create a issue. )

Hi ladik,

I used MPQ Editor v 3.5.1.821 (Chinese, 32-bit) to create a new MPQ,  and then imported everything from the starcraft/broodwar CD, because I wanted to make a "2 in 1" mpq for no-cd.

It worked well in 1.16.1 and later I found it even worked well in 1.11b (with cracked). This maked me interested, so I tried to use it in 1.00, but then I got error "Invalid data file version number rez/cdversion.txt", and the same in 1.04 (broodwar). I tried to use diablo/broodwar compatibility, and customized rule sets with no compression, but the result was the same.

Then I did the same thing with MPQ Workshop, and It didn't pop the error and worked well in 1.00 (but with other IO problems in 1.16.1). And finally, I found some "2 in 1" mpq could work well both from 1.00 to 1.16.1, but I didn't know which tool made it, maybe WinMPQ.

It seems to be the compression problem, I will try WinMPQ and other tool, but I prefer MPQEditor more, so I think I need to report this to you.

( PS: And now, I have tried WinMPQ, yes, it works well from 1.00 to 1.16.1.)

**Comment by ladislav-zezula** [comment]
Hi, I am not going to deal with this any soon, due to time constraints.

**Comment by LucianBuFan** [comment]
Oh, it's really a pity but I can understand.
