### ISSUE TITLE
MPQ Editor closing on ListFile application

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#107]
Hello!

Sorry to bother you again, but I have found a small issue, it is not causing too many problems or anything, just wanted to report it. The problem surfaces, when you have your file opened in MPQ Editor without adding listfile to it initially. Meaning if you have it opened like this:

![listfile1](https://user-images.githubusercontent.com/11413837/29179254-f7c1e108-7e04-11e7-9226-8bcd8e82877a.png)

Now if we add listfile using "Add Listfile" after we opened the file, like this:

![listfile2](https://user-images.githubusercontent.com/11413837/29179255-f7c24954-7e04-11e7-9d6c-5b9af700e82f.png)

Then, we get our usual working progress, like this:
![listfile3](https://user-images.githubusercontent.com/11413837/29179258-f7cc41de-7e04-11e7-8420-87b34e533b61.png)

However, when it starts adding listfile the program is instalty closed, I was able to catch it before it fully closing like this:

![listfile4](https://user-images.githubusercontent.com/11413837/29179257-f7c96784-7e04-11e7-9eff-de3013f453eb.png)

Then we get this:

![listfile5](https://user-images.githubusercontent.com/11413837/29179256-f7c516ac-7e04-11e7-8561-ae4b99795034.png)

Possibly due to a lot of new features added to the MPQ Editor its post-processing was damaged? Or I assume so. This is not such a big deal, as you can initially add the listfile when you just open the file, but still wanted to point it out.

As per usual thank you for your work and sorry for being an annoyance,
Sandro.

**Comment by Take1hat** [comment]
There seems to be another problem when adding a list file to a map with the new protection. You get the files from your listfile it seems. Which I have no idea how to fix due to no other guides. The only fix I've found was removing MPQeditor and unzipping it again. But after adding the list file again, the problem occurs. Perhaps I'm doing something wrong? And Tailer, I've tried poking you on WC3edit about the new protection because you seemed close to figuring it out. 
![mpqeditor_2017-08-11_18-39-33](https://user-images.githubusercontent.com/18003801/29236767-3eea1cce-7ec5-11e7-953d-f381c735a480.png)

**Comment by Tailer007** [comment]
This is not really the correct place to write about this, but I will answer in Ladik's stead. This is something that is caused by HEX corruption it references to files that do not exist, meaning you are supposed to just ignore them and no, they are not being taken from your listfile, this files were "added" to be referenced if they get "called".

All in all, just ignore files with extensions like: .ax / .asi / .css / .dll / .exe / .flt / .html /.,jpg / .js / .m3d / .tga (RPGCreator_font files) / .txt (in main folder) / .w3m / .w3n / .w3x / .wai / .xxx

These are the dummy files generated by the HEX corruption, that is pretty much it. It is near impossible to make MPQ Editor to know that beforehand and ignore them, so just use what you have, it is much more than enough.

Cheers,
Sandro.

**Comment by Take1hat** [comment]
Thank you for the reply. And I should have known because I do remember reading your post about the protection and the fake headers, I apologize. Also I should have worded my post a bit better.
First time posting on github, my mistake on using the wrong place to write.

Thank you Sandro.

**Comment by ladislav-zezula** [comment]
> All in all, just ignore files with extensions like: .ax / .asi / .css / .dll
> / .exe / .flt / .html /.,jpg / .js / .m3d / .tga (RPGCreator_font files)
> / .txt (in main folder) / .w3m / .w3n / .w3x / .wai / .xxx

In the newest build, there's "Deep File Verification" option in the openin dialog. If you check it, MPQ Editor will try to read few bytes from each file. Only if that succeeds, it will display that file.
Loading the MPQ will indeed be slower, but you will only see files that are really there.

As for the listfile bug reported by Tailer007, I'll look at it. Don't worry, you are not an annoyance, it's just I don't always have the time to react (and fix things) fast.

**Comment by ladislav-zezula** [comment]
The crash was fixed.
