### ISSUE TITLE
Two issues about extra filelist and patch opening

### ISSUE THREAD

**Issue by LucianBuFan** [ladislav-zezula/StormLib#108]
It's me again.

The first issue is that if the filelist’s path contains Chinese (maybe other non-ascii characters like Korean and Japanese also will be), the MPQEditor will not reads it. 

And the second is that when I try to open mpq A with patch B, and the files will more than A's upper limit, so MPQEditor try to expand it, but if A's filelist incomplete or out of memory, MPQEditor crashes rather than gives message like when I open A and expand limit manually.

**Comment by ladislav-zezula** [comment]
Could you send me file examples?

**Comment by LucianBuFan** [comment]
I just used the original starcraft‘s install.exe as the basic mpq, and broodwar's install.exe as the patch. 
I'm afraid I can not send them to you due to my network situation, but I think you can get them in the blizzard's website for free:
https://battle.net/download/getInstallerForGame?version=LIVE&gameProgram=STARCRAFT

**Comment by ladislav-zezula** [comment]
That's OK, it's all I need to know. I'll try.

**Comment by ladislav-zezula** [comment]
Fixed in commit 431570180b0d089143c10b40563810bb45e57300. Thanks for the contribution.
