### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by BlacklightsC** [ladislav-zezula/StormLib#111]
Hello, I am a user living in Korea.
I want to translate your tools.
I've used your tools before, but I do not know how to help them, so I upload them to this issue.

PS I made MPQ corruption to bypass your tools 2 months ago, but I have confirmed that it does not work anymore (I'm talking about Eden RPG).

**Comment by ladislav-zezula** [comment]
If you want to make Korean version of MPQ Editor, I can send you the resources for translation.
Please, contact me on zezula_at_volny_dot_cz
