### ISSUE TITLE
Updated .mix file type (.asi)

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#112]
Hello, and it is me again.

I really did not want to bother you again with things like this, but this is a protection that I couldn't fully crack, I could make MPQ Editor open it, but with all files corrupted/wrong (possibly by luck), anyways, here is the data.

Initial header is a bit different from .mix, but mostly retains the same structure, but for the rest of the "body". The major difference is this.
![mpqasidata1](https://user-images.githubusercontent.com/11413837/30026924-f5ced650-918f-11e7-9cbc-b2e84ca3043d.png)
Possibly this is done make Warcraft 3 realise where it has hidden the data, as the MPQ underneath:
![mpqasidata2](https://user-images.githubusercontent.com/11413837/30027396-df1156a2-9191-11e7-88d3-c6b128e00008.png)
is clearly corrupted and will never work at all. So by adding an MPQ Header on top of it with nill values we can open the MPQ, but of course without the correct hash table and block data, etc. it is quite useless.

You can download the file here: https://www.mediafire.com/file/n00n8w655nxwdr6/patch%28war3%29.asi
Blank old type .mix: [blankMix.zip](https://github.com/ladislav-zezula/StormLib/files/1274740/blankMix.zip)

Hopefully this data is enough, if not I will try my best to give more data.

Thank you for your attention,
Sandro.

**Comment by Tailer007** [comment]
A small update, the file extension does not matter, it can be changed back to .mix and it will function as it did, just wanted to point it out. Same way as changing current .mix extention into .asi won't affect it at all.

**Comment by Tailer007** [comment]
Bump! Hoping to see positive results soon.

**Comment by ladislav-zezula** [comment]
The file is some sort of a corrupt EXE.
The first screenshot you posted is actually strings used by MPQ-reading code.
The second screenshot is a completely wrong MPQ header. The only valid thing from it is the MPQ magic value ('MPQ\x1A').

**Comment by Tailer007** [comment]
I thought that they could have possibly hidden the rest of the MPQ values, as this .asi file is supposed to be loaded in WC3, so it can take the models out of it, or this particular file is damaged / wrong, not entirely sure, I will try to look for another one like this.

**Comment by Tailer007** [comment]
I have also confirmed that this file is just an .exe or a .dll as it has literally a manifest inside of it, if you look via Resource Hacker, sorry for getting trolled and making you waste your time!
