### ISSUE TITLE
CMake configure sets Character Set to Multi Byte

### ISSUE THREAD

**Issue by stijnherfst** [ladislav-zezula/StormLib#116]
When configuring StormLib as a static library with unicode it sets the Character Set encoding (option in Visual Studio) to Multi-Byte causing strings passed to for instance SFileOpenArchive to get cut off after their first character,

**Comment by Lectem** [comment]
This is the same issue #114 that #115 is trying to fix. Meanwhile you can try to modify your cmake cache to have the following defines based on what character set you need : 
SBCS: neither _UNICODE nor _MBCS defined
Unicode: _UNICODE defined
Multi_Byte: _MBCS defined
This should automatically be reflected in the project properties by cmake.
