### ISSUE TITLE
The MPQEditor still can't read filelist with Chinese.

### ISSUE THREAD

**Issue by LucianBuFan** [ladislav-zezula/StormLib#119]
I just tested the lastest MPQEditor (web say it is v 3.6.0.826 (Chinese, 64-bit), however, the help-about say itself is 3.5.1.832, but it doesn't have a namebreaker so I think it just a little mistake).

![error](https://user-images.githubusercontent.com/30830110/32258911-37484a0e-bef8-11e7-8610-7d8f091a8b43.jpg)

As above, I just start the editor, open a mpq and the click the "..." to choose the filelist, and it load failed, but if the filelist in the user folder or the [username(which I add mosaic because I used company's PC)] folder it will be fine.

The OS is window7 64bit.

**Comment by ladislav-zezula** [comment]
Please, make an UNICODE text file and paste your listfile path into it. Feel free to remove your user name from the path. Also, please, send me your listfile. I'll try the same situation like you did.

**Comment by LucianBuFan** [comment]
[path.txt](https://github.com/ladislav-zezula/StormLib/files/1433565/path.txt)

That's it, and I just get the listfile from your web (http://www.zezula.net/download/listfiles.zip) and unzip it.

[Starcraft BW.txt](https://github.com/ladislav-zezula/StormLib/files/1433572/Starcraft.BW.txt)

**Comment by ladislav-zezula** [comment]
Just a heads-up: I didn't forget about you. I identified the problem (SFileAddListFile taking the parameter as "const char *" instead of "const TCHAR *"). Just need some more time to finish this.

**Comment by ladislav-zezula** [comment]
Fixed in commit dae0b690f796bd421ab69a0219cb1b46095b9f27. Thank you for the contribution.
