### ISSUE TITLE
User can hide file in Warcraft III maps. Just add ~ in filename.

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#120]
Or non printable filenames, can't see in MPQ Editor

Problem with ~ in filename:
https://github.com/ladislav-zezula/StormLib/blob/adac4aa0f586c7aa2a3c19aa4e687d827dc86195/src/SFileListFile.cpp#L192

Please fix it :)

**Comment by ladislav-zezula** [comment]
I'll fix this together with https://github.com/ladislav-zezula/StormLib/issues/119.

**Comment by Karaulov** [comment]
Not fixed. I check latest MPQ Editor.

Try this archive:  ( With full internal listfile )


[TestBadCharInPath.zip](https://github.com/ladislav-zezula/StormLib/files/1450618/TestBadCharInPath.zip)

**Comment by Karaulov** [comment]
![scd4jbj 1](https://user-images.githubusercontent.com/6445336/32502410-b2286ef0-c3eb-11e7-9a9a-7535e68b782b.png)

**Comment by ladislav-zezula** [comment]
Dear friend, please, learn to read.
Repeat: I'll fix this together with #119. The "I'll" part means "I will", implicating that it's gonna happen in the future.

**Comment by Karaulov** [comment]
Sorry i bad english language, i translate only "fix" and "#119" words :))))

**Comment by ladislav-zezula** [comment]
Fixed in commit e549b5db4c8a02b8a4b9cce9477720c103d8e339
