### ISSUE TITLE
Failed to scan file names on a MPQ.Sprotect map

### ISSUE THREAD

**Issue by s09289728096** [ladislav-zezula/StormLib#126]
I'm a translator keening on translating Korean map into Chinese one, and there is a problem bother me for a long time.

There's a map encrypted by mpq.sprotect. I know there's a discussion about this encryption at #78 , and mpqeditor now can open these maps. However, the problem is on the funciton to scan file names.

![00000](https://user-images.githubusercontent.com/9736390/38087039-3ff79f64-3389-11e8-98a2-b49aeda0f131.jpg)

![000](https://user-images.githubusercontent.com/9736390/38087049-4980d0c8-3389-11e8-9294-b5acf7db78a7.jpg)

I don't know if i do something wrong, but both map file scanner and live game scanner cannot work on this map. I also try to use filelist from the old version of this map, but it still can't list all the files correctly.

![001](https://user-images.githubusercontent.com/9736390/38087057-53258ea2-3389-11e8-9706-5a38eb8e8a3c.jpg)

And hey, what's that?

![002](https://user-images.githubusercontent.com/9736390/38087062-561e4df6-3389-11e8-852e-cf0b86e15053.jpg)

These files are unusual big. I'm not sure if these things are the reason that causes scanner failing to list file names, so let me ask this question.

[New version of the map](https://drive.google.com/file/d/1EvxbwiRqi-T1z0rfJKNblzPADxwFt3Xh/view?usp=sharing)

[Old version of the map](https://drive.google.com/file/d/1alyzSnWRPKebByBHkEVe6vwP3OuPPdD8/view?usp=sharing)

My mpqeditor version is 3.6.0.837, it doesn't work on both 32-bit and 64-bit version.

**Comment by ladislav-zezula** [comment]
Did you try to make a live scan?
