### ISSUE TITLE
SFileAddFileEx question over dwCompressionNext

### ISSUE THREAD

**Issue by nvs** [ladislav-zezula/StormLib#128]
In the remarks section of the documentation for [`SFileAddFileEx ()`](http://www.zezula.net/en/mpq/stormlib/sfileaddfileex.html) it states the following:

> If the dwCompressionNext parameter is omited, the function uses dwCompression for compressing rest of the file.

However, in practice if `dwCompressionNext` is omitted then no compression is used for the rest of the file. According to [this block](https://github.com/ladislav-zezula/StormLib/blob/251c47d32087eff23c8fc20f073cdbf0a1d1a845/src/SFileAddFile.cpp#L929), `dwCompressionNext` is only set to `dwCompression` if it equals `MPQ_COMPRESSION_NEXT_SAME`. Although, there is mention of a default value that is not set at any point.

Is the behavior described in the remarks section correct (and it would seem perhaps in the source comments)? Or is the current behavior of the code correct?

**Comment by ladislav-zezula** [comment]
Documentation fixed. Thanks for the find.
