### ISSUE TITLE
conflicting definition with CascLib on linux

### ISSUE THREAD

**Issue by BogdanW3** [ladislav-zezula/StormLib#138]
GetLastError and SetLastError use 'DWORD' in StormLib, but in CascLib they use int. This inconsistency causes compilation errors. Also using both libs causes 'multiple definition' errors(GetLastError, SetLastError, IsValidFileHandle, CalculateDataBlockHash, VerifyDataBlockHash, IsValidMD5)

**Comment by ladislav-zezula** [comment]
In commit 9e10caef57e232f0d43a52c92cfa3a4caaf67066 of CascLib, I changed the LastError functions to use DWORD. I also renamed the IsValidFileHandle and IsValidStorageHandle. As for the others, there will probabl be many more conflicts than just CalculateDataBlockHash, VerifyDataBlockHash, IsValidMD5. At least the whole FileStream was taken from StormLib. I never intended to have both libraries on one project. Would building a dynamic library from StormLib and CascLib help?

**Comment by maxemann96** [comment]
What is the actual status of this? For ghost++ I need to use StormLib and CascLib simultaneously, StormLib for map MPQ-Files and CascLib for automatically extracting common.j and blizzard.j out of the Warcraft III.exe

**Comment by BogdanW3** [comment]
Take a look at my fork if no better solution arises, @maxemann96

**Comment by maxemann96** [comment]
@BogdanW3 Thx for your work, is working like a charm :)

**Comment by ladislav-zezula** [comment]
@BogdanW3: I looked at your fork and it seems that the only file that conflicts with CascLib is `CheckWildCard`. I renamed the function in commit b60bc45088ffa77b00dffca928f99159cbcebd2f. It should now work.

Closing the issue; if a problem persists, let me know.
