### ISSUE TITLE
Request for a WC3 tool.

### ISSUE THREAD

**Issue by Unryze** [ladislav-zezula/StormLib#140]
This is no an issue, but a request, as stated above. I would love to see a small executable or .bat or anything of such sort to instantly start WC3 with a selected map via path. Aka something you did with live scan, but have it separately and with possibility of controlling map path.

Could you please release your live scan, as a separate tool that will just launch a selected map directly in WC3? I would be very glad to have that, it will boost my map editing very-very much.

Thank you for your attention!

**Comment by ladislav-zezula** [comment]
Would this BAT filehelp? 

```rem copy the map to the Maps folder
copy /Y %1 "C:\Games\Warcraft III"

rem Run Warcraft III with the map
"C:\Games\Warcraft III\war3.exe" -window -loadfile "C:\Games\Warcraft III\Maps\%1"
```

**Comment by Unryze** [comment]
Yep, that's exactly what I needed, thank you ;)
