### ISSUE TITLE
Big memmory alloc

### ISSUE THREAD

**Issue by kirill-782** [ladislav-zezula/StormLib#141]
I installed the library on my bot and gave players the opportunity to download maps for free. One player has loaded an interesting map: [vkapps.ru/EWIX_v8_7.w3x](https://vkapps.ru/EWIX_v8_7.w3x). After SFileOpenMPQArchive, the bot began to consume 200 megabytes more RAM (before closing). A little debugging has shown that the function `BuildFileTable (TMPQArchive * ha)` does such a large malloc. `ha->pHeader->dwBlockTableSize` had a value of over 300,000, which made memory allocations of 200 megabytes. So conceived, or is it some kind of

**Comment by ladislav-zezula** [comment]
Yeah, block table size is 3.249.665 blocks (51.994.640 bytes), which makes StormLib to make a large allocation. I'll make a fix that trims block tables that go beyond the end of the file.

**Comment by ladislav-zezula** [comment]
Fixed in commit f35d106059accbddaa602b6525f9542746b2c2b7.
