### ISSUE TITLE
Can't add listfile to map

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#142]
Why can I edit a map with any file except listfile? I can replace any file in map opening mpq in write mode except for listfile. Also tried using SFileAddListFile instead of SFileAddFileEx but it doesn't seem to alter the mpq. map is https://ufile.io/1wm3p

**Comment by ladislav-zezula** [comment]
Listfile is maintained internally by StormLib. Yes, you can add a listfile, but if the map is somehow malformed (which is the case of ANY map protector today), StormLib opens it in read-only mode.

**Comment by juvian** [comment]
But this map is not opened in read only mode, I can edit any other file in it

**Comment by ladislav-zezula** [comment]
True, SFileAddListFile does not alter the map, but it merely adds an extra information about names which are unknown.

You may use SFileAddListFile, then add any file into the map (in order to mark it as changed) and close. StormLib will save the updated listfile.

**Comment by Unryze** [comment]
The thing is, what you are looking for is in WinMPQ, I really don't want MPQ Editor to have the same functionality, gives way too much useless powers to either those who just want to mangle a map or straight up steal things.

Of course, that is coming from a person who did all of the things above, but at least I had to be "tricky" about it. Let's not forget again, that this is MPQ Editor and not WC3 Map Editor, it does more than it should already to be fair.

Anyhow, just use combination of MPQ Editor + WinMPQ, add listfile with WinMPQ, close it and edit with MPQ Editor later.

**Comment by juvian** [comment]
@Unryze I mean I don´t see the difference, I can already add listfile, then extract all files and then make a new mpq with it. Its just unnecessarily inefficient for me. Map not having editor files and optimized script is the most you can do. Stealing models is already possible, and mpq editor already makes editing harder on read only maps. I am not sure when does it deem it to be read only, but this is not that case.

**Comment by Unryze** [comment]
@juvian 

It is a small "problem" for you and me, for others, who never did it, is like an obstacle that they cannot cross. 

As for editing, I've edited a lot of maps with just MPQ Editor and Notepad++ from basic abilities to coding, thus I look at it from the same perspective.

Read-Only appears on any, even small malformaion of MPQ via hex, like Vexorian does, etc.

**Comment by juvian** [comment]
I still don´t see the issue of adding it for non read only maps, which you are supposed to be able to edit

**Comment by Unryze** [comment]
There is no real reason not to add, only if you factor that it won’t be used in most cases just to translate maps, in majority of the cases it will be people trying to inject cheats, change code and etc, which is a very bad trade off.

Let’s wait for Ladik’s response, after all it is up to him to decide, I just gave my 5 cents on this matter. :)

**Comment by juvian** [comment]
You can already inject cheats on a non read only map.. Most maps where this matters are rpgs, and most do replay checking anyway. I see your point of hacking, but at this point in time even if you know nothing, just need to post the request at the appropiate site and you get hacked map ^^. "Experts" already have their own toolsets, and they do it in really little time.

**Comment by Unryze** [comment]
Just a small addition, there are protections that they are unable to bypass, like saint Seya map for example. 

Even Somj with filelist destroyed can’t be fully scanned.

I do have my own toolset of course, but what’s important is to not make life easier for beginners at this, so they don’t consider doing it.

That was pretty much what I was trying to tell, anyways cheers :)

**Comment by ladislav-zezula** [comment]
@juvian: Repeat: You may use SFileAddListFile, then add any file into the map (in order to mark it as changed) and close. StormLib will save the updated listfile. Understood? If this won't work, it's a bug.

**Comment by juvian** [comment]
@ladislav-zezula oh I see, misunderstood that files got marked as changed instead of mpq. Will try it out later, thanks!

**Comment by juvian** [comment]
@ladislav-zezula is SFileAddListFile second parameter a string to the path of listfile or the listfile text?
Tried with both options and still not working, did:
SFileOpenFileEx
SFileAddListFile 
SFileAddFileEx
SFileCloseArchive

Both SFileAddListFile and SFileAddFileEx return true

**Comment by ladislav-zezula** [comment]
It's name of the listfile.

**Comment by juvian** [comment]
@ladislav-zezula tried multiple things, both with a map that had no listfile and one that had, nothing seems to be able to change it (both editable maps)

**Comment by ladislav-zezula** [comment]
Could you send me the listfile and the map? I'll test and if there's a bug, I'll fix it.

**Comment by juvian** [comment]
@ladislav-zezula map without listfile is https://uploadfiles.io/1wm3p, don´t have listfile on this pc but can use just a file with regular files as listfile (war3map.j, war3map.w3a)

**Comment by ladislav-zezula** [comment]
I checked and the problem here is that StormLib keeps listfile status on a MPQ. So when there was no listfile before, there will be no listfile after. I recommend keep using an external listfile.

**Comment by juvian** [comment]
@ladislav-zezula when I tried with a map that had listfile it didn´t work either, unless entries are only added if file exists in mpq?

**Comment by ladislav-zezula** [comment]
I just tried with a map that has listfile and it works as expected. Newly added file was added to the MPQ and also to the listfile. Could you send me example of such map?

**Comment by juvian** [comment]
@ladislav-zezula yeah I meant arbitrarily adding file names that don´t exist to listfile, which doesn´t really have a use but that´s what I had tried. Haven´t tried with a map with partial list file (so with some unknown files) which would make more sense. Yes, if you add a file it works fine, just wanted to extend listfile though. For my particular purposes, managed to edit a map optimizer to take an external listfile, so guess will just go that way instead of modifying stormlib. The whole point of my case was to be able to use the optimizer to optimize map after translation, but map did not have listfile on it. Also 1.30 w3 stops being able to read most korean maps (this included) so rebuilding mpq or optimizing it was necessary. Thanks for your time

**Comment by ladislav-zezula** [comment]
I added a new flag to SFileOpenArchive. This one forces adding/updating listfile even if there was none at the at the archive open. Download the latest MPQEditor and follow these steps:

* Run MPQEditor.exe YourMap.w3x
* In the open dialog, check the "Force adding listfile when modified"
* Add a dummy file to the archive
* When you close the archive, the listfile will be properly updated.

Please, let me know if this solution is OK for you.

**Comment by juvian** [comment]
@ladislav-zezula tried on mpq editor, perfect 💯 . Do you have the dll? Hard to get it to compile

**Comment by ladislav-zezula** [comment]
Here: 
[StormLib_DLL.zip](https://github.com/ladislav-zezula/StormLib/files/2565056/StormLib_DLL.zip)
