### ISSUE TITLE
Mix Patch with Themida

### ISSUE THREAD

**Issue by Unryze** [ladislav-zezula/StormLib#144]
Hello, it is me again with an actually interesting case.

So, even though it evolves Themida and a secondary fake MPQ header after the obfuscated data, I've tried using OllyDBG (used it for the first time to be fair) but couldn't make it dump the file, however, the data won't load if fake MPQ header is removed, aka the secondary MPQ is loaded afterwards, on in fact it "switches" the loaded data to the data that was obfuscated.

Anyways, here is the .mix file for you to see:
[habpatch.zip](https://github.com/ladislav-zezula/StormLib/files/2766123/habpatch.zip)

Sadly I am not of much help on this one, as I am unfamiliar with Themida, nor am I really thinking you should care about it, I am more awaiting your opinion on this and possibly some ideas with a workaround.

Hopefully it will seem interesting to you, if you have any questions I will try to answer them if I can.

**Comment by ladislav-zezula** [comment]
What should I actually do with the file? MPQEditor can open it just fine.
![mpq-editor](https://user-images.githubusercontent.com/3244359/51305896-5f418480-1a3c-11e9-9f54-0f4a45f937aa.png)

**Comment by Unryze** [comment]
That is the secondary MPQ header underneath Themida compacted one, which I've explained ;P 

It is here:
![screenshot_1](https://user-images.githubusercontent.com/11413837/51306869-c456a380-1a57-11e9-9287-d2be033cbfd9.png)

That is a fake MPQ header, the rest is spoofed as I've mentioned before by Themida.

**Comment by ladislav-zezula** [comment]
Ok, but what is actually that "mix" file?
The only valid MPQ in it is the one that you call spoofed.

**Comment by Unryze** [comment]
.mix and .asi are pretty much MPQs, that are in "DLLS" WC3 can preload them and MPQ Editor is able to open them, in this case, because real header was hidden by themida, MPQ Editor is opening well, the only actual MPQ Header it can see, but the real one is hidden.

Meaning, opening it directly only gives us well a "fake" or any file it contains, while not showing the rest that is hidden.

As for the spoof, the data that is OVER the FAKE MPQ header is the spoofed data, which cannot be accessed if the fake MPQ header is removed which contains the file you have seen.

That is why I said it is a bit complicated to explain, and that is why I attached screenshots and list of hooks that this file does in order to change the fake MPQ with real one, etc.

**Comment by ladislav-zezula** [comment]
Oh. But well, I will not all any un-themida features into StormLib

**Comment by Unryze** [comment]
I see, also is there a way to read MPQ via Storm.dll like WC3 does? Or it does not support any file extraction features?

**Comment by ladislav-zezula** [comment]
IIRC Storm.dll is out for a long time, even for Warcraft III. I am not aware of how the .mix files exactly work.

**Comment by Unryze** [comment]
Well, they are simply automatically loaded by WC3, then MPQ that is inside of it is attached by the process of WC3, thus forcing it to load it as a MPQ.

All in all it emulates MPQ.

As for IIRC Storm.lib is there any MPQ Viewer that utilizes it? Aka able to ignore any corruption and view/extract files.

**Comment by ladislav-zezula** [comment]
I don't think that any MPQ viewer, using Storm.dll, can read MIX files.
If that's what are you asking about.

**Comment by Unryze** [comment]
Well, if it can read MPQ it should technically work, I will search for it, thanks :)

**Comment by ladislav-zezula** [comment]
Hi once again. I was looking to that .MIX file you sent me (habpatch.mix). You said that Themida replaces the fake MPQ data with another. This is actually weird. Let me explain.

The habpatch.mix consists of 6 files. 5 of them are EXEs, and the 6th is the MPQ itself:
```
E:\Ladik\Incoming\mix-files>split-pe habpatch.mix
[*] ===== habpatch.mix =====
[0] Writing fragment: 000-pefile.dat (11022336 bytes)
[1] Writing fragment: 001-pefile.dat (53248 bytes)
[2] Writing fragment: 002-pefile.dat (53248 bytes)
[3] Writing fragment: 003-pefile.dat (53248 bytes)
[4] Writing fragment: 004-pefile.dat (53248 bytes)
[5] Writing fragment: 005-pefile.dat (66059 bytes)
```
Themida cannot "patch" the MPQ tail in the memory, because infact, it is not even loaded. The Windows loader only loads the main EXE. Overlays (data that are beyond the image) are ignored. How did you come to conclusion that it is being patched on the fly?

BTW, maybe come offline to some instant messenger - Messenger, Viber, Slack, whatever you prefer. Send me an e-mail to zezula-at-volny-dot-cz, we figure something out.

**Comment by ladislav-zezula** [comment]
Hi, @Unryze. I am about to do some more work regarding to newest Warcraft III and name scanner. Could you please contact me? Please, send me an e-mail to zezula-at-volny-dot-cz

**Comment by Unryze** [comment]
> Hi, @Unryze. I am about to do some more work regarding to newest Warcraft III and name scanner. It will also involve MIX files. You seem to be an expert for these - could you please contact me? Please, send me an e-mail to zezula-at-volny-dot-cz

Sure, https://www.facebook.com/sandro.takaishvili.7 is my facebook, would be glad to be of help. Will also explain deeply the thing with that weird mix patch as well. o/

**Comment by ladislav-zezula** [comment]
Ok, friend request sent. I'll also delete your post, as you may want to stay anonymous :-)
