### ISSUE TITLE
Problem with Live Game Scanner 

### ISSUE THREAD

**Issue by 1kaitoukid1** [ladislav-zezula/StormLib#147]
Why does this problem happened to me ?
https://www.youtube.com/watch?v=U2VCLux4K2o

**Comment by ladislav-zezula** [comment]
Since certain version, Blizzard stopped using Storm.dll and has the code directly in game.exe, moreover protected by something. So MPQ Editor is unable to find an entry point for SFileOpenFileEx.

**Comment by 1kaitoukid1** [comment]
I have also tried to run it on 1.24e ver but it was the same problem like that

**Comment by 1kaitoukid1** [comment]
> Since certain version, Blizzard stopped using Storm.dll and has the code directly in game.exe, moreover protected by something. So MPQ Editor is unable to find an entry point for SFileOpenFileEx.
I have also tried to run it on 1.24e ver but it was the same problem like that

**Comment by 1kaitoukid1** [comment]
I have also tried to run it on 1.24e ver but it was the same problem like that

**Comment by ladislav-zezula** [comment]
I checked and it looks like it happened when you run MPQ Editor and the game on 32-bit Windows.
Fixed in latest build, which is already uploaded in my website. Thank you for the bug report.
