### ISSUE TITLE
The File Scanner is too slow to scan  this map!

### ISSUE THREAD

**Issue by 1kaitoukid1** [ladislav-zezula/StormLib#148]
When i use File Scanner to this map it takes so long time , after 20 mins i cancel scanning just takes about 200 files. Is there any solution for this?.(This map use the another file .mix to help seeing the models in game  of the map when you put it in the war3 folder )
Map:
https://drive.google.com/file/d/12S5lbqSD54akhqPgdCPyvxH25U68Tx75/view?usp=sharing
Mix File:
https://drive.google.com/file/d/1QI38LWOO_hmCN_oeRxb5_eVyxQqAUyjQ/view?usp=sharing

**Comment by ladislav-zezula** [comment]
Try the live scanner. This will catch file names as they come to the game, in plain text. However, you need to use Warcraft III version 1.27a, there's no support for newer versions.

**Comment by 1kaitoukid1** [comment]
.I used the Live Game Scanner but it can only get a few files because the new models will appear at certain times due to the operation of the map. I want to rebuild this map .

**Comment by Unryze** [comment]
This map contains the same type of protection as old Saint Seya map, if I reckon it has to do with JAPI of YDWE, and technically can be removed with YDWE.

The map is opened very slowly, due to very huge fake files.

Adding a scanned listfile with files from both map and patch here, you can use it as you want.
[NRDListFile.txt](https://github.com/ladislav-zezula/StormLib/files/2872722/NRDListFile.txt)

**Comment by 1kaitoukid1** [comment]
> This map contains the same type of protection as old Saint Seya map, if I reckon it has to do with JAPI of YDWE, and technically can be removed with YDWE.
> 
> The map is opened very slowly, due to very huge fake files.
> 
> Adding a scanned listfile with files from both map and patch here, you can use it as you want.
> [NRDListFile.txt](https://github.com/ladislav-zezula/StormLib/files/2872722/NRDListFile.txt)

Is There any guide about this protection to help me make a listfile myself ?

**Comment by 1kaitoukid1** [comment]
Unryze ,Can you tell me how to remove japi by YDWE ?

**Comment by Unryze** [comment]
Download YDWE, open map with it and save it as a regular map, that's at least how people who removed JAPI said it is done.

**Comment by 1kaitoukid1** [comment]
About Fake Files, Is it only one way that use File Name Scanner and wait for listfiles ?

**Comment by 1kaitoukid1** [comment]
How can you get about 99% listfiles of the map?. There are still many unscanned files when I use Name Scanning also Live Game Scanning.
