### ISSUE TITLE
Not Enough space on the disk bug

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#153]
Steps to produce the error: download https://drive.google.com/file/d/1RUn1Gun56rTF5kQ6zy468ZWCivcBryiR/view
1) Open with mpq editor
2) Use name scanner
3) Extract files
4) Open blank map (https://ufile.io/5vpd5)
5) add all files back
6) 
![image](https://user-images.githubusercontent.com/5660396/55135949-cef28080-510b-11e9-882d-682b081af4b9.png)

**Comment by ladislav-zezula** [comment]
I managed to extract 2424 files from that map (after deleting all files with names like File0000####.dat).
If you want to add all those files to a MPQ, you have to do it on MPQ with hash table size big enough. The "emptymap.w3x" you provided has hash table size only 2048.

**Comment by asssnatcher** [comment]
> I managed to extract 2424 files from that map (after deleting all files with names like File0000####.dat). If you want to add all those files to a MPQ, you have to do it on MPQ with hash table size big enough. The "emptymap.w3x" you provided has hash table size only 2048.
And how do I extend the table? If I open the MPQ in original editor (wc3 worldedit) it works correct. Maybe MPQ Archiver have a bug?

**Comment by ladislav-zezula** [comment]
Either create a new MPQ or use the "Operations / Change max file count" in MPQ Editor. This won't work in a protected map, thought.

**Comment by nazarpunk** [comment]
> Either create a new MPQ or use the "Operations / Change max file count" in MPQ Editor. This won't work in a protected map, thought.

How do I change the maximum number of files through the CLI?

**Comment by ladislav-zezula** [comment]
You can't. Maps that are protected are set to read-only mode intentionally, because it's not possible to cover all the variants of the MPQ corruption.

Unpack all files and make a new map.

**Comment by nazarpunk** [comment]
This is my own map that I add files to via `.bat`. And when I add it, an error “not enough free space” occurs. Changing the file limit solved this problem. But this option is not available in the CLI.

**Comment by ladislav-zezula** [comment]
Oh. In that case, you need to specify the hash table size when creating the map. The `ERROR_DISK_FULL` that you see is typically caused by hash table being too small.

**Comment by nazarpunk** [comment]
```
h[t]size MpqFile HashTableSize

Changes hash table size of the archive.

  MpqFile       Name of the MPQ to be used for this operation.
  HashTableSize File limit. Can be a dec or hex number. Default is 0x1000.
 ```

Thank you very much.

**Comment by ladislav-zezula** [comment]
```
C:\>MPQEditor.exe /console
Ladik's MoPaQ 2000 script interpreter (4.0.0.933)
Type "help" for help on available commands.
Type "exit" to exit the command console.

MoPaQ script interpreter also supports Windows command line.
For example, type "md /?" for help on the Windows "md" command.

C:\>help new
n[ew] MpqFile [MaxFileCount]

Creates a new MPQ. If the file already exists, it will be converted to MPQ.

  MpqFile       Name of the MPQ to be used for this operation.
  MaxFileCount  File limit. Can be a dec or hex number. Default is 0x1000.

C:\>
