### ISSUE TITLE
Problem about extract files !

### ISSUE THREAD

**Issue by 1kaitoukid1** [ladislav-zezula/StormLib#156]
When I extract files of this map, the strange thing is that the extract files process takes a long time and cause lag ( By the Lisfiles obtained after Live Scanning ). After all, I cancel the extract process, the folder containing the map files is up to 19GB.

Although I checked the "Read-only" and "Deep File Verficaition" modes, it seems that the number of files opened is still very high (I am using a 32bit version).

Look forward to the explanation and solution to this problem
Sincere thanks!
Link map: 
https://drive.google.com/file/d/1smDptkKgoe8r3xX96ZjAgOH0SjBVM41G/view?usp=sharing

P/s: Now more and more maps use the method of fake files very much, so scanning files names is no longer accurate and time consuming. Do you still intend to develop your program to solve this, Ladislav Zezula?

Sincere thanks!

**Comment by Unryze** [comment]
Have to confirm this issue, tested myself, same problem arises.

I made a mock up code to check text that files contain, perhaps it is possible to use it to enhance deep file verification?

void ParseBytes() {
	bool IsGood = true;
	ifstream inFile;
	string Extension = S2L( ".tga" );
	inFile.open( "test" + Extension );

	stringstream strStream;
	strStream << inFile.rdbuf();
	string str = strStream.str();

	if ( Extension == ".mdx" ) { if( str.find( "MDLXVERS" ) != 1 ) { IsGood = false; } }
	if ( Extension == ".blp" ) { if( str.find( "BLP" ) != 1 ) { IsGood = false; } }
	if ( Extension == ".tga" ) { for ( int i = 0; i < 10; i++ ) { if ( ( i != 2 && static_cast<int>( str[ i ] ) != 0 ) || ( i == 2 && static_cast<int>( str[ i ] ) != 2 ) ) { IsGood = false; break; } } }
	if ( !IsGood ) { cout << "Bad" << Extension.substr( 1 ) << "file!" << endl; }
	else { cout << "Check completed!" << endl; }
}

That is, if it is possible to open file like that from the MPQ that is in memory.

**Comment by Unryzesinshluhi** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6Ykxhzm/fc096595b2f3fe37eb19b9261fac5d11.jpg" alt="fc096595b2f3fe37eb19b9261fac5d11" border="0"></a>

**Comment by 2020karaulov2020** [comment]
@ladislav-zezula sorry for ping ) 

Possible it can be bypassed by check 'IsFileContainValidFileSectors" 

Valid file has valid file sectors:
![ZYQK5X 1](https://user-images.githubusercontent.com/62130676/77550621-65de4e00-6ec2-11ea-8d8f-16d3f162ee95.jpg)
Invalid with no sectors: 
![SGMY6r 1](https://user-images.githubusercontent.com/62130676/77550764-88706700-6ec2-11ea-8383-62db19cd6948.jpg)

**Comment by ladislav-zezula** [comment]
I reduced the amount of fake files that StormLib is willing to open. Somewhat.
Commit: 1f17e92643dea4340719ed195f4425272a29301e

**Comment by 2020karaulov2020** [comment]
https://github.com/ladislav-zezula/StormLib/blob/1f17e92643dea4340719ed195f4425272a29301e/src/SFileFindFile.cpp#L226

@ladislav-zezula file can be higher than sector size ?

```
if (pFileEntry->dwFileSize > ha->dwSectorSize)
            return false;
```
![77550764-88706700-6ec2-11ea-8383-62db19cd6948 1](https://user-images.githubusercontent.com/62130676/77575000-e6fa0d00-6ee3-11ea-9532-1660b49b9ce9.jpg)

Invalid file has 0 sector count, impossible to bypass files with zero sectors ??
