### ISSUE TITLE
Question of Searching Files

### ISSUE THREAD

**Issue by qq928880189** [ladislav-zezula/StormLib#159]
Many maps now use Lua scripts and now StormLib. DLL can't search and display Lua files.

**Comment by ladislav-zezula** [comment]
Could you send me a map which contains a LUA script?

**Comment by qq928880189** [comment]
Documents are too big to upload to your mailbox. How many mailboxes to send documents to you?

**Comment by ladislav-zezula** [comment]
There are many ways how to send big documents - Google Drive, OneDrive, Dropbox and many others. No need to send via e-mail. 

However, from your description, I know almost nothing about the problem.
> DLL can't search and display Lua files.
What does it mean? What DLL? What exactly are you trying to do?

**Comment by qq928880189** [comment]
Sfilefindfirstfile This function does not display Lua files, only XXX

**Comment by qq928880189** [comment]
The sfilegetfileinfo source does not seem to display the Lua file
![1](https://user-images.githubusercontent.com/55014991/64592631-fc439a00-d3de-11e9-906e-7b0cd06b3a9e.jpg)

**Comment by ladislav-zezula** [comment]
Ah, I see. 
However, because LUA files are text scripts, they cannot be easily recognized unless there is a fixed header.

To display LUA files properly, you must have them in listfile.

**Comment by qq928880189** [comment]
Okay, I see.

**Comment by ladislav-zezula** [comment]
But again - could you please upload a map with LUA scripts somewhere? I can look if there is something I can do.

**Comment by qq928880189** [comment]
I can't get into these disks.
Https://pan.baidu.com/s/1Umkns 5GQDkg RhalI 1IcGJg

If you try my disk, you can access it.
If it is not accessible, it can only be sent to you by e-mail.

**Comment by ladislav-zezula** [comment]
The only thing I understood from the page (even with Google translator) is that it wants me to install a Baidu client. But since that one is in Chinese as well, I stopped that process, because it won't help me either. Can't you upload the file here to GitHub?

**Comment by qq928880189** [comment]
More than 10MB can not upload
I will try to upload the papers in separate papers.

**Comment by qq928880189** [comment]
[map.part01.zip](https://github.com/ladislav-zezula/StormLib/files/3594761/map.part01.zip)
[map.part02.zip](https://github.com/ladislav-zezula/StormLib/files/3594774/map.part02.zip)
[map.part03.zip](https://github.com/ladislav-zezula/StormLib/files/3594775/map.part03.zip)
[map.part04.zip](https://github.com/ladislav-zezula/StormLib/files/3594789/map.part04.zip)
[map.part05.zip](https://github.com/ladislav-zezula/StormLib/files/3594790/map.part05.zip)
[map.part06.zip](https://github.com/ladislav-zezula/StormLib/files/3594791/map.part06.zip)
[map.part07.zip](https://github.com/ladislav-zezula/StormLib/files/3594792/map.part07.zip)
[map.part08.zip](https://github.com/ladislav-zezula/StormLib/files/3594793/map.part08.zip)
[map.part09.zip](https://github.com/ladislav-zezula/StormLib/files/3594794/map.part09.zip)
[map.part10.zip](https://github.com/ladislav-zezula/StormLib/files/3594795/map.part10.zip)

**Comment by qq928880189** [comment]
> 但是再次 - 你能否在某处上传一张带有LUA脚本的地图？我可以看看我能做些什么。
http://www.mediafire.com/file/91012cpg8ew7q67/lua_map.zip/file

**Comment by qq928880189** [comment]
> 但是再次 - 你能否在某处上传一张带有LUA脚本的地图？我可以看看我能做些什么。

1.27a version required
If the real-time scanner can scan War3.exe in real time instead of entering the game through the scanner, these Lua files will be easy to find out because many maps can be loaded through the combat platform and can not be created by entering the game through the scanner.

**Comment by ladislav-zezula** [comment]
Fixed in commit https://github.com/ladislav-zezula/StormLib/commit/0eb09af5fee66731d74f0a40c473487563508d93.
Also, MPQ Editor was updated.

**Comment by qq928880189** [comment]
Thank you very much.
But for real-time scanners, as mentioned above, some maps cannot load maps by booting war3.exe with scanners. It is hoped that future versions can add real-time monitoring war3.exe to get lists instead of using scanners to boot war3.exe.

**Comment by ladislav-zezula** [comment]
> It is hoped that future versions can add real-time monitoring war3.exe to get lists instead of using scanners to boot war3.exe.
I don't really want to invest much time into this; first, real-time monitoring is at the edge of breaking EULA, second, MPQ format is obsolete anyway.
