### ISSUE TITLE
[Question] Does this work with w3m reforged files?

### ISSUE THREAD

**Issue by rufreakde** [ladislav-zezula/StormLib#165]
Hi,
I am searching for a way to:
* extract my lua files of my w3m warcraft3 reforged MPQ file
* edit the lua files. 
* then add it back into the map MPQ file. 

Is this possible with this lib? 

PS: It is C code but I will call the code via Node.

Thanks in advance :)

**Comment by ladislav-zezula** [comment]
Is it's a MPQ file, then it will work. But for game data files itself, you need CascView.

**Comment by rufreakde** [comment]
Thanks no worries for the game files I will try to use this:
https://www.npmjs.com/package/wc3maptranslator/v/1.1.0
