### ISSUE TITLE
Default parameter in SFileAddFileEx

### ISSUE THREAD

**Issue by nvs** [ladislav-zezula/StormLib#166]
I had only been building against the 9.22 release and not master, so I had not run into this yet. However, in 4ad0bff21da0163917e1552960e6a43679586b89 a default parameter was added for SFileAddFileEx. Back in https://github.com/ladislav-zezula/StormLib/issues/11#issuecomment-32148918 you mentioned that default parameters were removed from the APIs due to making the StormLib interface C only. However, one seems to have sneaked in. This seems to be the only instance of this issue within the public API in master.

**Comment by ladislav-zezula** [comment]
Hi. Yes, at certain time, someone wanted the public interface to be read-only. However, at current time, nobody has problems with the default parameter and for the sake of a compilability of a library that is no longer developed, I'll leave it as it it.

**Comment by nvs** [comment]
Fair enough. I'll just have to keep this in mind.
