### ISSUE TITLE
Increasing file count limit invalidates open files

### ISSUE THREAD

**Issue by nvs** [ladislav-zezula/StormLib#167]
Currently, if you use `SFileSetMaxFileCount` to successfully set a new file count limit, the `pFileEntry` and `pHashEntry` on open files (i.e. `TMPQFile->pFileEntry`) can become invalid due to use of `realloc`  in the file table rebuild process. This causes calls to `SFileFinishFile` to segfault in such situations. However, with the following changes these references remain valid after `RebuildFileTable`, and the files finish correctly.

My testing of this change seems positive. Open writable files no longer cause issues when the file count limit is increased. But it is possible I am overlooking something in my approach (or in general). I did not see StormLib keeping track of `TMPQFile` objects anywhere. However, adding the extra member in `TFileEntry` and to keep track of parent `TMPQFile` objects was the easiest option. But I am unsure if changing `TFileEntry` is desirable. Thoughts?

```diff
diff --git a/src/SBaseFileTable.cpp b/src/SBaseFileTable.cpp
index a54f152..fce0b6c 100644
--- a/src/SBaseFileTable.cpp
+++ b/src/SBaseFileTable.cpp
@@ -2731,6 +2731,7 @@ int RebuildFileTable(TMPQArchive * ha, DWORD dwNewHashTableSize)
     TMPQHash * pOldHashTable = ha->pHashTable;
     TMPQHash * pHashTable = NULL;
     TMPQHash * pHash;
+    TMPQFile * hf;
     int nError = ERROR_SUCCESS;
 
     // The new hash table size must be greater or equal to the current hash table size
@@ -2773,7 +2774,9 @@ int RebuildFileTable(TMPQArchive * ha, DWORD dwNewHashTableSize)
             if(IsValidHashEntry(ha, pHash))
             {
                 pFileEntry = ha->pFileTable + MPQ_BLOCK_INDEX(pHash);
-                AllocateHashEntry(ha, pFileEntry, pHash->lcLocale);
+                hf = pFileEntry->hf;
+                hf->pFileEntry = pFileEntry;
+                hf->pHashEntry = AllocateHashEntry(ha, pFileEntry, pHash->lcLocale);
             }
         }
 
diff --git a/src/SFileAddFile.cpp b/src/SFileAddFile.cpp
index 7dd583f..86d2940 100644
--- a/src/SFileAddFile.cpp
+++ b/src/SFileAddFile.cpp
@@ -88,6 +88,7 @@ static int FillWritableHandle(
     DWORD dwFlags)
 {
     TFileEntry * pFileEntry = hf->pFileEntry;
+    pFileEntry->hf = hf;
 
     // Initialize the hash entry for the file
     hf->RawFilePos = ha->MpqPos + hf->MpqFilePos;
diff --git a/src/StormLib.h b/src/StormLib.h
index 31f6eda..096ca94 100644
--- a/src/StormLib.h
+++ b/src/StormLib.h
@@ -683,6 +683,8 @@ typedef struct _TPatchInfo
     // Followed by the sector table (variable length)
 } TPatchInfo;
 
+typedef struct _TMPQFile TMPQFile;
+
 // This is the combined file entry for maintaining file list in the MPQ.
 // This structure is combined from block table, hi-block table,
 // (attributes) file and from (listfile).
@@ -697,6 +699,7 @@ typedef struct _TFileEntry
     DWORD     dwCrc32;                          // CRC32 from (attributes) file. 0 if not present.
     BYTE      md5[MD5_DIGEST_SIZE];             // File MD5 from the (attributes) file. 0 if not present.
     char * szFileName;                          // File name. NULL if not known.
+    TMPQFile * hf;
 } TFileEntry;
 
 // Common header for HET and BET tables
```

**Comment by ladislav-zezula** [comment]
Hi. Thanks for your contribution.

Maybe the safest way to fis this would be a workaround - do not extend the file limit while there are files open. I am not very keen to change stuff in a library that handles file format that is almost dead.

**Comment by nvs** [comment]
Yeah, that would work in terms of preventing users from hitting that segfault. And for most it would not change anything, as if they've been trying to increase the limit with files open they've probably been running into said issue so that technique was not working anyway.

Although, it would prevent the behavior I'm trying to achieve, which is automatically increasing the limit on creating new files. But I am sure I can work around the change, depending on where it is introduced.
