### ISSUE TITLE
Big Endian issue

### ISSUE THREAD

**Issue by arczi84** [ladislav-zezula/StormLib#168]
Hello, I have endian issue with save files devilutionX a reversed engineered diablo game. 

It uses StormLib to encrypt / decrypt save file.

Here is my Amiga Big Endian branch.

https://github.com/AmigaPorts/devilutionX/tree/fix-saving

I have made save file from Little Endian version to load but can't save -> encrypt file so far.

With this commit
https://github.com/AmigaPorts/devilutionX/commit/bc1d0eb23b64a79728adea97f59c0a0757bc83e8

Can you help at this matter?

**Comment by ladislav-zezula** [comment]
I am afraid that there is no support for Amiga in StormLib. If you open StormPort.h, there is (was) support for big endian for Mac, before they switched to Intel processors. Since then no one tested big endian support for StormLib.

**Comment by grepwood** [comment]
I could test on big endian. I still have a PowerPC Linux machine lying around.

**Comment by ladislav-zezula** [comment]
@grepwood: If you mean that, please, write me an e-mail. I'll send you link to the testing files that are needed for StormLibTest to be executed.

**Comment by arczi84** [comment]
The problem I had was actually not related to StormLib.
So, StormLib with Big Endian patches used in DevilutionX works good Amiga on BE platform.

**Comment by ladislav-zezula** [comment]
Ok, closing the issue again.
