### ISSUE TITLE
Problem with open non protected mix archive (Protected MPQ)

### ISSUE THREAD

**Issue by 2020karaulov2020** [ladislav-zezula/StormLib#169]
Link https://drive.google.com/file/d/1HhoV_mV3y-3ws6znqkkeKd6MRO75n0LH/view
Please add support to open archive as original Storm.dll (with bypass all broken MPQ headers).
Or just share Mpq Editor source code in github if no have time to developing...

**Comment by ladislav-zezula** [comment]
Fixed in commit 468292a0c4f0febef52337ba1f2d9e3f76ccac63.
MPQEditor was rebuilt and uploaded.

**Comment by 2020karaulov2020** [comment]
@ladislav-zezula thanks it works! /play secret

**Comment by 2020karaulov2020** [comment]
@ladislav-zezula but it not warcraft III map, this is just MPQ archive loaded with bigger than war3patch.mpq priority :)
