### ISSUE TITLE
MPQ Editor for debug/bugfix with StormLib (as dynamic library)

### ISSUE THREAD

**Issue by 2020karaulov2020** [ladislav-zezula/StormLib#170]
@ladislav-zezula you can build MpqEditor with StormLib as dynamic library ?
(For test bugs/bug fixes)

**Comment by ladislav-zezula** [comment]
I build it with statically linked StormLib.

**Comment by 2020karaulov2020** [comment]
@ladislav-zezula i know, but for test and write bugfixes need possibility to replace StormLib.dll , you can't add debug version ?

**Comment by ladislav-zezula** [comment]
MPQEditor is shit for testing stuff. That's what StormTest is for.
