### ISSUE TITLE
Encountered an unopenable map

### ISSUE THREAD

**Issue by repingan10** [ladislav-zezula/StormLib#172]
Hi borther I am using MpqEditor encountered an unopenable map. Hope you can help me see. I am using the latest mpqeditor. The map is wc3 Reforged map!
This is the download address: http://www.warchasersreforged.com/Human6proto.w3x

**Comment by repingan10** [comment]
This may be a new kind of encryption!

**Comment by ladislav-zezula** [comment]
The file is cut.

**Comment by repingan10** [comment]
Can't you download it?

**Comment by ladislav-zezula** [comment]
The file size is 49 212 130 bytes, whilst according the MPQ header, it should be 54 804 898 bytes.
