### ISSUE TITLE
Archive handles are not thread safe

### ISSUE THREAD

**Issue by namreeb** [ladislav-zezula/StormLib#175]
The `HANDLE` type used by `SFileOpenFile()` et al is actually a pointer to a context structure of type `TMPQArchive`.

I have an application where the user can specify an arbitrary number of worker threads, which each will try to read from MPQs.  I was having very strange failures where opening of random files would return `ERROR_FILE_CORRUPT` but only on Linux.  I'm not sure if I was silently having this problem on Windows too, but I never saw an error on Windows.

The problem went away when I protected my open file function which uses stormlib with a mutex, ensuring only one thread at a time was trying to read from the open MPQs.

Is there perhaps documentation somewhere about thread safety with stormlib?  I have looked but haven't found it.

If I have to keep my current mutex solution then so be it, but if I can be more precise then that would be preferable.

**Comment by ladislav-zezula** [comment]
StormLib is not thread safe.

**Comment by namreeb** [comment]
Okay.  Do you think it would work to open each MPQ once per thread to avoid the lock contention?

**Comment by ladislav-zezula** [comment]
Yes, or you can lock every file open on a particular archive.

**Comment by namreeb** [comment]
Thanks!  Using a `thread_local` manager solved my performance problem.

**Comment by glebm** [comment]
Is it only OpenFile that is thread-unsafe, or ReadFile as well?

**Comment by glebm** [comment]
It'd be great to have a thread-safe API. Diablo opens multiple audio files that it streams from.
