### ISSUE TITLE
Read an in-memory MPQ archive

### ISSUE THREAD

**Issue by fluxxu** [ladislav-zezula/StormLib#180]
Is there any way to open an MPQ archive in memory?
For example, to read from a `vector<uint8_t>`?
My use case is to open an MPQ archive inside a CASC storage. Using a temp file seems too slow.
Thanks!

**Comment by ladislav-zezula** [comment]
StormLib supports open a MPQ archive from a named memory mapped file (provided you are on Windows).
You can save the file to a memory mapped file (not really a difference from saving it to vector<uint8>.

`SFileOpenFileEx("map:NAME_OF_FILE_MAPPING", ...)`

**Comment by fluxxu** [comment]
I see, thanks!

**Comment by Slayer95** [comment]
@ladislav-zezula , excuse me. My reading from this https://github.com/ladislav-zezula/StormLib/blob/e10150c8c389e6cd2ce41f88a3c0331ed499fb81/src/StormPort.h#L306-L309 is that memory-mapped files are also supported in Linux. Am I getting something wrong?

**Comment by Slayer95** [comment]
> StormLib supports opening a memory mapped files that have a name (named sections):
> 
> ```
> if(SFileOpenArchive(szSectionName, 0, BASE_PROVIDER_MAP, &hMpq)
> {
>     // Success
> }
> ```
> 
> MPQ Editor utilizes this function when recovering MPQs from MIX files.

Alright, thanks!
