### ISSUE TITLE
MPQ Not Booting

### ISSUE THREAD

**Issue by kaytotes** [ladislav-zezula/StormLib#181]
I apologise in advance if this isn't the place for this. Basically i'm simply trying to do a basic get all files in X directory and dump into Y MPQ file. 

When packaging the MPQ appears to be created correctly and files _appear_ to be being added to it as the file size grows. However booting up in game changes are not reflected. 

For reference i'm trying to build an MPQ for WoW 3.3.5 Build 12340 enUS

I'm 100% confident it's not an issue with the modification itself as packing via MPQEditor and a bunch of other tools that I know inherit from StormLib provides a working MPQ.

If it makes any difference i'm building on Ubuntu 20.04.

Been tearing my hair out for a few days so any guidance appreciated.

Below is the relevant code snippet:

```
Beginning MPQ Building
Compressing Directory '/home/kaytotes/code/nozdormu/client/resources/patch-g' to MPQ file '/home/kaytotes/code/nozdormu/client/build/Patch-G.MPQ'
Writing '/home/kaytotes/code/nozdormu/client/resources/patch-g/Sound/Music/GlueScreenMusic/Wotlk_Main_title.mp3' to '/Sound/Music/GlueScreenMusic/Wotlk_Main_title.mp3'
Done! Exiting...
```

```c++
void compress(int argc, char * argv[])
{
    std::cout << "Beginning MPQ Building" << std::endl;

    if (! optionExists(argv, argv+argc, "-d") || ! optionExists(argv, argv+argc, "-f")) {
        std::cout << "Missing either '-d' or '-f' flags. Check inputs with '-h' flag." << std::endl;
    }

    std::string directory = getOption(argv, argv + argc, "-d");
    std::string name = getOption(argv, argv + argc, "-f");

    std::cout << "Compressing Directory '" << directory << "' to MPQ file '" << name << "'" << std::endl;
    std::vector<std::string> files = getFiles(directory);

    /** Delete file if already exists */
    remove(name.c_str());

    HANDLE mpq;

    if (! SFileCreateArchive(name.c_str(), MPQ_FORMAT_VERSION_2 | MPQ_CREATE_ARCHIVE_V2 | MPQ_CREATE_LISTFILE | MPQ_CREATE_ATTRIBUTES, 4000, &mpq)) {
        std::cout << "Failed to create initial MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }

    for (auto str : files) {
        if (filesys::is_directory(str)) {
            continue;
        }

        std::size_t pos = str.find(directory);
        std::string mpqFileName = str.substr(directory.length());
        mpqFileName = mpqFileName.substr(1);

        std::cout << "Writing '" << str << "' to '" << mpqFileName << "'" << std::endl;

        if (! SFileAddFile(mpq, str.c_str(), mpqFileName.c_str(), MPQ_FILE_REPLACEEXISTING)) {
            std::cout << "Failed to write '" << mpqFileName.c_str() << "' to MPQ: " << GetLastError() << std::endl;

            exit(EXIT_FAILURE);
        }
    }

    if (! SFileCompactArchive(mpq, NULL, false)) {
        std::cout << "Failed to compress MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }

    if (! SFileCloseArchive(mpq)) {
        std::cout << "Failed to finalise MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }
}
```

**Comment by ladislav-zezula** [comment]
At the first sight, you are creating archive version 2 (MPQ_CREATE_ARCHIVE_V2). If I recall correctly, version 2 was used since WoW Cataclysm, aka 4.0.Dne 8. 7. 2020 0:50 napsal uživatel Kaytotes <notifications@github.com>:
I apologise in advance if this isn't the place for this. Basically i'm simply trying to do a basic get all files in X directory and dump into Y MPQ file.
When packaging the MPQ appears to be created correctly and files appear to be being added to it as the file size grows. However booting up in game changes are not reflected.
For reference i'm trying to build an MPQ for WoW 3.3.5 Build 12340 enUS
I'm 100% confident it's not an issue with the modification itself as packing via MPQEditor and a bunch of other tools that I know inherit from StormLib provides a working MPQ.
If it makes any difference i'm building on Ubuntu 20.04.
Been tearing my hair out for a few days so any guidance appreciated.
Below is the relevant code snippet:
void compress(int argc, char * argv[])
{
    std::cout << "Beginning MPQ Building" << std::endl;

    if (! optionExists(argv, argv+argc, "-d") || ! optionExists(argv, argv+argc, "-f")) {
        std::cout << "Missing either '-d' or '-f' flags. Check inputs with '-h' flag." << std::endl;
    }

    std::string directory = getOption(argv, argv + argc, "-d");
    std::string name = getOption(argv, argv + argc, "-f");

    std::cout << "Compressing Directory '" << directory << "' to MPQ file '" << name << "'" << std::endl;
    std::vector<std::string> files = getFiles(directory);

    /** Delete file if already exists */
    remove(name.c_str());

    HANDLE mpq;

    if (! SFileCreateArchive(name.c_str(), MPQ_CREATE_ARCHIVE_V2 | MPQ_CREATE_LISTFILE | MPQ_CREATE_ATTRIBUTES, HASH_TABLE_SIZE_MAX, &mpq)) {
        std::cout << "Failed to create initial MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }

    for (auto str : files) {
        std::size_t pos = str.find(directory);
        std::string mpqFileName = str.substr(directory.length());

        SFileAddFile(mpq, str.c_str(), mpqFileName.c_str(), MPQ_FILE_REPLACEEXISTING);
    }

    SFileCompactArchive(mpq, NULL, false);

    if (! SFileCloseArchive(mpq)) {
        std::cout << "Failed to finalise MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }
}

**Comment by kaytotes** [comment]
I have tried to use older MPQ version and still same result. 

```
    if (! SFileCreateArchive(name.c_str(), MPQ_FORMAT_VERSION_1 | MPQ_CREATE_ARCHIVE_V1 | MPQ_CREATE_LISTFILE | MPQ_CREATE_ATTRIBUTES, 4000, &mpq)) {
        std::cout << "Failed to create initial MPQ: " << GetLastError() << std::endl;

        exit(EXIT_FAILURE);
    }
```

When I open the final MPQ with MPQEditor.exe everything _appears_ to be present and in the correct directory structure.

**Comment by ladislav-zezula** [comment]
Well, I am not particularly expert for building files for games.

**Comment by kaytotes** [comment]
I appreciate that. Thanks for your assistance nonetheless. Will keep messing with flags and see what I can come up with. 

Feel free to close this.
