### ISSUE TITLE
Problem with open MPQ archives (Protected)

### ISSUE THREAD

**Issue by TeraForce** [ladislav-zezula/StormLib#182]
[Sample01.zip](https://github.com/ladislav-zezula/StormLib/files/5031645/Sample01.zip)
Help! It's a starcraft ii mod. which can't open...

**Comment by ladislav-zezula** [comment]
The MPQ header's MD5 does not match. The archive is corrupt.

**Comment by TeraForce** [comment]
I'm sure the SC2 can open the document, the game can load it but even the editor of SC2 will get crash.

**Comment by TeraForce** [comment]
the offset C0h is wrong (md5), but it really a mpq document from the battlenet cache.

**Comment by TeraForce** [comment]
it was named as e41f710d11ffd2108dbeec450f25e01c9c76cf221f023a3f909ca0056433af31.s2ma in the cache.
the sha256 of it should matched to this sample

**Comment by TeraForce** [comment]
[Sample02.zip](https://github.com/ladislav-zezula/StormLib/files/5037853/Sample02.zip)
i think the same protect also exists in this one. which i have make sure the sc2 can open/read it.

**Comment by TeraForce** [comment]
i have found some breakpoints to put (seems like SFileReadFile function), which it hits when the game attempt to read any file from mpq archives, this can expose the file name in archive, file size, and follow it can get the file data in memory. (maybe can help to working out this issue?)

**Comment by TeraForce** [comment]
i have test with a normal map file. which it can be open normally, if i change the md5 hash manually by edit the hex of file, offset 0xC0. the editor can not open the document any longer. (not throw the missing dependency messagebox.)
but the sample02, no matter keep the error md5 or edit it to other hex. offset 0xC0, the editor throws the missing dependency messagebox everytime. seems could open it.

**Comment by ladislav-zezula** [comment]
I removed header hash check from StormLib. When I rebuilt MPQ Editor with the new StormLib, it could open both Sample01 and Sample02, but there are no files.

**Comment by TeraForce** [comment]
> I removed header hash check from StormLib. When I rebuilt MPQ Editor with the new StormLib, it could open both Sample01 and Sample02, but there are no files. I'll keep StormLib as it is, until I find a map that contains something.

what means find a map that contains something..?

**Comment by ladislav-zezula** [comment]
> what means find a map that contains something..?

The two samples you sent contain nothing (aka no files).

**Comment by TeraForce** [comment]
> > what means find a map that contains something..?
> 
> The two samples you sent contain nothing (aka no files).

why i send two empty archives.. the sc2 editor can open/read the files in those archives.

**Comment by TeraForce** [comment]
[Sample02-DocumentInfo.zip](https://github.com/ladislav-zezula/StormLib/files/5046189/Sample02-DocumentInfo.zip)

please see the 'Sample02-DocumentInfo.zip'.
i have made it.

this should be enough to prove the the document Sample02.SC2Map has the '\DocumentInfo'

in test environment, open the editor, and prepare the breakpoints, put on two location.
1. SC2Editor_x64.exe+2B62132 -> rsi size of file, [rcx]+E8 is filepath (maybe file name only) (the filepath in the archive)
2. SC2Editor_x64.exe+2B62205 -> rbx points to data which it reads.
that means every time sc2 editor try load a file from the mpq archive, it will meet breakpoint 1, after read the file, it will meet breakpoint 2.

after the breakpoints ready, drag the Sample02.SC2Map to the sc2 edtior.

the first time breakpoint hit, (attributes) file. at this time, the RAX points to the memory region seems mentioned the header hash is invalid. (see the picture RAX.png)
and the second time hits, its the file i assumed (DocumentInfo).

i have dump the data which read by edtior (breakpoint 2 hit, rbx points to data) to the file DocumentInfo. (it's pure, same xml file to other sc2 maps.) (length is 0x41B2, see the rsi of Breakpoint 1 Hit.png)

**Comment by ladislav-zezula** [comment]
I am sorry, you were right. StormLib incorrectly handled MPQ Archives v 4.0, which have fake MPQ headers. I fixed it in commit https://github.com/ladislav-zezula/StormLib/commit/ac0dfb94b0a2482f06c2dbff11104448857640a1. I also rebuilt MPQ Editor.

**Comment by TeraForce** [comment]
> I am sorry, you were right. StormLib incorrectly handled MPQ Archives v 4.0, which have fake MPQ headers. I fixed it in commit [ac0dfb9](https://github.com/ladislav-zezula/StormLib/commit/ac0dfb94b0a2482f06c2dbff11104448857640a1). I also rebuilt MPQ Editor.

Thank you very much!

**Comment by TeraForce** [comment]
would you please send me the StormLib.dll of this new version? in fact i dont know how to compile it..

**Comment by ladislav-zezula** [comment]
Download link: http://www.zezula.net/download/stormlib_dll.zip

**Comment by TeraForce** [comment]
> Download link: http://www.zezula.net/download/stormlib_dll.zip

thanks

**Comment by retardfest** [comment]
So you basically does nothing to reverse enginner this protection, rather bags ladislav-zezula to reverse enginner it instead of you and yet you brags for it all over the place like you did whole thing lmao

**Comment by retardfest** [comment]
this cringefest. also @ladislav-zezula , please stop doing skiddy's job instead, rather make them to do it themself.

**Comment by TeraForce** [comment]
> So you basically does nothing to reverse enginner this protection, rather bags ladislav-zezula to reverse enginner it instead of you and yet you brags for it all over the place like you did whole thing lmao

i dont say 'i patched', i just says, its patched. do i?
and in fact i do not have any interests on those two maps, at least now.

**Comment by TeraForce** [comment]
> So you basically does nothing to reverse enginner this protection, rather bags ladislav-zezula to reverse enginner it instead of you and yet you brags for it all over the place like you did whole thing lmao

and in my qq group, i dont use discord, i says that zezula made it. i believe he can. i just prove the document its not empty. i dont say that i patched at all.
