### ISSUE TITLE
Stop helping chinese script kiddies?

### ISSUE THREAD

**Issue by retardfest** [ladislav-zezula/StormLib#183]
Sorry if title offends you.

SC2 map scene is plagued with chinese skids whom are continuasly steals NA maps to CN server, and modifies it for P2P by modifing map script.

Can you stop helping them, please? at least make them to do their own research.

**Comment by ladislav-zezula** [comment]
The issue you are probably referring to was, however, in fact a bug in processing MPQ archives. Aka bug in the MPQ library.

**Comment by retardfest** [comment]
@ladislav-zezula which doesnt happens when MPQ isnt manapulated artifically. yet you "fixes" it and that is deprotecting.

**Comment by retardfest** [comment]
you also knows that, since you defines new const as "fake header".

**Comment by retardfest** [comment]
w/e tho. your lib, your codes, your decision. but i really want you to stop helping skids.

**Comment by TeraForce** [comment]
> Sorry if title offends you.
> 
> SC2 map scene is plagued with chinese skids whom are continuasly steals NA maps to CN server, and modifies it for P2P by modifing map script.
> 
> Can you stop helping them, please? at least make them to do their own research.

i'm not the one which plagued the game environment.
over.

**Comment by retardfest** [comment]
> 
> 
> > Sorry if title offends you.
> > SC2 map scene is plagued with chinese skids whom are continuasly steals NA maps to CN server, and modifies it for P2P by modifing map script.
> > Can you stop helping them, please? at least make them to do their own research.
> 
> i'm not the one which plagued the game environment.
> over.

Still you datamines NA maps and releases them to public, arentcha?

**Comment by TeraForce** [comment]
> > > Sorry if title offends you.
> > > SC2 map scene is plagued with chinese skids whom are continuasly steals NA maps to CN server, and modifies it for P2P by modifing map script.
> > > Can you stop helping them, please? at least make them to do their own research.
> > 
> > 
> > i'm not the one which plagued the game environment.
> > over.
> 
> Still you datamines NA maps and releases them to public, arentcha?

who releases them to public? you sure its me? you must give me the link.

**Comment by retardfest** [comment]
>AND who are you, you know me? i'm really angry now, i hate anyone, no matter who, throw mud on me.

lmao you are just nonamer script kiddy who begs other gurus to do jobs for you. dont even pretend you have any fames on this scene, retard.

**Comment by TeraForce** [comment]
> > AND who are you, you know me? i'm really angry now, i hate anyone, no matter who, throw mud on me.
> 
> lmao you are just nonamer script kiddy who begs other gurus to do jobs for you. dont even pretend you have any fames on this scene, retard.

just block you this kind of idiots

**Comment by retardfest** [comment]
> just block
block covid to china plz k thx bye
