### ISSUE TITLE
SFileAddFileEx cause the document damaged

### ISSUE THREAD

**Issue by TeraForce** [ladislav-zezula/StormLib#185]
since the last time, the commit to open v4.0 mpq with fake headers, now the stormlib seems have problem when add files to mpq. the game editor will no longer load the mpq archive after add any file. also the old version of mpqeditor cant open it (display its empty). the game editor and the game cant recognize it. only the latest stormlib can open it. the situation also exists when using the latest mpqeditor.

**Comment by TeraForce** [comment]
all the mpq archive has this problem, i means normal mpqs, not with fake headers.

**Comment by ladislav-zezula** [comment]
Please, send me an example of a map that is corrupted as you describe.

**Comment by TeraForce** [comment]
[Issue.zip](https://github.com/ladislav-zezula/StormLib/files/5146771/Issue.zip)

SampleA.SC2Map is a normal MPQ Archive, can be opened by MPQEditor860 and MPQEditor854
and the MapScript.galaxy is extract from SampleA.SC2Map

if you use MPQEditor860 (latest ver) to open the SampleA.SC2Map, and add MapScript.galaxy to it. then the document becomes SampleB.SC2Map
the SampleB.SC2Map can only be opened by MPQEditor860, the MPQEditor854 think its empty. (also sc2 editor and the game cant open it)

but if you use MPQEditor854 to open it, add MapScript.galaxy to it. it wont have this problem. (both mpqeditor can still open it after the file added. also the sc2 edtior and the game)

**Comment by ladislav-zezula** [comment]
Thanks for your bug report. I prepared the proposed fix into separate branch:
https://github.com/ladislav-zezula/StormLib/tree/FixHashTable

Also, a beta version of MPQ Editor is ready:
http://www.zezula.net/download/mpqeditor_en_beta.zip

Please, check if it works for you and let me know.

**Comment by TeraForce** [comment]
it works, both of it (stormlib and mpqeditor).
thanks :)
