### ISSUE TITLE
add namespace to the lib?

### ISSUE THREAD

**Issue by meilaopo** [ladislav-zezula/StormLib#189]
the lib defined 
```
//-----------------------------------------------------------------------------
// Structure for bit arrays used for HET and BET tables

typedef struct _TBitArray
{
    DWORD NumberOfBytes;                        // Total number of bytes in "Elements"
    DWORD NumberOfBits;                         // Total number of bits that are available
    BYTE Elements[1];                           // Array of elements (variable length)
} TBitArray;

```

I am build this lib with Unreal Engine 4, while Unreal Engine 4 already defined TBitArray

**Comment by ladislav-zezula** [comment]
The structure was not really meant to be public, I made it private. The changes are in a separate branch. Could you please try if that will work for you?

Branch: https://github.com/ladislav-zezula/StormLib/tree/TBitArrayChangedToPrivate

**Comment by meilaopo** [comment]
> The structure was not really meant to be public, I made it private. The changes are in a separate branch. Could you please try if that will work for you?
> 
> Branch: https://github.com/ladislav-zezula/StormLib/tree/TBitArrayChangedToPrivate

TBitArray and others macro have same name with UE4, such as PLATFORM_XXX, I think namespace and StormLib_ prefix will solve these problem

```
STORMLIB_PLATFORM_WINDOWS
STORMLIB_PLATFORM_LINUX
STORMLIB_PLATFORM_XXX
```

**Comment by ladislav-zezula** [comment]
Next iteration:
* `PLATFORM_DEFINED` changed to `STORMLIB_PLATFORM_DEFINED`
* `PLATFORM_XXX` changed to `STORMLIB_XXX`

Please, try with your project.

**Comment by RPG3D** [comment]
> Next iteration:
> 
> * `PLATFORM_DEFINED` changed to `STORMLIB_PLATFORM_DEFINED`
> * `PLATFORM_XXX` changed to `STORMLIB_XXX`
> 
> Please, try with your project.

```
StormLib.h(483): error C4099: 'TBitArray': type name first seen using 'class' now seen using 'struct'
```

**Comment by ladislav-zezula** [comment]
Changed to class. If that won't help, I'll remove it from `StormLib.h` altogether.

**Comment by meilaopo** [comment]
> Changed to class. If that won't help, I'll remove it from `StormLib.h` altogether.

change TBitArray to StormLib_TBitArray fix compile error
