### ISSUE TITLE
StormLib and _dll

### ISSUE THREAD

**Issue by OneMeanDragon** [ladislav-zezula/StormLib#192]
seems theres some missing pieces in both
```CPP
1>'PostBuild.bat' is not recognized as an internal or external command,
1>operable program or batch file.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: The command "PostBuild.bat StormLib x64 DebugUS
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd" exited with code 9009.
1>Done building project "StormLib_vs19.vcxproj" -- FAILED.
```

and in the _dll project the dllmain.rc file was missing lol, though i removed the missing file and it ended up compiling under the latest version of the sdk i have.

**Comment by ladislav-zezula** [comment]
Added missing files in https://github.com/ladislav-zezula/StormLib/commit/fe0e63449bced71eb829653f3c10ba01d15bfa22.

**Comment by OneMeanDragon** [comment]
good to see your keeping up to date unlike the sfmpq lol

**Comment by OneMeanDragon** [comment]
_dll missing resource.h lol

**Comment by ladislav-zezula** [comment]
> good to see your keeping up to date unlike the sfmpq lol

I always thought `sfmpq` was not updated since like 2000 or so.

Missing file added.

**Comment by OneMeanDragon** [comment]
think most recent update he did was like 8 or 9 years ago lol
