### ISSUE TITLE
Windows Make WinDDK Required

### ISSUE THREAD

**Issue by DaleFoley** [ladislav-zezula/StormLib#195]
I'm trying to compile StormLib using the instructions outlined in the README.md but it looks like this project uses an old version of windows driver kit (where WDK was using build.exe, later versions use MSBuild.exe now). Do we know which version we specifically need to download and where it can be downloaded from? I've tried finding older versions on microsoft's website but no luck. I also tried downloading VS2015 as I thought I might be able to download driver kits through that but windows 10 won't even let me install VS2015.

[Error Output](https://imgur.com/a/UxmaKYt)

**Comment by ladislav-zezula** [comment]
The "make.bat" that is included is basically for my own purposes. It requires WDK 6001 which I still sometimes use for building stuff.
You probably want to use "make-msvc.bat" instead. Please, let me know if it works for you.

**Comment by DaleFoley** [comment]
Hi, thanks for your speedy reply. This is the following output I now get using "make-msvc.bat":

'""' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'""' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'""' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'""' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.
'devenv.com' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ladislav-zezula** [comment]
Do you have Visual Studio installed?

**Comment by DaleFoley** [comment]
Yes, versions 2017 and 2019 community editions I believe.

**Comment by ladislav-zezula** [comment]
Could we perhaps connect via an instant messenger in order to solve this more interactively?
(Skype, Discord, Messenger)

**Comment by DaleFoley** [comment]
No problem, discord will work for me. Dale#8748
