### ISSUE TITLE
noobie help

### ISSUE THREAD

**Issue by alexpineda** [ladislav-zezula/StormLib#199]
HI,

I'm attempting to create a basic command line program that I can pipe into and out of for a node integration. I may eventually create a native node extension, but one step at a time 👍 

I'm trying to get just the basics working. There is no error code, and the output buffer length (dstSize) always remains the same, and the output buffer itself comes back empty. Any obvious problems here?

```c++

#define STORMLIB_NO_AUTO_LINK
#include <StormLib.h>

int main() {
  int success;
  
  int srcSize = 3;
  unsigned char* srcBuf = new unsigned char[srcSize];
  srcBuf[0] = 69;
  srcBuf[1] = 77;
  srcBuf[2] = 99;
  
  int dstSize = 3;
  unsigned char * dstBuf = new unsigned char[dstSize];
  dstBuf[0] = 0;
  dstBuf[1] = 0;
  dstBuf[2] = 0;
  
  success = SCompImplode(dstBuf, &dstSize, srcBuf, srcSize);
  
  if (success == 0) {
     throw std::exception("implode failed ");
  }
}
```

**Comment by ladislav-zezula** [comment]
Yes. There is an obvious problem that you didn't even bother to read the documentation.
http://www.zezula.net/en/mpq/stormlib.html

**Comment by alexpineda** [comment]
What you linked does not lead me to any new information. I read the documentation, and read through the test files. I don't utilize the mpq container as you do in the examples so it was a little bit more difficult for me to isolate the use of the function. I'm using this for SC replays where I'm sending each chunk to get compressed. 

The only different part I see is the use of LPBYTE, however because my full implementation reads from std::cin I can't cast to LPBYTE. At least I don't think so.

My actually implementation is such. I'm not a c++ coder. Just doing what I can. Thanks for your attention.

```c++
	char b;

	_setmode(_fileno(stdin), _O_BINARY);
	_setmode(_fileno(stdout), _O_BINARY);

	std::vector<unsigned char> rawInput;
	while(std::cin.read(&b, 1)) {
		rawInput.push_back(b);
	}

	int srcSize = rawInput.size() - 2; //account for windows line end
	int dstSize = rawInput.size() + 0x100;
	unsigned char* srcBuf = new unsigned char[srcSize];
        unsigned char * dstBuf = (BYTE *)malloc(dstSize * sizeof(BYTE));

	if (srcSize > 0) {
		for (int i = 0; i < srcSize; i++) {
			srcBuf[i] = rawInput[0];
		}
                for (int i = 0; i < dstSize; i++) {
			dstBuf[i] = 0;
		}
	}

int success = SCompImplode(dstBuf, &dstSize, srcBuf, srcSize);
```

**Comment by ladislav-zezula** [comment]
```
    char * srcBuff = "This is a data to be compressed";
    char dstBuff[0x1000];
    int cbOutBuffer = sizeof(dstBuff);
    int cbInBuffer = (int)strlen(srcBuff);

    SCompImplode(dstBuff, &cbOutBuffer, srcBuff, cbInBuffer);
```

**Comment by alexpineda** [comment]
Thank you. That did work. Actually I had a big break through today with emscripten, so I won't need to create a node extension. https://github.com/imbateam-gg/pkware-wasm thank you!!
