### ISSUE TITLE
cannot convert parameter 1 from 'const char *' to 'const TCHAR *

### ISSUE THREAD

**Issue by TheReVeaLz** [ladislav-zezula/StormLib#201]
I just want to update ghost++ stormlib but I'm getting this error message, do you have any idea and can you help me?

Source code : https://code.google.com/archive/p/ghostplusplus/downloads

**Function**

	string MapMPQFileName = m_GHost->m_MapPath + m_MapLocalPath;
	HANDLE MapMPQ;
	bool MapMPQReady = false;

	if( SFileOpenArchive( MapMPQFileName.c_str( ), 0, MPQ_OPEN_FORCE_MPQ_V1, &MapMPQ ) )
	{
		CONSOLE_Print( "[MAP] loading MPQ file [" + MapMPQFileName + "]" );
		MapMPQReady = true;
	}
	else
		CONSOLE_Print( "[MAP] warning - unable to load MPQ file [" + MapMPQFileName + "]" );

**Output log**

	1>.\map.cpp(271) : error C2664: 'SFileOpenArchive' : cannot convert parameter 1 from 'const char *' to 'const TCHAR *'
	1>        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
	1>ghost.cpp
	1>.\ghost.cpp(1392) : error C2664: 'SFileOpenArchive' : cannot convert parameter 1 from 'const char *' to 'const TCHAR *'
	1>        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
	1>Build log was saved at "file://c:\Users\Administrator\Downloads\ghostplusplus_17.1\ghost\ghost\Release MySQL\BuildLog.htm"
	1>ghost - 2 error(s), 0 warning(s)

**Comment by ladislav-zezula** [comment]
I assume you build StormLib with UNICODE support, which is the default settings. With that settings, every function with a `const TCHAR *` (or `LPCTSTR`) becomes `const wchar_t *`.
So change your program to support UNICODE (use `wstring`). This also brings the possibility to open files with non-ANSI names (Chinese, Japanese, Korean).

**Comment by TheReVeaLz** [comment]
I'm haven't build StormLib yet, the source code error from call a function from StormLib.h

**ghostplusplus_17.1\ghost\ghost\map.cpp**

	#define __STORMLIB_SELF__
	#include <src/StormLib.h> 
	string MapMPQFileName = m_GHost->m_MapPath + m_MapLocalPath;
	.......
	if( SFileOpenArchive( MapMPQFileName.c_str( ), 0, MPQ_OPEN_FORCE_MPQ_V1, &MapMPQ ) )     //Error line
	.......

also I'm using Visual Studio 2008 (Which is GHost++ source code was created).

**Comment by ladislav-zezula** [comment]
You did not do what I wanted. You store the `MapMPQFileName` in `string`. Store it in `wstring`, you should be fine.

**Comment by TheReVeaLz** [comment]
I did it but I got a lot of error
**Output Log**

	1>.\map.cpp(267) : error C2440: 'initializing' : cannot convert from 'std::basic_string<_Elem,_Traits,_Ax>' to 'std::basic_string<_Elem,_Traits,_Ax>'
	1>        with
	1>        [
	1>            _Elem=char,
	1>            _Traits=std::char_traits<char>,
	1>            _Ax=std::allocator<char>
	1>        ]
	1>        and
	1>        [
	1>            _Elem=wchar_t,
	1>            _Traits=std::char_traits<wchar_t>,
	1>            _Ax=std::allocator<wchar_t>
	1>        ]
	1>        No constructor could take the source type, or constructor overload resolution was ambiguous
	1>.\map.cpp(273) : error C2784: 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1857) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1857) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1857) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1857) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1746) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1746) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1746) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy> std::operator +(_Difft,std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>)' : could not deduce template argument for 'std::_Vb_const_iterator<_Sizet,_Difft,_MycontTy>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(1746) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_iterator<_Ty,_Alloc> std::operator +(_Vector_iterator<_Ty,_Alloc>::difference_type,std::_Vector_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(409) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_iterator<_Ty,_Alloc> std::operator +(_Vector_iterator<_Ty,_Alloc>::difference_type,std::_Vector_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(409) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_iterator<_Ty,_Alloc> std::operator +(_Vector_iterator<_Ty,_Alloc>::difference_type,std::_Vector_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(409) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_iterator<_Ty,_Alloc> std::operator +(_Vector_iterator<_Ty,_Alloc>::difference_type,std::_Vector_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(409) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_const_iterator<_Ty,_Alloc> std::operator +(_Vector_const_iterator<_Ty,_Alloc>::difference_type,std::_Vector_const_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_const_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(277) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_const_iterator<_Ty,_Alloc> std::operator +(_Vector_const_iterator<_Ty,_Alloc>::difference_type,std::_Vector_const_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_const_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(277) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_const_iterator<_Ty,_Alloc> std::operator +(_Vector_const_iterator<_Ty,_Alloc>::difference_type,std::_Vector_const_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_const_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(277) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Vector_const_iterator<_Ty,_Alloc> std::operator +(_Vector_const_iterator<_Ty,_Alloc>::difference_type,std::_Vector_const_iterator<_Ty,_Alloc>)' : could not deduce template argument for 'std::_Vector_const_iterator<_Ty,_Alloc>' from 'std::wstring'
	1>        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\vector(277) : see declaration of 'std::operator +'
	1>.\map.cpp(273) : error C2784: 'std::_Deque_iterator<_Ty,_Alloc,_Secure_validation> std::operator +(_Deque_iterator<_Ty,_Alloc,_Secure_validation>::difference_type,std::_Deque_iterator<_Ty,_Alloc,_Secure_validation>)' : could not deduce template argument for 'std::_Deque_iterator<_Ty,_Alloc,_Secure_validation>' from 'std::wstring'
	
	.......

	1>ghost - 192 error(s), 4 warning(s)
	========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by ladislav-zezula** [comment]
If your entire project uses normal strings, you can also convert it to UNICODE right before calling SFileOpenArchive
```
string MapMPQFileName = m_GHost->m_MapPath + m_MapLocalPath;
HANDLE MapMPQ;
TCHAR szMapMpqName[MAX_PATH];
bool MapMPQReady = false;

MultiByteToWideChar(CP_ACP, 0, MapMPQFileName.c_str( ), MapMPQFileName.size() + 1, szMapMpqName, _countof(szMapMpqName));
if( SFileOpenArchive( szMapMpqName, 0, MPQ_OPEN_FORCE_MPQ_V1, &MapMPQ ) )
{
	CONSOLE_Print( "[MAP] loading MPQ file [" + MapMPQFileName + "]" );
	MapMPQReady = true;
}
else
	CONSOLE_Print( "[MAP] warning - unable to load MPQ file [" + MapMPQFileName + "]" );
```

**Comment by TheReVeaLz** [comment]
After using the conversion code I get another error like this, dunno what's wrong

	1>Linking...
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileOpenArchive@16
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileGetFileSize@8
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileReadFile@20
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileCloseFile@4
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileCloseArchive@4
	1>ghost.obj : error LNK2001: unresolved external symbol _SFileOpenFileEx@16
	1>C:\Users\Administrator\Downloads\ghostplusplus_17.1\ghost\Release MySQL\ghost.exe : fatal error LNK1120: 6 unresolved externals
	1>Build log was saved at "file://c:\Users\Administrator\Downloads\ghostplusplus_17.1\ghost\ghost\Release MySQL\BuildLog.htm"
	1>ghost - 7 error(s), 4 warning(s)
	========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by ladislav-zezula** [comment]
You need to add the stormlib static library to the project.

**Comment by TheReVeaLz** [comment]
This one? Still getting same error
![rsz_screenshot_1](https://user-images.githubusercontent.com/70447633/111375683-227f7f80-86d1-11eb-988e-0335b860f924.jpg)

**Comment by ladislav-zezula** [comment]
There is a [header construction]([url](https://github.com/ladislav-zezula/StormLib/blob/60c2dd0fa16d3506722e25fee9b6fa4082b0c1e5/src/StormLib.h#L107)) that does it for you. You must have done something that prevents it.

**Comment by TheReVeaLz** [comment]
Maybe can I ask something? StormLib was built by MS Visual Studio 2012, though GHost++ built by MS Visual Studio 2008 (with old StormLib which VS2008 could build).
There's any problem when I change stormlib to the latest version because Visual Studio version?

**Comment by ladislav-zezula** [comment]
Currently, there are projects for VS 2008 and VS2019. If you want to link both together, you need to make them built by the same version, otherwise you will not be able to link them. However, you should be able to update both of them to VS 2012.

**Comment by TheReVeaLz** [comment]
Thanks that's work, the problem is caused by wrong version of VS.

**Comment by TheReVeaLz** [comment]
Thanks that's work, the problem is caused by wrong version of VS.
