### ISSUE TITLE
Is there any option to extract only the "Files" that I have known its name? 

### ISSUE THREAD

**Issue by 1kaitoukid1** [ladislav-zezula/StormLib#210]
Is there any option to extract only the "Files" that I have known its name? (I have used ListFile before to get the Files'sname)

Also can you update your software so that I can choose actively the program "War3.exe" to run on Live Game Scanner because now most Korean maps must be run under the application "JNLoader.exe" ?

Sincere thanks!
Sorry for my bad English.

**Comment by ladislav-zezula** [comment]
Not sure if you are referring to StormLib or MPQEditor, but no, there isn't.Dne 1. 4. 2021 8:06 napsal uživatel 1kaitoukid1 ***@***.***>:
Is there any option to extract only the "Files" that I have known its name? (I have used ListFile before to get the Files'sname)

**Comment by 1kaitoukid1** [comment]
> Not sure if you are referring to StormLib or MPQEditor, but no, there isn't.Dne 1. 4. 2021 8:06 napsal uživatel 1kaitoukid1 ***@***.***>: Is there any option to extract only the "Files" that I have known its name? (I have used ListFile before to get the Files'sname) —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

i'm referring to MPQEditor
