### ISSUE TITLE
Replace WINAPI with STORMAPI

### ISSUE THREAD

**Issue by glebm** [ladislav-zezula/StormLib#211]
Can you please replace WINAPI with STORMAPI?
This will allow users to easily opt out of the Windows calling convention without lots of little changes to the code.

**Comment by ladislav-zezula** [comment]
Negative. It is common practice to also specify calling convention, especially on Windows. StormLib.h is a header file for both static LIB and for the DLL, where you have to specify a calling convention.

**Comment by glebm** [comment]
I guess we'll maintain our custom patch then. Makes upstreaming things harder though

**Comment by ladislav-zezula** [comment]
Why do you need to change the calling convention anyway?Libraries like zlib also have their own and nobody caresDne 1. 4. 2021 14:15 napsal uživatel Gleb Mazovetskiy ***@***.***>:
I guess we'll maintain our custom patch then. Makes upstreaming things harder though

**Comment by glebm** [comment]
We don't actually. I've fixed our code. :+1:
