### ISSUE TITLE
Default to no mmap

### ISSUE THREAD

**Issue by glebm** [ladislav-zezula/StormLib#215]
Currently the main issue we encounter when porting DevilutionX to a new platform is that StormLib assumes mmap availability by default.

Perhaps it'd be better if mmap defaulted to off, and was only enabled on the condition of:

```c
#if defined(__linux__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || defined(__DragonFly__)
#include <sys/mman.h>
#define STORMLIB_HAS_MMAP
#endif
```

**Comment by ladislav-zezula** [comment]
When adding new platform, add the whole new `#include` section to the existing ones in `StormPort.h`. If there is no map support, just don't put `#define STORMLIB_HAS_MMAP` there.

**Comment by glebm** [comment]
With my suggestion (and perhaps another tweak or two) we shouldn't even need to define these platforms.

This is the assumption that I want to weaken:
https://github.com/ladislav-zezula/StormLib/blob/95fabe8c0936e013d8764858d6eaf17b6a774e12/src/StormPort.h#L252
