### ISSUE TITLE
Unable to open .ASI files using MPQEditor

### ISSUE THREAD

**Issue by Hibabo** [ladislav-zezula/StormLib#217]
Hello Zezula, I've read through some of the conversations you've had with Unryze and came across several .asi files using the same kind of protection described [here](https://github.com/ladislav-zezula/StormLib/issues/112) This seems to be the new big thing for chinese protection when it comes to mix/asi file formats (since asi and mix files are basically the same) I've got one that I would like to open using MPQEditor but everytime I attempt to do so it throws a failed to open file wrong format my way

heres the [file](https://drive.google.com/file/d/1E4o6eo1UTRdaDn1lkx7pCyOftZQaeiqx/view?usp=sharing) in question

It has files inside since attempting to launch the map without the .asi file in your folder will lead to the map missing basically every model, if you need the map I can send a link your way as well please help out because I'm clueless and I dont have any experience in hex or mpq headers.

I can also send you another .asi using the same kind of protection if you need it just let me know, 

thanks.

**Comment by ladislav-zezula** [comment]
The MPQ has different file markers. That is, there is different MPQ signature and also different encryption keys for both hash table and block table. To open it properly, you need to:

 1) Download the latest build of MPQ Editor
 2) Create an INI file, with the name of `grandparty.ini`. Put in the content below
 3) Place the INI file to the same folder where you placed `grandparty.asi`.
 4) Open the `grandparty.asi` with MPQ Editor as usual. If you have listfiles, use a listfile for "Warcraft III Maps".

Let me know it it works for you.

Content of the INI file:
```
[MpqMarkers]
MpqSignature=0x58485343
HashTableKey=(cash table)
BlockTableKey=(clock table)
```

**Comment by ladislav-zezula** [comment]
The MPQ has different file markers. That is, there is different MPQ signature and also different encryption keys for both hash table and block table. To open it properly, you need to:

 1) Download the latest build of MPQ Editor
 2) Create an INI file, with the name of `grandparty.ini`. Put in the content below
 3) Place the INI file to the same folder where you placed `grandparty.asi`.
 4) Open the `grandparty.asi` with MPQ Editor as usual. If you have listfiles, use a listfile for "Warcraft III Maps".

Let me know it it works for you.

Content of the INI file:
```
[MpqMarkers]
MpqSignature=0x58485343
HashTableKey=(cash table)
BlockTableKey=(clock table)
```

**Comment by ladislav-zezula** [comment]
> I can also send you another .asi using the same kind of protection if you need it just let me know,
Yes please.

**Comment by Hibabo** [comment]
I'll send you two instead of one.

One of which was fixed by a korean guy on cafe naver, he only provided a picture of it and did not provide a link to a working version.

Heres the [link](https://drive.google.com/file/d/1hLoL-njF1pZ1OaDQVBtTevKqJGbSuY9g/view) of the one mentioned above and heres a picture of him somehow making it work 
![image](https://user-images.githubusercontent.com/67027827/114843679-5afea000-9dda-11eb-989a-0e0adda9f38c.png)

And [here](https://drive.google.com/u/0/uc?id=1EHMjX2PmQK-NG--Fk07wzAHsJzS6CyeR&export=download) is the other file which also has the protection.

**Comment by ladislav-zezula** [comment]
Thank you. Get the latest MPQ Editor and open as normal.
