### ISSUE TITLE
MPQ Editor name scanner locale

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#220]
Is there an option to change the locale used by name scanner feature? Have a map with all files in Korean locale and running name scanner finds 0 files so I am guessing its because of the locale. Tried changing the locale in compatibility menu but that seems to be for new files and not file searching?

If I add listfile with war3map.j it does find it, so I guess adding listfile does try all locales.

I also tried using SFILE_OPEN_ANY_LOCALE and it didn't work either but that might be just an issue of the library I am using that does the dll mappings.

**Comment by ladislav-zezula** [comment]
Send me the map, I'll check that out. Also, do you have another (unprotected) map with Korean names? I'd like to check that out

**Comment by juvian** [comment]
This is the map: https://drive.google.com/file/d/1XlJ-s0glLAbdhAo0defsLNcJZVRxGgps/view?usp=sharing

Don't have the unprotected version of this map, have some unprotected Korean maps but without files in Korean locale

**Comment by ladislav-zezula** [comment]
The map can't even be loaded in Warcraft III version 1.26a.

**Comment by juvian** [comment]
Well, as files are in korean locale I think it requires korean warcraft, haven't been able to get map to work on english install (even replacing War3.mpq with korean one), but it works in 1.28.5 korean wacraft install: https://m16.me/Down/2551. Map uses custom blizzard.j so don't think it would work on 1.27 or 1.26 without changing that.  

Sounds great, will wait for new version then. Do you mind meanwhile sharing the name scanner result? Can also test with that if by making new mpq with standard locale it would work in english 1.28.5 at least. 

Thanks for your continued work on this over the years, very appreciated ^^

**Comment by ladislav-zezula** [comment]
[listfile.zip](https://github.com/ladislav-zezula/StormLib/files/6440007/listfile.zip)

**Comment by ladislav-zezula** [comment]
You can download beta version of the MPQ Editor that can deal with various locales in the name-scanned maps.
