### ISSUE TITLE
Precedence rules?

### ISSUE THREAD

**Issue by namreeb** [ladislav-zezula/StormLib#221]
I'm wondering if a file exists in three different MPQs, how do we know which MPQ is the "correct" version?  Are there rules about which MPQs take precedence?  I've tried reversing a game that loads MPQs.  That game has a function named `SFileOpenFileEx`, which seems to make a decision on which archive to use based on some hash table or something.

Apologies if this is not a good place to ask this question, but I thought it would be less annoying than an email.  And perhaps someone else out there might know (or benefit from) the answer.

**Comment by ladislav-zezula** [comment]
IIRC games load all MPQs in a certain order (patches first) and then search each loaded MPQ for a given file. StormLib doesn't have such support.
