### ISSUE TITLE
unable to build with cmake on macOS using Clang 12

### ISSUE THREAD

**Issue by kambala-decapitator** [ladislav-zezula/StormLib#222]
```sh
cd some_build_dir
cmake /path/to/stormlib
cmake --build .
```

configure output:
<details><pre>-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Found BZip2: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libbz2.tbd (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Linking against dependent libraries statically
-- Configuring done
-- Generating done
-- Build files have been written to: ...</pre></details>

build output:
<details><pre>Scanning dependencies of target storm
[  0%] Building CXX object CMakeFiles/storm.dir/src/adpcm/adpcm.cpp.o
[  0%] Building CXX object CMakeFiles/storm.dir/src/huffman/huff.cpp.o
[  1%] Building C object CMakeFiles/storm.dir/src/jenkins/lookup3.c.o
[  1%] Building C object CMakeFiles/storm.dir/src/lzma/C/LzFind.c.o
[  2%] Building C object CMakeFiles/storm.dir/src/lzma/C/LzmaDec.c.o
[  2%] Building C object CMakeFiles/storm.dir/src/lzma/C/LzmaEnc.c.o
[  3%] Building C object CMakeFiles/storm.dir/src/pklib/explode.c.o
[  3%] Building C object CMakeFiles/storm.dir/src/pklib/implode.c.o
[  4%] Building CXX object CMakeFiles/storm.dir/src/sparse/sparse.cpp.o
[  4%] Building CXX object CMakeFiles/storm.dir/src/FileStream.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/FileStream.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/FileStream.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  4%] Building CXX object CMakeFiles/storm.dir/src/SBaseCommon.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseCommon.cpp:15:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseCommon.cpp:15:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  5%] Building CXX object CMakeFiles/storm.dir/src/SBaseDumpData.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseDumpData.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseDumpData.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  5%] Building CXX object CMakeFiles/storm.dir/src/SBaseFileTable.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseFileTable.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseFileTable.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  6%] Building CXX object CMakeFiles/storm.dir/src/SBaseSubTypes.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseSubTypes.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SBaseSubTypes.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  6%] Building CXX object CMakeFiles/storm.dir/src/SCompression.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SCompression.cpp:16:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SCompression.cpp:16:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  7%] Building CXX object CMakeFiles/storm.dir/src/SFileAddFile.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileAddFile.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileAddFile.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  7%] Building CXX object CMakeFiles/storm.dir/src/SFileAttributes.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileAttributes.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileAttributes.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  8%] Building CXX object CMakeFiles/storm.dir/src/SFileCompactArchive.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileCompactArchive.cpp:14:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileCompactArchive.cpp:14:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  8%] Building CXX object CMakeFiles/storm.dir/src/SFileCreateArchive.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileCreateArchive.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileCreateArchive.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  8%] Building CXX object CMakeFiles/storm.dir/src/SFileExtractFile.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileExtractFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileExtractFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  9%] Building CXX object CMakeFiles/storm.dir/src/SFileFindFile.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileFindFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileFindFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[  9%] Building CXX object CMakeFiles/storm.dir/src/SFileGetFileInfo.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileGetFileInfo.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileGetFileInfo.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 10%] Building CXX object CMakeFiles/storm.dir/src/SFileListFile.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileListFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileListFile.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 10%] Building CXX object CMakeFiles/storm.dir/src/SFileOpenArchive.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileOpenArchive.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileOpenArchive.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 11%] Building CXX object CMakeFiles/storm.dir/src/SFileOpenFileEx.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileOpenFileEx.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileOpenFileEx.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 11%] Building CXX object CMakeFiles/storm.dir/src/SFilePatchArchives.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFilePatchArchives.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFilePatchArchives.cpp:12:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 12%] Building CXX object CMakeFiles/storm.dir/src/SFileReadFile.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileReadFile.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileReadFile.cpp:13:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 12%] Building CXX object CMakeFiles/storm.dir/src/SFileVerify.cpp.o
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileVerify.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:93:14: warning: '__SYS_ZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_ZLIB
             ^
<command line>:4:9: note: previous definition is here
#define __SYS_ZLIB 1
        ^
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/SFileVerify.cpp:17:
In file included from /Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormLib.h:86:
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/StormPort.h:94:14: warning: '__SYS_BZLIB' macro
      redefined [-Wmacro-redefined]
  #define    __SYS_BZLIB
             ^
<command line>:3:9: note: previous definition is here
#define __SYS_BZLIB 1
        ^
2 warnings generated.
[ 12%] Building C object CMakeFiles/storm.dir/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c.o
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:58:12: error: 
      implicit declaration of function 'LibTomMalloc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  tmpbuf = XMALLOC(siglen);
           ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/../../headers/tomcrypt_custom.h:27:18: note: 
      expanded from macro 'XMALLOC'
#define XMALLOC  LibTomMalloc
                 ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:58:10: warning: 
      incompatible integer to pointer conversion assigning to 'unsigned char *' from 'int' [-Wint-conversion]
  tmpbuf = XMALLOC(siglen);
         ^ ~~~~~~~~~~~~~~~
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:66:6: error: 
      implicit declaration of function 'LibTomFree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     XFREE(tmpbuf);
     ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/../../headers/tomcrypt_custom.h:45:18: note: 
      expanded from macro 'XFREE'
#define XFREE    LibTomFree
                 ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:72:6: error: 
      implicit declaration of function 'LibTomFree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     XFREE(tmpbuf);
     ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/../../headers/tomcrypt_custom.h:45:18: note: 
      expanded from macro 'XFREE'
#define XFREE    LibTomFree
                 ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:83:3: error: 
      implicit declaration of function 'LibTomFree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  XFREE(tmpbuf);
  ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/../../headers/tomcrypt_custom.h:45:18: note: 
      expanded from macro 'XFREE'
#define XFREE    LibTomFree
                 ^
1 warning and 4 errors generated.
make[2]: *** [CMakeFiles/storm.dir/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c.o] Error 1
make[1]: *** [CMakeFiles/storm.dir/all] Error 2
make: *** [all] Error 2</pre></details>

Doesn't matter if you build with command line tools or with Xcode 12.

Using Clang 10 and 11 succeeds: what clang 12 treats as an error (implicit function declaration), these only show a warning. Example:

```
[ 12%] Building C object CMakeFiles/storm.dir/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c.o
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/rsa_verify_simple.c:58:12: warning: 
      implicit declaration of function 'LibTomMalloc' is invalid in C99 [-Wimplicit-function-declaration]
  tmpbuf = XMALLOC(siglen);
           ^
/Users/kambala/dev/diablo/build-D2-MXL-parser/_deps/stormlib-src/src/libtomcrypt/src/pk/rsa/../../headers/tomcrypt_custom.h:27:18: note: 
      expanded from macro 'XMALLOC'
#define XMALLOC  LibTomMalloc
```

**Comment by ladislav-zezula** [comment]
The `siglen` is declared as `unsigned long`. Is it greater than size_t, by any chance?

**Comment by kambala-decapitator** [comment]
the reason of error/warning is

> implicit declaration of function ... is invalid in C99

i.e. function is used without including its declaration first. Trivial example:

```c
int main() {
  f();
  return 0;
}

void f() {}
```

which is fixed by adding `void f();` before `main`.

**Comment by ladislav-zezula** [comment]
The main header (`tomcrypt.h`) includes `tomcrypt_custom.h`, where the CLIB_like functions are defined:
```
#define XMALLOC  LibTomMalloc
```
Then, the same main header (`tomcrypt.h`) includes `tomcrypt_cfg.h`, which contains the prototype:
```
LTC_EXPORT void * LTC_CALL XMALLOC(size_t n);
```
At the moment it seems fine to me, gotta look at it later

**Comment by kambala-decapitator** [comment]
those prototypes are disabled because `LTC_NO_PROTOTYPES` gets defined. Added a test code to verify that which triggers:
```c
#ifdef LTC_NO_PROTOTYPES
#error "LTC_NO_PROTOTYPES"
#endif
```

Will dig tomorrow what exactly causes that.

**Comment by ladislav-zezula** [comment]
Can you also try the branch https://github.com/ladislav-zezula/StormLib/tree/CLANG_12_MAC to see if that annoying `__SYS_BZLIB` goes away?

**Comment by kambala-decapitator** [comment]
yes, `__SYS_BZLIB` warning is gone. But there's the same about `__SYS_ZLIB` :)

Now I also get new error:
```
/Users/kambala/dev/diablo/StormLib/src/FileStream.cpp:37:8: error: unknown type name 'thread_local'
static thread_local DWORD nLastError = ERROR_SUCCESS;
```
(previously I was building the latest tag)

**Comment by ladislav-zezula** [comment]
Ok I fixed the `__SYS_ZLIB` as well.
Weird about that `thread_local` thing. It is supposed to be C++ 11.

**Comment by kambala-decapitator** [comment]
I found a proper fix for `thread_local`: require C++11 in `CMakeLists.txt`.
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by ladislav-zezula** [comment]
Commit 94e32487c14d75d63618a8b617dcfe4673f5c34c

**Comment by kambala-decapitator** [comment]
thanks, only those prototypes are left!

probably the easiest fix would be using a dedicated macro for each of the functions instead of generic `LTC_NO_PROTOTYPES`.

**Comment by ladislav-zezula** [comment]
> probably the easiest fix would be using a dedicated macro for each of the functions instead of generic LTC_NO_PROTOTYPES

I would prefer to find out why it doesn't work first

**Comment by kambala-decapitator** [comment]
> `memset` and `memcpy` are macros, that's why `LTC_NO_PROTOTYPES` gets defined.

not sure which other answer you need...

You can also check SDK headers, here for example:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_string.h

```c
```

**Comment by ladislav-zezula** [comment]
Oh, I see. Commit 026e9b23ad7fd105b2b171cce0ea4ea965a30dd9. Could you please check?

**Comment by kambala-decapitator** [comment]
perfect! no errors any more!

**Comment by ladislav-zezula** [comment]
Ok, merged. You can now switch to master.
