### ISSUE TITLE
Deadlock when verify/extract contents in some corrupted archives

### ISSUE THREAD

**Issue by TeraForce** [ladislav-zezula/StormLib#226]
the situation is very rare. i have 4 MPQ archives has this problem. (4 of 2.5million+)
[ProblemMPQArchive.zip](https://github.com/ladislav-zezula/StormLib/files/6756382/ProblemMPQArchive.zip)
this zip contains one of it (77A23A4A7F996A3DC63F90388D6EE403522B350C2C552EE85E8DE26119B15471D3C51B9620BDF461B0585399B7281B0DD97269330B2702F42B81A469F70BF29B.SC2Replay)
the deadlock will happened when use SFileExtractFile to extract the "replay.game.events", and also deadlock while using SFileVerifyFile to verify "replay.game.events"
MPQEditor can verify the file (no deadlock issue), but if try to extract, MPQEditor also deadlock. (same file "replay.game.events")

**Comment by ladislav-zezula** [comment]
Probably not a deadlock, but rather an endless loop. I'll take a look, but given it's holiday, don't expect it sooner than in two weeks.

**Comment by TeraForce** [comment]
all right, thanks

**Comment by ladislav-zezula** [comment]
There was an infinite loop in BZIP decompression on the file "replay.game.events". I fixed the decompression, so it doesn't loop indefinitely anymore. However, I can't say whether it unpacks valid data or not.
[mpqeditor_en.zip](https://github.com/ladislav-zezula/StormLib/files/6757225/mpqeditor_en.zip)

**Comment by TeraForce** [comment]
ah, thank you!
