### ISSUE TITLE
SFileRenameFile cause MPQArchive lost files

### ISSUE THREAD

**Issue by TeraForce** [ladislav-zezula/StormLib#227]
the issue happens when using stormlib to rename a file in a mpq archive. seems its a recent issue..
after renamed a file, open the mpq archive by mpqeditor, appears a lot of filexxxxxxx in it.

**Comment by ladislav-zezula** [comment]
> seems its a recent issue..

Do you know which build broke it?

Anyway, I am gonna need the MPQ and also what did you rename (both source and destination name).

**Comment by TeraForce** [comment]
i dont sure which build, i check the problem found it was the latest release(stormlib and mpqeditor). (after the last time decompress issue slove)
rename the 'replay.initData' to 'replay.initData2' of the test.SC2Replay can cause all file to File000000xx.xxx
seems, all the mpq archives i tested has same issue (first found was in a SC2Map, now i test for a replayfile). rename a file and most of files lost.

**Comment by ladislav-zezula** [comment]
Should be fixed in commit https://github.com/ladislav-zezula/StormLib/commit/48c3ae62151efd49592cf75359ecf23cdab9b69d.

**Comment by TeraForce** [comment]
i tested the rename, no problems, thanks)
