### ISSUE TITLE
What does dwPriority Argument stands for in Function SFileOpenArchive ?

### ISSUE THREAD

**Issue by jaydeepsaravaiya** [ladislav-zezula/StormLib#229]
`bool   WINAPI SFileOpenArchive(const TCHAR * szMpqName, DWORD dwPriority, DWORD dwFlags, HANDLE * phMpq);`

according to comments it stands for 

`//   dwPriority - When SFileOpenFileEx called, this contains the search priority for searched archives`

But after reading source code for it I found that dwPriority is not being assigned anywhere. Is it a relic of past or something ?

**Comment by ladislav-zezula** [comment]
Yeah, the prototype of the function corresponds to the very first prototype from Diablo I. Although I believe that the game itself orders MPQs by priority (example: a patch should have higher priority than the base MPQ), StormLib does not utilize the argument.
