### ISSUE TITLE
Fail to extract CHK from a Starcraft mpq (scx)

### ISSUE THREAD

**Issue by Chromowolf** [ladislav-zezula/StormLib#231]
I'm using the latest version MPQeditor (4.0.0.871).
The SCX is a protected MPQ, and can be opened by adding the default starcraft list file.
If I use 64bit version of MPQeditor:
The result of extracting staredit\scenario.chk is an empty file named "scenario#0409.chk"
If 32bit version is used:
Got a memory error (probably after calling `SFileGetFileSize` ) when trying to extract the chk.

You may download the file here:
[CannotExtractCHK.zip](https://github.com/ladislav-zezula/StormLib/files/7724864/CannotExtractCHK.zip)

Could u plz investigate this MPQ? Thx

**Comment by ladislav-zezula** [comment]
Hi,Yeah I found two tricks that prevent StormLib from treating the MPQ properly. I'll make an update.L.Dne 16. 12. 2021 6:51 napsal uživatel Chromowolf ***@***.***>:
I'm using the latest version MPQeditor (4.0.0.871).
The SCX is a protected MPQ, and can be opened by adding the default starcraft list file.
If I use 64bit version of MPQeditor:
The result of extracting staredit\scenario.chk is an empty file named "scenario#409.chk"
If 32bit version is used:
Got a memory error (probably after calling SFileGetFileSize ) when trying to extract the chk.
You may download the file here:
CannotExtractCHK.zip
Could u plz investigate this MPQ? Thx

**Comment by ladislav-zezula** [comment]
New build of MPQ Editor with the fix: http://www.zezula.net/download/mpqeditor_en_test.zip.
New version of StormLib is in separate branch: https://github.com/ladislav-zezula/StormLib/tree/LZ_CannotExtractCHK

**Comment by ladislav-zezula** [comment]
Merged to master. New build of MPQ Editor available on my website.

**Comment by Chromowolf** [comment]
> New build of MPQ Editor available on my website.

Thanks a lot! 
I could download the new build from the given link http://www.zezula.net/download/mpqeditor_en_test.zip, but I didn't find it in http://www.zezula.net/en/mpq/download.html

**Comment by ladislav-zezula** [comment]
Beta builds are not supposed to be in the download page.

**Comment by Chromowolf** [comment]
> Beta builds are not supposed to be in the download page.

I see. thx

**Comment by Chromowolf** [comment]
I'm sorry but I have to open this issue again. There are some follow-up questions about this MPQ.
I parsed the extracted CHK file. There are many `PlayWAV` actions that reference to strings such as "?23", "?0", "?1", etc. I'm pretty sure these are the file names of the audio files in this MPQ.
An example is:
![image](https://user-images.githubusercontent.com/37732663/146793519-10d27085-98d5-492e-afd7-4478cae2813f.png)
One of the `PlayWAV` actions references the above string, "?23", which is one of the audio files in the MPQ.

By parsing all the `PlayWAV` actions, I got the following guessed "listfile" of this MPQ:
```
staredit\scenario.chk
staredit\wav\bgm4.wav
?23
?8
?10
?21
?22
?3
?5
?9
?7
?4
?15
?17
?12
?20
?14
?2
?0
?1
```
I opened this MPQ using the above listfile, and got:
![image](https://user-images.githubusercontent.com/37732663/146794003-244c868e-c315-4620-ac9d-e05039e7c81e.png)

Nearly all the "?xx" files cannot be extracted.
Please help me to investigate this if possible. Thx!

**Comment by ladislav-zezula** [comment]
> All the files that has Encrypted attributes cannot be extracted.
Cannot be extracted because of what? Because of the "?" in the name?

**Comment by Chromowolf** [comment]
Maybe not because of the "?". Cuz all the file with the 'C' flag can be extracted. Other files with "CE" flags cannot. For example:
![Uploading image.png…]()
It says:
```
Fail to extract the file "?10
File or directory corrupted/broken and unreadable
```

**Comment by ladislav-zezula** [comment]
Please, send me the listfile to zezula at volny dot cz.

**Comment by Chromowolf** [comment]
Note that this list file is inferred from the `TRIG` and `STR ` sections of the CHK. It's the actual list file. I do not have the original project of this map.
[listfile_guessed.txt](https://github.com/ladislav-zezula/StormLib/files/7746657/listfile_guessed.txt)

**Comment by ladislav-zezula** [comment]
Thanks, I'll look at it. However, MPQ Editor would normally be able to extract the files even without the name, which I couldn't so maybe the files are just corrupt.

**Comment by Chromowolf** [comment]
I'm pretty sure the files are not currupted. cuz the sounds can be played during game

**Comment by ladislav-zezula** [comment]
I improved Warcraft III Name Scanner so that it also works with Starcraft. No GUI changes, but it does. I tried and the only file that it tried to open from the map was `staredit\scenario.chk`. However, it also exited the gameplay as soon as I started. So I need you to try this:

1. Download the beta build of MPQ Editor: http://www.zezula.net/download/mpqeditor_en_test.zip
2. Run 32-bit version and open the map
3. Select `Tools \ Warcraft III Name Scanner` and put the name of the Starcraft directory to the `Game Path`.
4. Click `Scan` in the `Live Game Scanner` group
5. Starcraft will run. You need to open the map in Starcraft and play it for a while.

Let me know if you found more file names.

**Comment by Chromowolf** [comment]
I'm stuck at step 5:
![image](https://user-images.githubusercontent.com/37732663/146882864-be63fc03-8bd1-44ba-a082-aedf89ae64fd.png)

When I click `scan`, it says:
![image](https://user-images.githubusercontent.com/37732663/146882936-459ef7fa-3cf7-4860-bee8-286816ca56ae.png)

**Comment by Chromowolf** [comment]
> However, it also exited the gameplay as soon as I started

I tried playing this map using the original starcraft, the game crashed within 1 minute. But this map can be played normally with SC:Remastered

**Comment by ladislav-zezula** [comment]
1) You need to enter game directory, not EXE
2) MPQ Editor will look for Starcraft.exe, not Brood.exe.

**Comment by ladislav-zezula** [comment]
Anyway - I identified the problem, thanks to the known file names. I fixed the buggy decompression and it now works:
http://www.zezula.net/download/mpqeditor_en_test.zip

**Comment by Chromowolf** [comment]
Thanks. Now all the files could be extracted.
Some more questions:
(1) Why are all the extracted file ended with "# 0409" ?
(2) Why are there 2 listfile, both with size 2147483647 ?

**Comment by ladislav-zezula** [comment]
> (1) Why are all the extracted file ended with "# 0409" ?

This solves the problem of MPQs ability to have multiple files with the same name and different locale

> (2) Why are there 2 listfile, both with size 2147483647 ?

This is result of the protector. Both are fake entries with wrong file size.

**Comment by ladislav-zezula** [comment]
Fixed in https://github.com/ladislav-zezula/StormLib/pull/233

**Comment by Chromowolf** [comment]
thx
