### ISSUE TITLE
Cannot Extract path from MPQ due to some MPQ protections

### ISSUE THREAD

**Issue by zzlk** [ladislav-zezula/StormLib#240]
Hi zezula,

I am trying to parse this mpq file: [https://bounding.net/map/170190](https://bounding.net/map/170190) and I am running into some issues. As you can see from the link, my website can parse the map but that is using an older algorithm that is simply "enumerate all files in mpq, try to parse each one as a starcraft map, pick the first one that parses correctly". This algorithm isn't great because it picks up fake CHK files inside the mpq, so I want to move away from it.

When I try to parse the above map, I get error 1004 from SFileReadFile for all locales that I try (I am making sure that the filename ends in .scx) when trying to read 'staredit\scenario.chk\'. I think this file is intentionally mangled to be difficult to read by protectors. It has many files inside the MPQ that are likely bogus. Almost all of them cannot be read by MPQEditor except for File00000029.xxx and the various .wav files. File00000029.xxx is the real CHK file for this map. I will also note that there is at least one other file with the same codewords as File00000029.xxx, it is File00000028.xxx. The only difference I can see from these two files in the mpq archive are that File00000029.xxx has the flag 'decryption key adjusted' where as the fake files do not have this.

What do you suggest I do here to read the correct CHK file instead of the fake one?

**Comment by ladislav-zezula** [comment]
I have troubles downloading the map from that webpage. Can you attach it to this thread?

**Comment by zzlk** [comment]
looks like i broke the downloads without noticing it :)

[map.zip](https://github.com/ladislav-zezula/StormLib/files/8009729/map.zip)

**Comment by ladislav-zezula** [comment]
Thanks. I'll look at it. Recently, [I did some improvements for protected Starcraft maps](https://github.com/ladislav-zezula/StormLib/pull/232), so I assume this will be similar problem

**Comment by ladislav-zezula** [comment]
https://github.com/ladislav-zezula/StormLib/pull/241

**Comment by zzlk** [comment]
Let me try it now.

**Comment by ladislav-zezula** [comment]
I also rebuilt MPQ Editor, it can now open the files properly.

BTW, if you check `[*] Deep File Verification` during opening the map, you will only see files that are actually valid.

**Comment by zzlk** [comment]
Thanks zezula. I can confirm it is now passing in my tests properly. I found another file with a different issue I think. I'll investigate  a bit and then maybe file another issue.

**Comment by zzlk** [comment]
it seems there is a bit more to this issue. When I apply these patches it fixes the issue in this map, but it also breaks another one.

I suspect that remaster has changed something to do with mpq reading. I also believe that both of these maps are valid and have worked with starcraft at some version. Both maps are protected.

| Map | protection |
| ----------- | ----------- |
| [ococ bound.scx](https://bounding.net/map/100638)      | ACMP 1.74 |
| [Sniper - Seed vA.scx](https://bounding.net/map/170190)   | SMC 2.9 |

## starcraft tests:

| Map | Starcraft 1.16.1 | Starcraft Remaster |
| ----------- | ----------- | -------------- |
| [ococ bound.scx](https://bounding.net/map/100638)      | Works correctly | Works correctly |
| [Sniper - Seed vA.scx](https://bounding.net/map/170190)   | Can be played, 99% sure it works correctly | Cannot be loaded |

I am not sure why [Sniper - Seed vA.scx](https://bounding.net/map/170190) cannot be loaded in starcraft remaster. It could be because it cannot  read the mpq, or it could be because it cannot parse scenario.chk. Additionally, while [Sniper - Seed vA.scx](https://bounding.net/map/170190) can be loaded in starcraft 1.16.1 and the game can be started,  it is not entirely clear if the map is playing correctly. But this definitely means that 1.16.1 can read the mpq at least mostly correctly. I suspect the map is either designed for 2 players or it requires an earlier version of starcraft to play correctly (likely because of outdated EUD triggers).

## My code test cases:
My code for reading these files is [here](https://github.com/zzlk/bwmap/blob/cea9c8f739993a515704af4a6cabc9926eec07a1/src/mpq.rs#L40). Simply, I open the archive, set locale (try multiple locales) then call SFileReadFile().

| Map | With 9eef856125 | Without 9eef856125 |
| ----------- | ----------- | -------------- |
| [ococ bound.scx](https://bounding.net/map/100638)      | SFileReadFile: 1004 | Success |
| [Sniper - Seed vA.scx](https://bounding.net/map/170190)   | Success | SFileReadFile: 1004 |

**Comment by zzlk** [comment]
I am calling SetFileLocale(0). The code below is how I am doing it. None of the attempts (try_map_with_locale) are returning successfully. Each attempt will call SetFileLocale(x) and then SFileOpenFIleEx and then SFileReadFile in that order. All locales fail with 1004, then the test fails with "couldn't find scenario.chk the legit way".

I will double check my code tomorrow morning, but I think i am setting the locale correctly. I am also not sure that [ococ bound.scx](https://bounding.net/map/100638) is using the same technique, at least I did not see a duplicate hash of "staredit\scenario.chk" in the hash table

```rust
        let locales = [
            0x404, 0x405, 0x407, 0x409, 0x40a, 0x40c, 0x410, 0x411, 0x412, 0x415, 0x416, 0x419,
            0x809, 0,
        ];

        // PROTECTION: Some maps put fake scenario.chk files at different locales. Try to find the real one by trying a lot of them.
        for locale in locales {
            if let Ok(x) = try_map_with_locale("staredit\\scenario.chk", locale) {
                println!("got candidate");
                // PROTECTION: Some maps put very small scenario.chk files in the mpq at different locales, ignore them.
                if verify_is_valid_chk(x.as_slice()) {
                    return Ok(x);
                }
            }
        }

        return Err(anyhow::anyhow!(
            "Couldn't find scenario.chk the legit way: {}, file: {}",
            stormlib_bindings::GetLastError(),
            filename
        ));
```

**Comment by ladislav-zezula** [comment]
We need to make sure that there is no issue in your code. Or in the layer between your code and StormLib code. MPQ Editor doesn't do any black magic - there's call to `SFileFindFirst/NextFile` -> `SFileSetLocale(found_locale)` -> `SFileOpenFileEx`.

> I am also not sure that [ococ bound.scx](https://bounding.net/map/100638) is using the same technique, at least I did not see a duplicate hash of "staredit\scenario.chk" in the hash table.

It doesn't use the same technique. You can examine the tables in MPQ Editor - open the MPQ and go Tools\MPQ Table Viewer (Ctrl+T).

**Comment by zzlk** [comment]
I realize that I have been linking the wrong map this whole time. Sorry for the confusion. The correct maps are

[OcOc Bound 2(p).scx](https://bounding.net/map/100652)
[Sniper - Seed vA.scx](https://bounding.net/map/170190)

We can now see that both do use the same technique, both have duplicate hash table entries for "staredit\scenario.chk"

[OcOc Bound 2(p).scx](https://bounding.net/map/100652)
![2022-02-09_17:51:25](https://user-images.githubusercontent.com/2418897/153322231-b22c5bd7-052c-4871-8d44-ba0b7a5dba41.png)

[Sniper - Seed vA.scx](https://bounding.net/map/170190)
![2022-02-09_17:56:36](https://user-images.githubusercontent.com/2418897/153322347-311a3ee3-6f7f-422b-9b45-3ac00bcf7a6f.png)

I tried creating a simple test case to remove some layers to make sure the issue I'm encountering is real. I added that test case below, and I made two of them, one for [OcOc Bound 2(p).scx](https://bounding.net/map/100652) and one for [Sniper - Seed vA.scx](https://bounding.net/map/170190).

I think I know the issue now. It seems as though SFileOpenFileEx is selecting the wrong file when told to open "staredit\scenario.chk" I noticed that I can call SFileOpenFileEx() with "File00000014.xxx" and I can extract this one correctly. I think this also explains why mpqeditor can extract the files from both archives correctly, since it is using FindNextFile so it will be trying to open the "FileXXXXXX" names.


using commit b79a6cc62e I get:

```
running 2 tests
test chk2::test::general::specific_test_0c0c_bound ... FAILED
test chk2::test::general::specific_test_sniper_seed ... ok

failures:

---- chk2::test::general::specific_test_0c0c_bound stdout ----
Error: SFileReadFile. GetLastError: 1004
```

if i do `git revert 9eef856125` and rebuild and rerun the same tests:

```
test chk2::test::general::specific_test_0c0c_bound ... ok
test chk2::test::general::specific_test_sniper_seed ... FAILED

failures:

---- chk2::test::general::specific_test_sniper_seed stdout ----
Error: SFileReadFile. GetLastError: 1004
```

using commit b79a6cc62e, but instructing the [OcOc Bound 2(p).scx](https://bounding.net/map/100652) test case to open "File00000014.xxx" instead of "staredit\scenario.chk"
```
running 2 tests
test chk2::test::general::specific_test_0c0c_bound ... ok
test chk2::test::general::specific_test_sniper_seed ... ok
```

### example test case using direct stormlib calls
```rust
#[test]
fn specific_test_0c0c_bound() -> Result<()> {
    unsafe {
        let filename = format!(
            "{}/test_vectors/OcOc Bound 2(p).scx",
            env!("CARGO_MANIFEST_DIR")
        );
        let cstr = std::ffi::CString::new(filename.as_str())?;

        let mut mpq_handle = 0 as stormlib_bindings::HANDLE;
        if stormlib_bindings::SFileOpenArchive(cstr.as_ptr(), 0, 0, &mut mpq_handle as *mut _)
            == false
        {
            return Err(anyhow::anyhow!(
                "SFileOpenArchive. GetLastError: {}, filename: {filename}",
                stormlib_bindings::GetLastError()
            ));
        }

        stormlib_bindings::SFileSetLocale(0);

        let mut chk_data: Vec<u8> = vec![0; 32 * 1024 * 1024];
        let mut archive_file_handle = 0 as stormlib_bindings::HANDLE;
        if stormlib_bindings::SFileOpenFileEx(
            mpq_handle,
            std::ffi::CString::new("staredit\\scenario.chk")?.as_ptr(),
            0,
            &mut archive_file_handle as *mut _,
        ) == false
        {
            return Err(anyhow::anyhow!(
                "SFileOpenFileEx. GetLastError: {}",
                stormlib_bindings::GetLastError()
            ));
        }

        let mut size: u32 = 0;
        if stormlib_bindings::SFileReadFile(
            archive_file_handle,
            chk_data.as_mut_ptr() as *mut _,
            chk_data.len() as u32,
            &mut size as *mut _,
            0 as *mut _,
        ) == false
        {
            let last_error = stormlib_bindings::GetLastError();
            if last_error != stormlib_bindings::ERROR_HANDLE_EOF || size == chk_data.len() as u32 {
                return Err(anyhow::anyhow!(
                    "SFileReadFile. GetLastError: {}",
                    last_error,
                ));
            }
        }

        chk_data.resize(size as usize, 0);
        anyhow::ensure!(chk_data.len() > 0);
    }

    anyhow::Ok(())
}
```

**Comment by ladislav-zezula** [comment]
I can confirm that both maps can be open with the original Starcraft 1.16.1. I'll look what's so special about them.

**Comment by ladislav-zezula** [comment]
If you are doing some sort of tests, do it with the [LZ_DefragmentHashTableBug](https://github.com/ladislav-zezula/StormLib/tree/LZ_DefragmentHashTableBug). I had to remove the hash table defragmentation, because it was not 100% and one of the protectors abused that fact.

It will slow down loading some protected MPQs terribly; especially those where the caller uses large listfile.

**Comment by zzlk** [comment]
I can confirm that with that branch at commit 6a107601c628ec I can run all my tests now and they all pass.
