### ISSUE TITLE
Error loading stormlib

### ISSUE THREAD

**Issue by jjcm** [ladislav-zezula/StormLib#244]
Hey there, getting an error loading stormlib:

```
lua: error loading module 'stormlib' from file '/usr/local/lib/lua/5.3/stormlib.so':
        /usr/local/lib/lua/5.3/stormlib.so: undefined symbol: __gxx_personality_v0
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        ./map/file/w3x.lua:7: in main chunk
        [C]: in function 'require'
        ./map/task/build/w3x/read.lua:4: in main chunk
        [C]: in function 'require'
        ./map/tasks.lua:73: in function 'map.tasks.run'
        (...tail calls...)
        [C]: in ?
        
```

For reference, here's the flags I built StormLib with: ` cmake -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=debug -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF -G "Unix Makefiles" CMakeLists.txt`

Any idea what's going on here?

**Comment by ladislav-zezula** [comment]
Well I am not particularly good in Linux, but it sounds like the dynamic library (stormlib.so) wants to import a symbol that is not present in CRT library (maybe)?

Perhaps some sort of new-linker vs. old-library issue?

**Comment by nvs** [comment]
I commented at nvs/lua-stormlib#12 on the same issue. Basically, I've been using `-DBUILD_SHARED_LIBS=on` and have not run into problems. Luarocks does not work with static libraries, and I'm wondering if that is the issue here.

**Comment by nvs** [comment]
I have closed the related issue on my repository as I feel it has been sufficiently addressed. See for yourself here: https://github.com/nvs/lua-stormlib/issues/12#issuecomment-1061232518.
