### ISSUE TITLE
dll name in DllMain.def is different with the actually file name when built with cmake on Windows 

### ISSUE THREAD

**Issue by toddwong** [ladislav-zezula/StormLib#246]
dll name in DllMain.def is "StormLib.dll", but when built with cmake on Windows, the actually dll file is named "storm.dll".
I'd suggest remove the dll name ( which is optional ) in DllMain.def.

**Comment by ladislav-zezula** [comment]
I removed it from the DEF file (https://github.com/ladislav-zezula/StormLib/commit/910b9ef2c1b0e563a20505aad59b9c44aaf8785d). However, the name should rather be `StormLib.dll` to avoid possible conflict with Blizzard's `storm.dll`.

**Comment by toddwong** [comment]
> However, the name should rather be `StormLib.dll` to avoid possible conflict with Blizzard's `storm.dll`.

So, maybe 
```
if(Win32)
set_target_properties(${LIBRARY_NAME} PROPERTIES OUTPUT_NAME "StormLib")
endif()
```
in CMakeLists.txt (after the `add_library` line) is more appropriate?

**Comment by ladislav-zezula** [comment]
That doesn't work. I guess that's one of the reasons why I hate CMake to the bone. If you can, please, make pull request.

**Comment by toddwong** [comment]
It should be `if(WIN32)` instead of  `if(Win32)`
