### ISSUE TITLE
No way to contact (MPQ name breaking)

### ISSUE THREAD

**Issue by heinermann** [ladislav-zezula/StormLib#248]
Hello, tried emailing the email provided on http://www.zezula.net/ and got

> Message not deliveredYour message couldn't be delivered to ####### because the remote server is misconfigured. See technical details below for more information.

> The response from the remote server was:550 relay not permitted

Anyway the contents of the email was as follows:

----

Hello, not sure if you're still doing namebreaking stuff but thought I'd contribute some missing names for the Brazilian and Japanese Starcraft versions.

```
#Starcraft PT-BR
files\stormd.dll
files\battled.snp
files\standardd.snp
files\scupdate.hlp
files\scupdate.cnt
campaign\terran\tutorial\staredit\wav\t0b06tad.wav
setupdat\gamemenu.bin

#SCJ Beta
setupdat\scuninJ.exe
setupdat\scuninJ.pif
files\StarCraftJ.exe
files\Sdlg.dll
files\font\fontbig.jfn
files\font\fontmed.jfn
files\font\fontsmall.jfn
setupdat\font\fontbig.jfn
setupdat\font\fontmed.jfn
setupdat\font\fontsmall.jfn
```

There are still 16 unknowns between them which I will be looking to run a name breaker for (as well as 13+ other unknowns in various Starcraft/Broodwar betas).

EDIT: After some name breaking & further guessing

```
#Starcraft PT-BR
files\stormd.dll
files\battled.snp
files\standardd.snp
files\scupdate.hlp
files\scupdate.cnt
campaign\terran\tutorial\staredit\wav\t0b06tad.wav
setupdat\gamemenu.bin
music\text.wav
music\vocals.wav
music\scintr22.wav

#SCJ Beta
setupdat\scuninJ.exe
setupdat\scuninJ.pif
files\StarCraftJ.exe
files\Sdlg.dll
files\font\fontbig.jfn
files\font\fontmed.jfn
files\font\fontsmall.jfn
setupdat\font\fontbig.jfn
setupdat\font\fontmed.jfn
setupdat\font\fontsmall.jfn
sound\protoss\fenixd\ufddth00.wav
sound\zerg\zergling\wavlist.txt
multimaps\oldladder\(4)Dire Straits.scm
multimaps\oldladder\(4)Lost Temple.scm
multimaps\oldladder\(4)Rivalry.scm

#Beta Stardat.mpq
glue\battle.net\generic\icons\but_radio.pcx
glue\battle.net\icons\dealie.pcx
sound\bullet\shockcnn.wav
sound\misc\tmasti00.wav
sound\terran\marine\tmapss00.sfk
tileset\badlands\yellow.pcx
triggers\greed.trg
unit\terran\tghcloak.grp
```

**Comment by ladislav-zezula** [comment]
Hello,

thanks for the contribuion. I updated the listfile ZIP on my webpages.
As for the e-mail, it will work again when my maintenance is done. In the meantime, you can e-mail me on zezula at volny dot cz.
