### ISSUE TITLE
Is this gap intentional?

### ISSUE THREAD

**Issue by drazisil** [ladislav-zezula/StormLib#254]
https://github.com/ladislav-zezula/StormLib/blob/460354d98bc266507befe517f9f246d3b952abc9/src/pklib/pklib.h#L99

Hello! It looks like there is a gap between 0x2203 and 0x2234. Is this intentional, or am I reading this incorrectly?

**Comment by ladislav-zezula** [comment]
0x2203 is relative offset within `out_buff`. It's there from the times when I reversed the pklib compression and wanted it to be equal to the original pklib code.
