### ISSUE TITLE
corrupt mpq archive cause crash

### ISSUE THREAD

**Issue by TeraForce** [ladislav-zezula/StormLib#256]
the attachment is the corrupt archive, can crash mpqeditor.
[MPQEditor_Crash_6EF9A265B698838B2B5747C7E1774DCFEC39BD98AE73ED11F96C04134D62BECA017FE9FE778E2578FDB7311B4127514505B901B6E452DCBF005571E72F8AB5C4.zip](https://github.com/ladislav-zezula/StormLib/files/8839782/MPQEditor_Crash_6EF9A265B698838B2B5747C7E1774DCFEC39BD98AE73ED11F96C04134D62BECA017FE9FE778E2578FDB7311B4127514505B901B6E452DCBF005571E72F8AB5C4.zip)
my program use stormlib to access mpq archive, but it crash when access it :(

**Comment by ladislav-zezula** [comment]
The MPQ seems to be corrupt. I'll fix StormLib to deny opening it.

**Comment by ladislav-zezula** [comment]
Commit https://github.com/ladislav-zezula/StormLib/commit/5e179844a864e130918f045165a75fa268629b4a adds more strict check to the HET table structure and refuses to load such MPQ.

**Comment by TeraForce** [comment]
thanks!
