### ISSUE TITLE
StormLib.dll x64 windows could not open archive

### ISSUE THREAD

**Issue by coolzoom** [ladislav-zezula/StormLib#260]
```
        [DllImport("StormLib.dll")]
        public static extern bool SFileOpenArchive(
            [MarshalAs(UnmanagedType.LPStr)] string szMpqName,
            uint dwPriority,
            [MarshalAs(UnmanagedType.U4)] OpenArchiveFlags dwFlags,
            out IntPtr phMpq);
```

SFileOpenArchive always returns false at x64 mode. x86 mode works great.
Is it a bug for the dll at x64 mode or is it because I missed something?

How to repeat:

1, Compile StormLib.dll x86, use SFileOpenArchive, works great.
2, Compile StormLib.dll x64, use SFileOpenArchive, returns false for any mpq file.

Tested compiler: Visual Studio 2019, Visual Studio 2022

**Comment by ladislav-zezula** [comment]
```
[MarshalAs(UnmanagedType.LPStr)] string szMpqName,
```
should be changed to:
```
[MarshalAs(UnmanagedType.LPWStr)] string szMpqName,
```
If you want a non-Unicode version, change that in the project settings of `StormLib_dll`

**Comment by coolzoom** [comment]
Thanks! Tested it is now working! will do some more tests and now i will close this issue, 
Cheers!
