### ISSUE TITLE
Mpq editor loading different files than warcraft game

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#261]
Similar issue to my last one, this time with a different map: https://file.io/UqzZZ37ZWsUO

If you look at files like items w3t, they were translated to english but when loading map in 1.28.5 wacraft it still shows all files in korean, so the way warcraft chooses which one is the latest version seems to differ from mpq editor

**Comment by ladislav-zezula** [comment]
Hi, could you please re-upload the map? I might have time to look at it.

**Comment by juvian** [comment]
I think it was this one: https://file.io/NcyGDGJNSZa7

**Comment by ladislav-zezula** [comment]
> so the way warcraft chooses which one is the latest version seems to differ from mpq editor

I checked the files and they have both locale & platform set to zero. So there should not be any ambiguity as for what the game picks and what MPQ Editor picks. Could you give me a concrete example of a file that is picked differently?

**Comment by juvian** [comment]
I don't remember much about this case. It is highly possible that its just that the node library I am using is years old so the stormlib dll it must use is not replacing the files correctly, I just tried doing it manually with mpq editor and seems to replace the files fine. Unfortunately I'm in the middle of some rewriting in my translation tool so can't test it for a while. Will close for now and reopen if I find an issue after retesting. Sorry to bother and thanks as usual

**Comment by ladislav-zezula** [comment]
Oookey. Well the truth is that there was an issue recently (like half-year ago) in StormLib that caused the game picking different files, based on file locale. It might have been the same case. Let me know if you find something.
