### ISSUE TITLE
New MPQ protection

### ISSUE THREAD

**Issue by GlitchLxrd** [ladislav-zezula/StormLib#266]
When i try to extract war3map.j , it says that the file is corrupted.

https://user-images.githubusercontent.com/65363348/196037829-0314faba-7796-4ed7-bb48-049a20d34411.mp4

https://drive.google.com/file/d/1myi5n16BGHN2WYp5dCqTp6GRiKqY63xi/view?usp=sharing

**Comment by ladislav-zezula** [comment]
I'll take a look, but I am a bit busy at the moment, so give me some time.

**Comment by ladislav-zezula** [comment]
Storm.dll is not able to open the file either. Are you sure that the game doesn't use `war3map.j` that is in the root?

**Comment by Luashine** [comment]
This is Frotty's work and he's working on a proprietary map protector (w3pro), that's now only available as SaaS. I will provide the files if the download links break. I took them from the map's discord server. I tested different map versions with MPQEditor:

- [0.21w](https://cdn.discordapp.com/attachments/821504130723348500/949699699428966471/Zombie_Defense_0.21w_w3pro.w3x):
    - scripts/war3map.j has a 26B dummy (filled with \x01)
    - the real script is in root
    - 30k files

- [0.22s](https://cdn.discordapp.com/attachments/821504130723348500/982593515584389140/Zombie_Defense_0.22s_w3pro.w3x):
    - 30269 tracked files (many of them are fake)
    - same as 0.21w
	
- [0.23i](https://cdn.discordapp.com/attachments/821504130723348500/1015427304551362660/Zombie_Defense_0.23i_w3p.w3x):
    - 30344 tracked files (many of them are fake)
    - has two script files:
    - 	1. in scripts/ which cannot be extracted and has a different file index
    - 	2. in root: the regular script

- 0.23p:
    - 30340 tracked files (many of them are fake)
    - 	1. in scripts/ which cannot be extracted
    - 	2. in root: the regular script

I tried to repack the latest in a new MPQ archive, it didn't work in game and I don't care to find out what was missing. Anyhow I think the war3map.j in root is the correct one and the only script file there is. JassHelper reports success on the repacked archive.

So the **only** issue there is, are the thousands of misleading files (like `scripts/war3map.j`). Looks like the protector only adds 30k files, but according to MPQEditor's "New MPQ" rules one could put up to 500k files (in base 2) in the MPQ listing, that'd probably cause real issues opening/browsing the archive.

One UX issue I have here: when I try to extract the "scripts/war3map.j" file, the error message cannot be clicked away and it blocks all other of MPQEditor's windows. You can only kill the application or press "SPACE" to close the message box with the error msg. I'll file this as a separate issue if necessary.

Other than the two general issues, this question should be resolved, works as expected (doesn't extract garbage).
