### ISSUE TITLE
problem mpq editor

### ISSUE THREAD

**Issue by jhoancito** [ladislav-zezula/StormLib#268]
Suddenly I get the error "this operation is not allowed in read-only or locked mode" it won't let me replace files it won't delete or create folder it won't rename it only lets me extract how do I fix it

https://ibb.co/rQX2Qpx

[url=https://ibb.co/rQX2Qpx][img]https://i.ibb.co/cyshy86/Captura.png[/img][/url]

**Comment by ladislav-zezula** [comment]
Could you define "Suddenly"?

From the image, I see that you opened a read-only MPQ archive. In that case, you cannot modify it.
