### ISSUE TITLE
Reading files by hash name

### ISSUE THREAD

**Issue by kirill-782** [ladislav-zezula/StormLib#281]
Is there a way to somehow get the hash of the names of the files contained in the archive?  And also get the contents of the file not by name, but by the hash of the name?

Most of the archives do not have a listfile, but I need to somehow compare the similarity of these archives.

**Comment by ladislav-zezula** [comment]
It may be possible that your request can be satisfied immediately. Let me explain.

StormLib supports opening file by index. To do that, pass `File########.ext` to `SFileOpenFileEx`, where `########` is the decimal value of a file index, aka index to the block table. The index is returned by `SFileFindFirstFile/SFileFindNextFile` in the `SFILE_FIND_DATA::dwBlockIndex`.

Would that work for you?

**Comment by kirill-782** [comment]
@ladislav-zezula Are HetHash and BetHash saved in MPQ? Or are they needed for calculations?

**Comment by ladislav-zezula** [comment]
Yep, they are. See [here](https://github.com/ladislav-zezula/StormLib/blob/f487b8a0e0df994fe5e19c4b2a77837cb95f79c3/src/StormLib.h#L766) and [here](https://github.com/ladislav-zezula/StormLib/blob/f487b8a0e0df994fe5e19c4b2a77837cb95f79c3/src/StormLib.h#L792).
