### ISSUE TITLE
MPQ Editor creates invalid archive entries using LZMA compression

### ISSUE THREAD

**Issue by MadProbe** [ladislav-zezula/StormLib#283]
Steps to reproduce:
1. Download MPQ Editor
2. Go to settings, create custom ruleset with LZMA compression and nothing else
3. Create an archive
4. Copy some files into it
5. Check added files (Verify files)

Additional info:
1. files compressed with ZLIB are ok
2. SC2 Editor cannot open archives with LZMA compression
3. OS: Windows 10 21H1
4. Archive is larger than normal one
5. Using StormLib directly also fails and creates a corrupted archive
6. Including MD5 and CRC32 with the archive has no effect

Screenshots:
Failed Archive:
![image](https://user-images.githubusercontent.com/49519179/216759286-4015645d-660a-4006-8ea0-8e85b962e293.png)
Ruleset:
![image](https://user-images.githubusercontent.com/49519179/216759363-af2c4753-4598-4aba-958e-9b78e6021d95.png)
Failed archive
[failed-archive.zip](https://github.com/ladislav-zezula/StormLib/files/10608298/failed-archive.zip)

**Comment by ladislav-zezula** [comment]
I'll check it out, but I'll probably close it as "won't fix" and disable the option in MPQ Editor.

**Comment by ladislav-zezula** [comment]
Fix: https://github.com/ladislav-zezula/StormLib/pull/285

Could you please download the latest MPQ editor and retry your use case?
Link: http://zezula.net/download/mpqeditor_en_madprobe.zip

**Comment by MadProbe** [comment]
> Fix: #285
> 
> Could you please download the latest MPQ editor and retry your use case? Link: http://zezula.net/download/mpqeditor_en_madprobe.zip

I've checked and I can confirm that fix is working properly
