### ISSUE TITLE
MPQEditor corrupts the .mpq/.scx on SC1 v1.16

### ISSUE THREAD

**Issue by Death-cord** [ladislav-zezula/StormLib#286]
When adding a staredit\scenario.chk file (which opens normally in Scmdraft) to a new MPQ using MPQEditor, then renaming it .scx, this .scx file will open in SCR & Scmdraft, but not SC1 v1.16, the map is normal SC1 v1.16 map without protection or new ramps, etc...

[MPQEditor.zip](https://github.com/ladislav-zezula/StormLib/files/11118296/MPQEditor.zip)

The game crashes when I select the map with this msg:
```
---------------------------
StarCraft
---------------------------
This application has encountered a critical error:
The file data is corrupt.

Program:    E:\starcraft\StarCraft.exe
File:    E:\starcraft\maps\BroodWar\template1.scx

staredit\scenario.chk

Press OK to terminate the application.
---------------------------
OK   
---------------------------
```

**Comment by ladislav-zezula** [comment]
The file `staredit\scenario.chk` in your map (template1 - .chk added (only open in SCR).scx) is compressed using ZLIB compression. If I check the same file in an original map, it is compressed by PKLIB. Can you check the game compatibility settings in MPQ Editor? It should be set to "Starcraft" or to a custom rule with PKLIB compression.

**Comment by captain-majid** [comment]
Yes setting the `Game - Compatibilty` to `Starcraft - Brood War` fixed the issue, thanks !

**Comment by Death-cord** [comment]
Yes, setting the `Game Compatibility` to `Starcraft - Brood War` fixed the issue, thanks !
