### ISSUE TITLE
Unable to view the assets of the Sc1 map.(Scx)

### ISSUE THREAD

**Issue by RemovePT** [ladislav-zezula/StormLib#287]
[cantview.zip](https://github.com/ladislav-zezula/StormLib/files/11307446/cantview.zip)
This map is protected through a tool called Freeze.
https://github.com/armoha/euddraft (Here is a file called freezeMpq)

When I open the map with mpq editor, I can't see the asset completely.
What should I do in this case?

![233920499-9c6b60dc-a66e-4cd2-87c4-9500193bb878](https://user-images.githubusercontent.com/131646360/235440676-c57e64bb-5cc3-4d48-a231-ccb4cab067de.png)

**Comment by ladislav-zezula** [comment]
You will need a listfile for that. I tried mine and I can at least see `staredit\scenario.chk`.

**Comment by RemovePT** [comment]
https://github.com/ladislav-zezula/StormLib/issues/231
I saw the article here and used the scanner, but the computer was frozen with a memory error.
My guess is because maps made with the latest EUD editor are not compatible with the 1.16.1 version.
Even with eudenabler.dll, only the EUD maps created before the remaster are compatible, and the maps created after the remaster are incompatible.
Please, I hope the scanner in the MPQ editor can be made compatible with the scremaster.
![12DSFDS](https://user-images.githubusercontent.com/131646360/235439608-760416c8-7337-4f6e-a4cd-a7b14f83c7a2.png)
Old EUD map
![12DSFDS2](https://user-images.githubusercontent.com/131646360/235439640-3d77063c-29a7-4ea0-959f-29fcec4d8e83.png)
EUD Map Created with Latest Editors

**Comment by ladislav-zezula** [comment]
I'll check the name scanner with the map you provided in the first post.

**Comment by ladislav-zezula** [comment]
I tried the map that you posted in the name scanner. It ended up normally. I need to say that name scanner is only designed to work with Warcraft III maps.

Which map failed for you?

Also, what is EUD?

**Comment by ladislav-zezula** [comment]
After some consideration, I decided not to implement Starcraft Name Scanner. It is not worth the time.
