### ISSUE TITLE
Pls Help MPQ EDITOR

### ISSUE THREAD

**Issue by Xaiphos** [ladislav-zezula/StormLib#289]
![Captura de pantalla 2023-05-26 115020](https://github.com/ladislav-zezula/StormLib/assets/81425626/96572d99-a8c4-484b-8748-5aa0773cf754)

please someone help me and tell me if the map is protected or I am doing something wrong and show me I am willing to donate $10

**Comment by ladislav-zezula** [comment]
Well, you tried to modify something on map that is read only.
