### ISSUE TITLE
字符乱码

### ISSUE THREAD

**Issue by thiyee** [ladislav-zezula/StormLib#299]
你有注意到这个项目在解析一个MPQ文件时 当这个MPQ文件中存在一个中文文件名的文件,会出现乱码的问题吗

**Comment by thiyee** [comment]
很抱歉 我不能向你提供一个具有中文文件名的MPQ文件 因为此邮件的接收方(也就是你发送邮件时使用的邮件服务器)不接受一个过大的MPQ文件附件

如果你有其他的联系方式 我将在后续将此MPQ文件发送给你
另外 我在我下载的项目中解决了我所遇到的乱码问题 但同样的邮件的接收方不接受附件 如果有需要请给我一个可接收邮件附件的邮箱地址





-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ladislav-zezula/StormLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 晚上8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ladislav-zezula/StormLib] 字符乱码 (Issue #299)





 
Please, send me a map. I guess this is because I don't support UTF-8 in the file names.

**Comment by thiyee** [comment]
这里有一个附件MPQ文件 里面的一些文件是带有中文文件名的文件 他在MAPEditor中解析出来是乱码的
即使我使用listfile中的正确的文件名去修复了解包后的文件名
但是在重新将打包后的文件夹打包成MPQ文件时 打包完成后游戏实际上也不能再正常加载这个文件了

但我在我下载的StormLib中修复了这个问题 但只是我调试时将我能看到的问题解决了&nbsp; 因为我不了解整个库的架构&nbsp; 也不了解这个MAP的具体文件结构及数据如何存储和加载的 所以我不确定我是否解决了全部的问题
以下是我在这个项目中对修复这个问题做出的部分修改
创建了MyString.cpp以及MyString.h两个文件
在DoMPQSearch_FileEntry以及DoListFileSearch中将UTF-8字符串转换成LOCALACP(本机字符编码)
这个我使用这个项目StormLib_vs08.sln来编译&nbsp;&nbsp;&nbsp; 用于unpack以及repack带有中文文件名的MPQ的文件
希望这些文件对你有所帮助
如果你在之后修复了这个问题 请使用此邮件回复我
如果可以&nbsp; 也将修复后的可以正常解析中文文件名的MPQEditor随附件一同发送给我


链接: https://pan.baidu.com/s/1sZ2wKIQwzoJ1xVd9UfpGGg?pwd=7w92 提取码: 7w92&nbsp;

-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ladislav-zezula/StormLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ladislav-zezula/StormLib] 字符乱码 (Issue #299)





 
Perhaps you could put the file to a download server and send me the link?

**Comment by ladislav-zezula** [comment]
Meh, baidu.com requires me to register. Can you post the file here to github?

**Comment by ladislav-zezula** [comment]
Thanks, I could download and unRAR the .s2ma file, Inside, I see the file `Nox Arcana-'The Call of Cthulhu'å…‹è‹é²çš„å‘¼å”¤ï¼ˆTrashÂ Killah remixï¼‰-Trash Killah.mp3` which is probably the one you are talking about.

Give me some time to fix the issue. It's vacation time, after all :-)

**Comment by thiyee** [comment]
是的&nbsp; 我已经在附件StromLib中解决了这一问题 但我不完全确定使用其他功能时这个修复任然有效
我在StormLib的test文件中修改了tamin入口的代码&nbsp; 用于测试我对DoMPQSearch_FileEntry以及DoListFileSearch中的修复是否有效
你可以使用StormLib_vs08.sln重新生成StormLib_test 然后将MPQ.s2ma文件拖拽到生成的StormLib_test.exe程序上 然后程序会在当前目录下输出这张地图的解包文件夹
或者将已经解包的文件夹拖拽到StormLib_test.exe上 重新生成其SCMap文件


不过 这个不是应该算是你的个人项目吗&nbsp; 为什么放假了不需要维护自己的项目


-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ladislav-zezula/StormLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 凌晨1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ladislav-zezula/StormLib] 字符乱码 (Issue #299)





 
Thanks, I could download and unRAR the .s2ma file, Inside, I see the file Nox Arcana-'The Call of Cthulhu'å…‹è‹�é²�çš„å‘¼å”¤ï¼ˆTrashÂ&nbsp;Killah remixï¼‰-Trash Killah.mp3 which is probably the one you are talking about.
 
Give me some time to fix the issue. It's vacation time, after all :-)

**Comment by ladislav-zezula** [comment]
StormLib is indeed my hobby project. "vacation time" applies to computers in general, not just in work :-)

I think the fix needs to be done in MPQ Editor, not in StormLib. After all, if we say that listfile is in UTF-8 encoding, then StormLib stays as it it.

Please, tell me: the map you shared with me - did you add the file with MPQ Editor or was it another application?

**Comment by ladislav-zezula** [comment]
I changed the way MPQ Editor treats the file names. Now they are all considered to be UTF-8 strings. Your MPQ can be open with it just fine. Please, try this beta build and let me know:
[mpqeditor_en_utf8.zip](https://github.com/ladislav-zezula/StormLib/files/11923258/mpqeditor_en_utf8.zip)

**Comment by thiyee** [comment]
-
***@***.***

非常感谢你的修复,但是这个Editor是否有汉化版本 像这样



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ladislav-zezula/StormLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月1日(星期六) 凌晨5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ladislav-zezula/StormLib] 字符乱码 (Issue #299)





 
I changed the way MPQ Editor treats the file names. Now they are all considered to be UTF-8 strings. Your MPQ can be open with it just fine. Please, try this beta build and let me know:
 mpqeditor_en_utf8.zip

**Comment by ladislav-zezula** [comment]
Here: [mpqeditor_cn_utf8.zip](https://github.com/ladislav-zezula/StormLib/files/11930115/mpqeditor_cn_utf8.zip)
