### ISSUE TITLE
Protection?

### ISSUE THREAD

**Issue by GlitchLxrd** [ladislav-zezula/StormLib#305]
Hello, mpq editor cant open this file: https://drive.google.com/file/d/1JJEtQ56zVaf4C0y-ShEVgrvRvID6Pq30/view

It's a mix file for this map : https://drive.google.com/file/d/1BGENz-8G2vqkkY1ruZ5X6PwFMvvbFxGK/view?usp=sharing

**Comment by ladislav-zezula** [comment]
I cannot access the document, because it's violating terms of use.

**Comment by GlitchLxrd** [comment]
https://drive.google.com/file/d/1T1n8o8IeUjQppms1GEnGGkIATmgd1RCr/view?usp=sharing

try this one

**Comment by GlitchLxrd** [comment]
https://www.dropbox.com/scl/fi/2snpydi9rxr75r1vk2w52/AniDreams-ResourcePack1.0.0.1.zip?rlkey=87tltjkk7qgeva1qqt3ij2421&dl=0

Try this one, google blocks the file.

**Comment by ladislav-zezula** [comment]
I fixed MPQ Editor so that it can now deprotect this archive.

**Comment by GlitchLxrd** [comment]
Nice, can you send me test version pls?

**Comment by ladislav-zezula** [comment]
Already on my website :-)

**Comment by GlitchLxrd** [comment]
I think you forgot to update the mpq editor ;c

**Comment by GlitchLxrd** [comment]
![image](https://github.com/ladislav-zezula/StormLib/assets/65363348/e6d4457c-6f61-497b-b89c-78005d2a5080)
![image](https://github.com/ladislav-zezula/StormLib/assets/65363348/e4e08c79-03e0-4832-bb7b-6bd9dbbee7c0)

**Comment by ladislav-zezula** [comment]
Damn, you are right, the version on the web is still the old one.
I am in the middle of some changes in the ASI/MIX deprotector, so please, give me some time, I'll send you the preview when ready.

**Comment by GlitchLxrd** [comment]
okey, ty

**Comment by ladislav-zezula** [comment]
Here you go. Don't forget that you can't open the file directly, but you must use the "MIX/ASI Deprotector" feature.
[mpqeditor_en_new_mix.zip](https://github.com/ladislav-zezula/StormLib/files/12777148/mpqeditor_en_new_mix.zip)

**Comment by GlitchLxrd** [comment]
Mix deprotector cant see files in redist/miles

**Comment by GlitchLxrd** [comment]
![image](https://github.com/ladislav-zezula/StormLib/assets/65363348/f9af5c69-e49b-4ce5-9512-7428788d2b7c)
i got this problem

**Comment by ladislav-zezula** [comment]
I'll extend the list in the second page of the wizard so it will also include the `redist\miles` subfolder.
However, it does not matter much. All files loaded by the game are taken into account.
I copied the `[AniDreams]ResourcePack1.0.0.1.mix` file into the `redist\miles` and it worked just fine (see the picture below).

The MIX deprotector is only supposed to work with the pre-CASC version of Warcraft III. Which version do you have?

![image](https://github.com/ladislav-zezula/StormLib/assets/3244359/172d95ef-169a-495b-a59f-575e5fc98c96)

**Comment by ladislav-zezula** [comment]
BTW, it seems that it also works with files `*.m3d` and `*.flt`, I'll add that too

**Comment by GlitchLxrd** [comment]
1.26 RU , but idk why it's not working on me and others

**Comment by GlitchLxrd** [comment]
https://github.com/ladislav-zezula/StormLib/assets/65363348/6104e623-a463-4040-9795-3db26934703c

**Comment by ladislav-zezula** [comment]
Thanks for the video, TBH I was gonna ask you about one :-)

From that video, I saw that it fails to find the MIX files quite fast. That may mean that the process failed at the very beginning.

Let's try to debug the problem.

1. Get the new build: [mpqeditor_en_new_mix.zip](https://github.com/ladislav-zezula/StormLib/files/12778735/mpqeditor_en_new_mix.zip)
2. Run the MIX deprotector again
3. On the bottom of the final page, there's an error. There is also reason for that error (error code converted to windows-native error code text). Please, tell me what it says. My best guess is "Access Denied".

Then we can turn on some logging and see more.

**Comment by GlitchLxrd** [comment]
I've downloaded a new build , it's also not working for me. But now MPQ Editor can see redist/miles .  
Error says : No MIX/ASI files found.

**Comment by ladislav-zezula** [comment]
Would it be possible to ZIP your copy of Warcraft III and put it somewhere for download?

- Remove all logs
- Remove all big files that are not necessary to run the game
- Maybe keep the "ReplaySpeedUnlocker.mix", may be part of the problem

**Comment by GlitchLxrd** [comment]
https://drive.google.com/file/d/1zb5fs1jTrREt0ot7O1KwQPWauBLMOIh9/view?usp=sharing

Tested on this war3. Deleted [AniDreams]ResourcePack1.0.0.1.mix , add it to test

**Comment by ladislav-zezula** [comment]
Thanks. Please, leave the file there for some time, I am on a slow internet in these days.

**Comment by ladislav-zezula** [comment]
Google Drive says that the document violates the Terms of Use.

**Comment by ladislav-zezula** [comment]
Here's a new build of MPQ Editor with logging. Just run the wizard normally.
There will be two log files in C: (hard coded path, make sure you can write there):

- `mix-dumper-mpq-editor.log` - log from MPQEditor
- `mix-dumper-war3.log` - log from Warcraft III

Please, send them to me.

[mpqeditor_en_new_mix.zip](https://github.com/ladislav-zezula/StormLib/files/12783536/mpqeditor_en_new_mix.zip)

**Comment by GlitchLxrd** [comment]
Nov everything is working fine ;D. Thank you for your work!

**Comment by GlitchLxrd** [comment]
https://drive.google.com/file/d/1JF67zAZSYcD-h2oD-BJrh-vAnrV3YHPX/view?usp=sharing

Uploaded my war3 again, deleted AniDreamsModules

**Comment by ladislav-zezula** [comment]
> Now everything is working fine ;D. Thank you for your work!
> btw couldn't find any logs, maybe because dumper was succeed , idk

Well I didn't change anything, so thats really weird. And the absence of logs means that we didn't even fix anything.

> Uploaded my war3 again, deleted AniDreamsModules

Again, violation of terms of use. Maybe pack it with 7zip, with a password and rename to something neutral, like `file.bin`

**Comment by GlitchLxrd** [comment]
Yes, i am running the new version. I've deleted the old version. https://drive.google.com/file/d/1d7HvhyN27v9vaddGnmQ1DfS2chBoMLMN/view?usp=sharing
Packed to mpq ;D

**Comment by ladislav-zezula** [comment]
Thanks. This time, I downloaded and unpacked the file just fine. I'll keep it for later testing.
