### ISSUE TITLE
MPQ Editor: Bitmap Viewer crashes with fresh MPQ

### ISSUE THREAD

**Issue by Luashine** [ladislav-zezula/StormLib#310]
MPQEditor 4.0.0.882, 4.0.0.908 Unicode
StormLib 9.24

1. Create Empty MPQ
2. Game profile: Warcraft III Maps
3. max number files: 4000
4. Go to Tools, open MPQ Bitmap
5. It will create a very long list
6. Scroll Down and crash

However when you save and reopen the same empty MPQ archive, it will show one blue (present) block only without crashing.

**Comment by ladislav-zezula** [comment]
I'll see the crash, will fix MPQEditor a.s.a.p. Thanks for the heads up.

**Comment by ladislav-zezula** [comment]
MPQ Editor fixed & available on my website.
