### ISSUE TITLE
Access Violation - SFileGetFileInfo on Protected MPQ

### ISSUE THREAD

**Issue by speige** [ladislav-zezula/StormLib#311]
Protected map Lusin2Rpg1.28.w3x
https://drive.google.com/file/d/1y7YuiNx5a6YTxg0PJjeGe1Hzx2G5uoea/view?usp=drive_link

Calling SFileGetFileInfo with SFileInfoNameHash1 or SFileInfoNameHash2 with psuedo filename File00002875.blp

Exception thrown at 0x00000001400DF418 in StormLib_test.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Access violation is pretty serious, since it typically crashes the entire application (even a try/catch fails to fix it)

Haven't tested all the SFileInfo enum options, but I think several others cause same access violation.

Example archive has fake files, which I can easily ignore by doing SFileExtractFile & checking disk file size. However, File00002875.blp is a real file which can be succesfully extracted. I'd expect SFileInfoNameHash1 to succeed considering it's a real file, but it still fails.

I made an attempt at a PR that I believe fixes it, but I'm not an expert, so correct me if I'm wrong.
https://github.com/ladislav-zezula/StormLib/pull/312

Thank you so much for this tool. You're amazing!

**Comment by ladislav-zezula** [comment]
Hello, thanks for the bug find. I could not merge your PR, because it did not solve the problem completely. I did it on my own PR and also added regression test for this particular case.

PR: https://github.com/ladislav-zezula/StormLib/pull/313.
I also updated MPQEditor on my website.

I wish you a merry Christmas and a happy new year :-)

**Comment by speige** [comment]
Thank you! No worries, I figured you could code it better, just hoping the PR saved you debugging time.

**Comment by ladislav-zezula** [comment]
> I figured you could code it better, just hoping the PR saved you debugging time.

Sure it did. Moreover, the map you provided is now added to my "pervert map collections", so it should never happen again.

Take care 👍
