### ISSUE TITLE
DetectFileKey incorrect

### ISSUE THREAD

**Issue by speige** [ladislav-zezula/StormLib#315]
https://drive.google.com/file/d/13sCYkMP7_HswnC_CzuZ1NAJzBKvyIeVu/view?usp=sharing
WC3 Map ORD11.089.w3x

PseudoFileName: File00000343.xxx
RealFileName: AZTextures\\AZ_TexturesA4422.blp
correct dwFileKey: 3218152129
incorrect dwFileKey: 237525816

Bug is in DetectFileKeyBySectorSize. Not sure if other DetectFileKey methods have same bug.
Since we need real file name to calculate the real encryption key, the Detect methods try to crack it. In this example, there are 2 possible keys that will crack it, both can theoretically be found by DetectFileKeyBySectorSize, but detection quits after 1st possible match is found, which for this file is wrong & causes garbage bytes. If 1st match is skipped, DetectFileKeyBySectorSize does find correct key in later iteration of loop.

Obviously not easy to pick the *best* key when multiple possible valid keys are found.
Maybe make detection APIs public so end-user can enumerate both versions of the file?

Obviously with listfile problem is solved, but nice to be able to inspect a file that doesn't have a known name.

**Comment by ladislav-zezula** [comment]
> Maybe make detection APIs public so end-user can enumerate both versions of the file?

Not worth the trouble. Guessing the proper encryption key is not guaranteed if the file is not opened by its proper name.

The correct way to fix this would be to detect the file name (Live Scanner in MPQEditor) and put that name in the listfile.

**Comment by speige** [comment]
Agreed. I'm doing that already & it seems to resolve the issue.

Theoretically the Live Scanner could fail to find a dependent file if the parent file fails to decrypt. (Say an MDX referencing a BLP) But, I think that would be extremely rare, since most files are cross-referenced from multiple places.

**Comment by ladislav-zezula** [comment]
> I guess "Live Game Scanner" should 100% always succeed though, even if "Map File Scanner" fails.

Yes, I was talking about Live Scanner in my previous post. That one should always succeed, except for cases where the file is not used - imagine a scenario where something appears only under very specific situation on the map.
