### ISSUE TITLE
SFileOpenPatchArchive() does not pass dwFlags to SFileOpenArchive()

### ISSUE THREAD

**Issue by vdm-dev** [ladislav-zezula/StormLib#317]
For this reason, you cannot use the MPQ_OPEN_NO_LISTFILE flag (or any others) for patches.

**Comment by ladislav-zezula** [comment]
Hi, thanks for the report. Could you please give an example why is this a problem?

**Comment by vdm-dev** [comment]
Of course! This problem is closely related to #318.
I'm working on a project where I need to load all MPQ files from WoW: WotLK in the same order as they are used in the original client. Here is a piece of code:
```
    const char* baseFiles[] = {
        "common.MPQ",
        "common-2.MPQ",
        "expansion.MPQ",
        "lichking.MPQ"
    };
...
    for (size_t i = 0; i < sizeof(baseFiles) / sizeof(baseFiles[0]); ++i) {
        SStrCopy(path, "Data/", sizeof(path));
        SStrPack(path, baseFiles[i], sizeof(path));
        OsFileToNativeSlashes(path);

        if (i == 0) {
            // This one works fast because MPQ_OPEN_NO_LISTFILE flag is set
            if (!SFileOpenArchive(path, 0, MPQ_OPEN_NO_LISTFILE, &g_mpqHandle))
                return;
        // But this line below works slow because MPQ_OPEN_NO_LISTFILE flag is ignored and the files (common-2.MPQ, expansion.MPQ, lichking.MPQ) are huge.
        } else if (!SFileOpenPatchArchive(g_mpqHandle, path, nullptr, MPQ_OPEN_NO_LISTFILE)) {
            return;
        }
    }
```

**Comment by ladislav-zezula** [comment]
Ok. I will add the propagation of `MPQ_OPEN_NO_LISTFILE` to `SFileOpenPatchArchive`.

**Comment by vdm-dev** [comment]
> Ok. I will add the propagation of `MPQ_OPEN_NO_LISTFILE` to `SFileOpenPatchArchive`.

Cool, thank you!

**Comment by ladislav-zezula** [comment]
Try the branch https://github.com/ladislav-zezula/StormLib/tree/LZ_SFileOpenPatchArchive_Fix. Let me know if this works for you.

**Comment by vdm-dev** [comment]
It works like a charm. Thank you.

**Comment by ladislav-zezula** [comment]
Merged to master.
