### ISSUE TITLE
SListFileCreateNodeForAllLocales() is very slow

### ISSUE THREAD

**Issue by vdm-dev** [ladislav-zezula/StormLib#318]
The `SListFileCreateNodeForAllLocales()` function from the `SFileListFile.cpp` file is very slow.
The slowdown is due to a change in the algorithm for filling the hash table with filenames.
Link to changes:
https://github.com/ladislav-zezula/StormLib/commit/503ab19d3d4253fb013752572c19c314d19de792#diff-c78bc74cc3b191a93e9b557d857446fb9bcbe369cc19b78ac404b74564e83d9d

The old algorithm (commented for now) is fast because it does not completely search the entire hash table for each file added.
Instead, the old algorithm uses hashes to match the hashed and the real file name.

**Comment by ladislav-zezula** [comment]
While I agree with you, the change introduces in the commit has a good reason, which is MPQ protectors that try very hard to disrupt opening MPQs. One of their methods is to create MPQs with large hash tables (often larger than the MPQ itself) which are filled with random garbage. There is no terminator and the hash search algorithm is forced to search the entire hash table.

**Comment by vdm-dev** [comment]
Yeah, now I see what's going on.
I can suggest a workaround: introduce the `MPQ_LISTFILE_FAST_LOAD` flag to use the old hash table-based algorithm.
```
if(ha->dwFlags & MPQ_LISTFILE_FAST_LOAD)
{
        pFirstHash = pHash = GetFirstHashEntry(ha, szFileName);
        while(pHash != NULL)
        {
            // Allocate file name for the file entry
            AllocateFileName(ha, ha->pFileTable + MPQ_BLOCK_INDEX(pHash), szFileName);

            // Now find the next language version of the file
            pHash = GetNextHashEntry(ha, pFirstHash, pHash);
        }
}
else
{
        for(pHash = ha->pHashTable; pHash < pHashEnd; pHash++)
        {
            if(pHash->dwName1 == dwName1 && pHash->dwName2 == dwName2 && MPQ_BLOCK_INDEX(pHash) < ha->dwFileTableSize)
            {
                // Allocate file name for the file entry
                AllocateFileName(ha, ha->pFileTable + MPQ_BLOCK_INDEX(pHash), szFileName);
            }
        }
}
```

**Comment by ladislav-zezula** [comment]
I will not do that. Normal archives are opened quite fast. And those that are malformed, people can always extract all files and make new map which is not malformed.
