### ISSUE TITLE
building under Windows with MingGW

### ISSUE THREAD

**Issue by DeadWarlock** [ladislav-zezula/StormLib#32]
I try build library with this command `mingw32-make -f makefile.w32` and have several errors from linker ((.
Because you forgot add `bzip2` library for building in makefile. And I stop trying. Please check `makefile.w32`. And  `OBJS_TEST = test/test.o` not exist you rename that file. Thank you.

**Comment by ladislav-zezula** [comment]
Fixed in commit 13c889a84d51692ea3f42e19f04c394bd2caf35d.
