### ISSUE TITLE
Can't run game with Live Scan

### ISSUE THREAD

**Issue by null15** [ladislav-zezula/StormLib#321]
![image](https://github.com/ladislav-zezula/StormLib/assets/30800470/bc81ca82-4d52-4bf3-a75a-5dd3b4b83556)

![image](https://github.com/ladislav-zezula/StormLib/assets/30800470/009fdab2-4d89-4bf9-b205-f3f8e7c853d5)

Map: [Download, GDrive](https://drive.usercontent.google.com/download?id=1XI7-dpHegc04ycQOiZioD4XP55zg_EaX&export=download&authuser=0)

To play/host this map (the access denied is not related, I think at least, but in case you want to play/test the map) you need 1.27 wc3

WC3: [Download, GDrive](https://drive.google.com/file/d/1lgTKVcJ1tUpwCXK1Hpb7aaIsBDEb7Nox/view)
Run the Launch.bat or launch-windowed.bat file

**Comment by ladislav-zezula** [comment]
Hi, thanks for the report.
It will probably tied to your specific setup, so it needs to be diagnosed on your PC.
Could you run Process Monitor on MPQEditor.exe and see what exactly was denied?

**Comment by null15** [comment]
> Hi, thanks for the report. It will probably tied to your specific setup, so it needs to be diagnosed on your PC. Could you run Process Monitor on MPQEditor.exe and see what exactly was denied?

Sure! I'm not familiar with the tool, so I will go test it. If you want to communicate through Discord I can do that too, but give me a moment, I will install Process Monitor and check

**Comment by ladislav-zezula** [comment]
Hello, we can go discord. Can you e-mail me your discord name?

**Comment by null15** [comment]
> Hello, we can go discord. Can you e-mail me your discord name?

i emailed you

**Comment by ladislav-zezula** [comment]
Cant see it in any of my mailboxes. Try to add me as ladikthegrey.

**Comment by null15** [comment]
> Cant see it in any of my mailboxes. Try to add me as ladikthegrey.

Weird, I added you again

**Comment by null15** [comment]
Fixed
