### ISSUE TITLE
Incorrect file size and/or SFileExtractFile behaviour

### ISSUE THREAD

**Issue by joankaradimov** [ladislav-zezula/StormLib#323]
I'm trying to extract `StarCraft.exe` from the [official StarCraft 1.16.1 patch](https://www.moddb.com/games/starcraft/downloads/starcraft-brood-war-v1161-patch). I have something along these lines:
```c++
const char* patch_path = "some-path/BW-1161.exe";
SFileOpenArchive(patch_path, 0, 0, &patch_archive);
SFileExtractFile(patch_archive, "starcraft.exe", "extracted/StarCraft.exe", 0);
SFileCloseArchive(patch_archive);
```

After the file is extracted it ends up as a corrupted executable. There are 24 extra bytes of data before the `MZ` header magic. The total size of the extracted file is 1,220,632 bytes. Interestingly the MPQ Editor manages to extract a valid exe file (with size 1,220,608 bytes), but reports the size as 1,220,632 bytes in the UI.

I'm using:
- StormLib v9.25 (but the latest master behaves the same way).
- MPQ Editor 4.0.0.915 [StormLib v9.25] (but 3.6.085 [StormLib v9.22] behaves the same way).

**Comment by Chaosvex** [comment]
Had a quick look and I think the extraction is correct and the file simply has additional data at the beginning, possible for patching purposes. The 32-bit LE value at offset 12 contains the actual size of the file in bytes (00A01200 = 1220608). Third byte looks like it's an offset to the start of the data (or a coincidence), so it could be the size of an additional header in BE.

I'm guessing MPQEditor knows what it is and makes the necessary adjustments where as StormLib just extracts as-is.

**Comment by ladislav-zezula** [comment]
> I'm guessing MPQEditor knows what it is and makes the necessary adjustments whereas StormLib, being lower level, just extracts as-is.

Yep:
![image](https://github.com/ladislav-zezula/StormLib/assets/3244359/eb8ea1f7-1d69-4d1e-a401-a2724dd22473)

**Comment by joankaradimov** [comment]
That's a surprise. Thanks!

I'm guessing that is unrelated to [patchfiles](http://www.zezula.net/en/mpq/patchfiles.html)? WoW Cataclysm is after StarCraft 1.16.1, I believe.

Is there anything fancy about this detection? Or does it just strip the first 18 bytes? I am now noticing that `battle.snp` and `standard.snp` that the MPQ Editor extracts from the patch are not valid DLL/PE files and StarCraft does not load them.

**Comment by ladislav-zezula** [comment]
> I'm guessing that is unrelated to [patchfiles](http://www.zezula.net/en/mpq/patchfiles.html)? WoW Cataclysm is after StarCraft 1.16.1, I believe.

It is unrelated. Patch files in Starcraft are much older.

> Is there anything fancy about this detection?

Not really:
![image](https://github.com/ladislav-zezula/StormLib/assets/3244359/15149c34-4757-45b8-8f4b-cbb7d2e4d9c4)
