### ISSUE TITLE
Why can't the file region be set?

### ISSUE THREAD

**Issue by wroldLove** [ladislav-zezula/StormLib#324]
if(StormLibrary.SFileOpenFileEx(stormLibrary.archiveHandle, SelectedItems, 0, out IntPtr hFile))
  {
       StormLibrary.SFileSetFileLocale(hFile, 1033);
 }

Always return false,Please help me

**Comment by ladislav-zezula** [comment]
Most probably, you opened a Warcraft III map that is corrupt and StormLib opened the map in read-only mode.

**Comment by wroldLove** [comment]
> 最有可能的是，您打开了一张损坏的魔兽争霸III地图，而StormLib以只读模式打开了该地图。

I redownloaded the map and got the same result. I also tested the map that came with Warcraft III, but it kept returning false.

**Comment by ladislav-zezula** [comment]
> I redownloaded the map and got the same result.

Sorry, I should have been more specific. By `corrupt`, I meant a map that is malformed, i.e. protected by some MPQ protectors. Such maps are opened in read-only mode by StormLib.

I tried on a Warcraft III map called `(4)Duskwood.w3m` and it works:
```
    HANDLE hFile = NULL;
    HANDLE hMpq = NULL;

    if(SFileOpenArchive(_T("(4)Duskwood.w3m"), 0, 0, &hMpq))
    {
        if(SFileOpenFileEx(hMpq, "war3map.j", 0, &hFile))
        {
            SFileSetFileLocale(hFile, 1033);   // Returns 'true'
            SFileCloseFile(hFile);
        }
        SFileCloseArchive(hMpq);
    }
```

**Comment by wroldLove** [comment]
> > 我重新下载了地图，得到了相同的结果。
> 
> 对不起，我应该更具体。我指的是 `corrupt` 格式不正确的地图，即受某些 MPQ 保护器保护。此类地图由 StormLib 以只读模式打开。
> 
> 我试过一张名为 `(4)Duskwood.w3m` 魔兽争霸III的地图，它有效：
> 
> ```
>     HANDLE hFile = NULL;
>     HANDLE hMpq = NULL;
> 
>     if(SFileOpenArchive(_T("(4)Duskwood.w3m"), 0, 0, &hMpq))
>     {
>         if(SFileOpenFileEx(hMpq, "war3map.j", 0, &hFile))
>         {
>             SFileSetFileLocale(hFile, 1033);   // Returns 'true'
>             SFileCloseFile(hFile);
>         }
>         SFileCloseArchive(hMpq);
>     }
> ```

That's strange, why do I keep getting false as the return value? I checked the code and it should return true, only SFileSetFileLocale keeps returning false.
`           if (StormLibrary.SFileOpenFileEx(stormLibrary.archiveHandle, "war3map.j", 0, out IntPtr hFile))
           {
               Console.WriteLine(StormLibrary.SFileSetFileLocale(hFile, 1033));
               StormLibrary.SFileCloseFile(hFile);
           }`

**Comment by ladislav-zezula** [comment]
Please, try with the freshly rebuilt StormLib.dll. If it doesn't work, send me an example of the project in C#.
[stormlib_dll.zip](https://github.com/ladislav-zezula/StormLib/files/14816872/stormlib_dll.zip)

**Comment by wroldLove** [comment]
> 请尝试使用新重建的StormLib.dll。如果它不起作用，请向我发送 C# 中的项目示例。 [stormlib_dll.zip](https://github.com/ladislav-zezula/StormLib/files/14816872/stormlib_dll.zip)
I use this newly rebuilt StormLib.dll to open the MPQ file handle always returns 0, it is the same when opening any file, while using the previous dll successfully gets the file handle.

**Comment by wroldLove** [comment]
> [stormlib_dll.zip](https://github.com/ladislav-zezula/StormLib/files/14816872/stormlib_dll.zip)

Sorry, I can now open an MPQ file normally and get the handle, and the file region has also been set successfully, thank you.

**Comment by wroldLove** [comment]
I have another question to consult with you. In an MPQ file, there are files that seem to have been encrypted. However, when I use your MPQ editor, I can correctly read the file names. How should I proceed in this case? Thank you.
“chmijing浣?mdx、chbjtz浣?mdx、pandarenserpentgod_green3浣?mdx”

**Comment by ladislav-zezula** [comment]
You need to provide listfile with file names that are UTF-8 encoded.

**Comment by wroldLove** [comment]
> You need to provide listfile with file names that are UTF-8 encoded.

It is not UTF-8 encoding. When opened with MPQ editor, "浣?" becomes "体", for example: chmijing浣?mdx > chmijing体.mdx

**Comment by ladislav-zezula** [comment]
Well, MPQ Editor opens the archive and then calls SFileAddListFile. Believe it or not.
