### ISSUE TITLE
MPQ Editor can't open a map

### ISSUE THREAD

**Issue by gabriel193** [ladislav-zezula/StormLib#325]
Crash after trying to open, MPQ Editor Version: 4.0.0.905 (Unicode Build)
Map download: https://pixeldrain.com/u/XsWjk1QC

**Comment by ladislav-zezula** [comment]
That is an interesting file. I'll fix that.

**Comment by gabriel193** [comment]
I managed to fix it by removing some stuff with HxD, here's my edited file
Edited map: https://drive.google.com/file/d/1JDXLtNBSkfsA3bF87s5mN7UmkIs9bmv2/view?usp=sharing

**Comment by ladislav-zezula** [comment]
You can also strip the fake headers by removing the first 0x400 bytes from the MPQ. The real MPQ header starts at offset 0x400.
But there is more. Many compressed files in the MPQ have smaller compressed size than declared in the block table, so they are padded by random bytes at the end. I§ll fix that one as well.

**Comment by gabriel193** [comment]
Can you share the latest MPQ Editor here? For some reason your website does not work anymore on Brazil.

**Comment by ladislav-zezula** [comment]
MPQ Editor v 4.0.0.917 was uploaded to my website. You can also download it from here: [mpqeditor_en.zip](https://github.com/ladislav-zezula/StormLib/files/15000744/mpqeditor_en.zip)

**Comment by gabriel193** [comment]
Thanks, it works like a charm. Do you by any means have a discord?

**Comment by ladislav-zezula** [comment]
> Thanks, it works like a charm. Do you by any means have a discord?

Write me an e-mail.
