### ISSUE TITLE
Where did ApplyMpqPatch_BSD0 go?

### ISSUE THREAD

**Issue by grepwood** [ladislav-zezula/StormLib#348]
I'm trying to re-implement the steps for patching Warcraft 3 RoC from 1.0 to 1.26a with open source tools and freely available patch files. Using official bspatch obviously doesn't work. But I've read on http://www.zezula.net/en/mpq/patchfiles.html that there's a function in StormLib that can do this. But it's not coming up in the search. Where did it go?

**Comment by ladislav-zezula** [comment]
https://github.com/ladislav-zezula/StormLib/blob/90c5928441ea0014598c9fd45284e8143a3ebca1/src/SFilePatchArchives.cpp#L219.

**Comment by grepwood** [comment]
Thank you! :)
