### ISSUE TITLE
Is it possible to add a file scanner to the program?

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#35]
Hello!

The issue that I have is, when I open MPQ it has filename9249119921, so when I want for example to export a model from MPQ, I either need to use programs such as:

MPQ Recover
RMPQeX
FileListGrabber  

In order to get the listfile for it. Yes, they are used for warcraft 3 maps. So I thought of asking you to add a MPQ scanner utility like in one of those programs. 
______________________________________________________________________________

Здравствуйте! 

Моя так сказать проблема заключается в том, что порой я открываю MPQ файлы и вместо их настоящего имени получаю file192491294129. Так как внутри MPQ был удален встроенный листфайл. Поэтому порой приходится использовать программы, что указаны выше.

Программы созданы для поиска имен файлов в картах варкрафта 3. Было бы круто если бы и в этой программе появилась функция сканирования файлов :)

Спасибо за внимание!
Thanks for attention!

**Comment by ladislav-zezula** [comment]
If I had the source of one of these, maybe.

**Comment by Tailer007** [comment]
Karaulov can send you the source code of it, or even I can, but it works a bit differently. As it's not an inside MPQ search but you target the program to the MPQ and it scans it. If it's the same then I guess his program should work for it too. As this feature would be really amazing.

**Comment by Tailer007** [comment]
After reading http://forum.wc3edit.net/useful-tools-f69/rmpqex-map-extractor-t6363.html

I found the author saying.

What it does:
function ADD(s): removes extension from s and tries s, s+".blp", s+".tga", s+".mdx", s+".mdl", s+".mp3", s+".wav"
Then it takes the filename part from s and tries "ReplaceableTextures\CommandButtonsDisabled\DIS"+s+""/".blp"/".tga"

First it uses ADD for all known filenames in the archive
Then it finds all .txt and .slk files and scans them: reads them line by line and for each line takes either the last quoted string or the part of the line after the '=' sign, and uses ADD
For all .j files, it finds all quoted strings and uses ADD
For all .mdx files it skips blocks and looks for MODL, TEXS, ATCH and PREM blocks and ADD's filenames from them.
For all object files (.w3u .w3t .w3b .w3d .w3a .w3h .w3q) it uses ADD for all string values.
In .w3i file it looks for loading screen path.
So I don't think there's anything it can miss.

Hope it helps!

**Comment by ladislav-zezula** [comment]
Beta build of MPQ Editor with Name Scanner is available:
http://www.zezula.net/download/mpqediten32-namescanner-beta.zip

It will need some more tuning, but so far, it has some good results, compared to RMPQEx.exe.

**Comment by actboy168** [comment]
It's so good! You can see the w3xExporter, it's 100% complete. @ladislav-zezula 
http://www.ydwe.net/w3xExporter103.zip

Could you open the source?

**Comment by ladislav-zezula** [comment]
As for the source, I can publish the source of the scanner itself - not the entire MPQ Editor.
http://www.zezula.net/download/w3x_name_scanner_source.zip
The project is missing resources and headers, so it won't be compilable without additional work -  I don't want copy cats to use it.

(irony) Hopefully this will help MPQ Protector people to do their job even better (/irony)

**Comment by ladislav-zezula** [comment]
As for the w3xExporter: Like RMPQEx.exe, this one uses a listfile too.
You can use the same listfile in MPQ Editor as well.

**Comment by actboy168** [comment]
I means can you publish to github. I can submitting a pull request or issues.

I scan the dota6.81d.w3x, and w3x_name_scanner cans founds only 1120 files. But w3xExporter cans founds 1158 files.

**Comment by ladislav-zezula** [comment]
Ah right. Here you go:
https://github.com/ladislav-zezula/W3xNameScanner

**Comment by wheybags** [comment]
@ladislav-zezula out of interest, why have you not released the source for mpq editor?

**Comment by actboy168** [comment]
@ladislav-zezula  Thank you very much.

**Comment by ladislav-zezula** [comment]
@wheybags: Because I don't want to.
