### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by Lectem** [ladislav-zezula/StormLib#350]
Hello,

It seems there have been quite a few fixes since the last version ( https://github.com/ladislav-zezula/StormLib/compare/v9.25...master ).
Would it be possible to bump the version number and make a new release ?
I think it would be better accepted by package managers and let people know they should get those fixes.

Thanks !

**Comment by ladislav-zezula** [comment]
[Sure](https://github.com/ladislav-zezula/StormLib/commit/fa129058b1a8d9e58a7d70a888b81121f9d48382). [Here](https://github.com/ladislav-zezula/StormLib/releases/tag/v9.26) is the release 9.26. I also rebuilt MPQEditor with the latest release.

**Comment by Lectem** [comment]
Thanks a lot !
FYI I've also opened a PR for the vcpkg port https://github.com/microsoft/vcpkg/pull/39197
