### ISSUE TITLE
Any chance for binaries here on Github?

### ISSUE THREAD

**Issue by malvarenga123** [ladislav-zezula/StormLib#351]
For some reason any time I try to access http://www.zezula.net/mpq.html, I get a "connection was reset" error, so I can't download the latest dll. Mirroring the release here on Github would avoid that issue.

**Comment by ladislav-zezula** [comment]
I'll setup something up. In the meantime, here is the DLL from version 9.26: [stormlib_dll.zip](https://github.com/user-attachments/files/15759068/stormlib_dll.zip)

**Comment by malvarenga123** [comment]
Thanks!
