### ISSUE TITLE
MPQ Editor can't open the mix file, resulting in an error that states the the file is not in the correct format.

### ISSUE THREAD

**Issue by SinisterLuffy5** [ladislav-zezula/StormLib#353]
The developer of this mix file stated that he used a special algorithm to prevent your MPQ Editor from opening it.
Here is the link to the file: https://www.mediafire.com/file/79ty4xvp92xwic0/AniDreams_1.0.0.2.rar/file

**Comment by ladislav-zezula** [comment]
Interesting. The MIX file performs few things:
- Hooks some file functions in ntdll.dll
- Then it loads fake DLL `test.dll`. The hooks make sure that the DLL "exists".
- That fake DLL performs `SFileOpenArchive` on fake MPQ `test.mpq` with priority 43. Again, those hooks make sure that it "exists".

Here is the link to the deprotected MPQ: http://www.zezula.net/[AniDreams]ResourcePack1.0.0.2.mpq.
Tell my greetings to the developer.

It is gonna be problematic to add into MPQ Editor. I would probably have to rework the whole thing, for which I don't have time now.

**Comment by ladislav-zezula** [comment]
I did some experiments with this protector. I'll try to integrate it into MPQ Editor, after all. Give me few days.
