### ISSUE TITLE
HW3M

### ISSUE THREAD

**Issue by Koral-cmd** [ladislav-zezula/StormLib#358]
hi zezula, I didn’t know how to contact you, I decided to do it this way, you could improve your mpq editor so that it could scan cards with compressed data blocks, someone changed some of the data in hex and because of this it is impossible to get a listfile map: https://irinabot.ru/maps/48714

**Comment by ladislav-zezula** [comment]
The map can be open just fine.

![image](https://github.com/user-attachments/assets/c42d37c5-8ecb-4c0a-a380-a4bd4aaf10e4)
