### ISSUE TITLE
Any way to let MPQEditor extract neutral/English language

### ISSUE THREAD

**Issue by captain-majid** [ladislav-zezula/StormLib#359]
The UI of MPQEditor itself allows you to see/extract different languages of the same file, but using the command line it extracts Spanish or other languages, how to make it extract the neutral/English version? what I'm using is:

`MPQEditor.exe e Patch_rt.mpq rez\stat_txt.tbl . /fp`

stat_txt.tbl exists 6 times at this path in the .mpq with the same name.

**Comment by ladislav-zezula** [comment]
Download new MPQ Editor and try this:
`MPQEditor.exe e Patch_rt.mpq rez\stat_txt.tbl . /fp /locale:0`
Using the new `/locale` flag, you can limit the extracted files to one locale only. The locale number may be decimal (`/locale:1234` or hexadecimal (`/locale:0x0407`)
