### ISSUE TITLE
MPQ.KangTooJeeЌ protection like Somj

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#36]
Раннее Караулов выложил проблему связанную с Somj защитой, написанной корейцами. На неё ему пожаловался я, а он поступил умнее и связался с вами, о чем я не подумал :D Если вам не сложно взгляните на систему защиты. Ссылка на файл http://dropmefiles.com/Kcgzp . По факту она дает проге открыть файл, но из-за искажения хекса не покажет файлы.
_______________________________________________________________________________

Previously Karaulow posted the issue about Somj protection, that was created by Koreans. I told him about it, and he asked you here, which I didn't think of :D. If it won't be problematic for you, please also take a look on another protection system. File URL http://dropmefiles.com/Kcgzp . It acts nearly in same way as somj, by damaging the header, but instead of just blocking the access it allows you to open it with the programm, but you can't see any files in it.

Спасибо за внимание!
Thanks for Attention!

**Comment by ladislav-zezula** [comment]
I'll look at it eventually.

**Comment by ladislav-zezula** [comment]
Would it be possible to send me an example of the protected map?
Please, send it to zezula-at-volny-dot-cz

**Comment by ladislav-zezula** [comment]
Support for this protector added in commit c2261d51033088429ba960879dd4d9731e6f9bc1.
However, there is quite a lot of false positives in that archive (fake files that cannot be read), I'll try to remove them from the block table when the MPQ is open.
