### ISSUE TITLE
Idk where to put MPQ Editor bug, so I'll put it here

### ISSUE THREAD

**Issue by mricewolf0110** [ladislav-zezula/StormLib#360]
I use Wine-GE to run MPQ Editor. It hang when loading large map, for example https://www.epicwar.com/maps/339406/, same thing happens when you scan the map and apply scanned file list.

**Comment by mricewolf0110** [comment]
> I just tried the map you provided on this version of Linux: ![image](https://private-user-images.githubusercontent.com/3244359/369393620-b9a21888-2c93-4209-98fb-aeddcf6933f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzc3NjgsIm5iZiI6MTcyNjgzNzQ2OCwicGF0aCI6Ii8zMjQ0MzU5LzM2OTM5MzYyMC1iOWEyMTg4OC0yYzkzLTQyMDktOThmYi1hZWRkY2Y2OTMzZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTMwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTdlMWRkY2U2MDYwYmM0YmZjYzFlODgzYTRkNjg5ZTcwNzQ5NTliZWEzZDcyMDcyMjY4NjZlOTQxZmMyYTgyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hnF4qDn9fWJZUAmgyIJgJ2vqTDjUVyLVOAgHmLSoFkI)
> 
> I was able to load that map just fine. Then, I selected "Tools / W3X Name Scanner" and clicked "Scan" in Map File Scanner. It found several unknown names. I clicked "Apply and it added these new entries to the file list just fine: ![image](https://private-user-images.githubusercontent.com/3244359/369394339-becadda6-5d58-4de6-9b87-c6a25d673ff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzc3NjgsIm5iZiI6MTcyNjgzNzQ2OCwicGF0aCI6Ii8zMjQ0MzU5LzM2OTM5NDMzOS1iZWNhZGRhNi01ZDU4LTRkZTYtOWI4Ny1jNmEyNWQ2NzNmZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTMwNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJjOGQxNjM1MGI1MWE1NzhiNjc1MThmMmY2YzQzMjA4ZmY5OTE4MjBlYjdkOWY0OGM3YzM4YWE5ZmRlMzQ2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7--7L_SohtBjm_kXfu_cA5xGq3Qm2-YvXHVcIFGT5-4)

Pls try on a fresh install of wine. Mine is just freeze like this. Lutris logs show no warning.
![image](https://github.com/user-attachments/assets/a9c07b07-a414-4786-a2da-f41606bf2fbe)

**Comment by mricewolf0110** [comment]
any update on this?

**Comment by ladislav-zezula** [comment]
You will have to contact Win-GE authors to look what's wrong. This is not a bug in MPQ Editor, because it loads the map just fine in Windows and also in normal version of Wine. Therefore I don't feel the need to fix anything.
