### ISSUE TITLE
Ruby bindings for stormlib

### ISSUE THREAD

**Issue by sebyx07** [ladislav-zezula/StormLib#361]
hey, I created bindings for ruby for your library:

https://github.com/sebyx07/stormlib

I'll be using it in https://github.com/sebyx07/rails-on-azerothcore

You can in your readme my bindings library if you want

**Comment by ladislav-zezula** [comment]
Thank you. IIRC there are also Python bindings somewhere. They are not present in the readme either, but if you want, make a pull request with new README.
