### ISSUE TITLE
Where is StormLib_vs19.sln file?

### ISSUE THREAD

**Issue by sethmachine** [ladislav-zezula/StormLib#364]
I cannot find this file in the repo.  Is it checked in somewhere?  A search on GitHub doesn't show it: https://github.com/search?q=repo%3Aladislav-zezula%2FStormLib%20StormLib_vs19.sln&type=code 

I am trying to build this for Windows using Visual Studio 2019.  Most of the instructions don't seem to actually match what's in the GUI program either...

**Comment by ladislav-zezula** [comment]
I updated the build instructions. Build solution file for VS 2019 is no longer there and was replaced by `StormLib.sln`.
