### ISSUE TITLE
Incorrect File Name

### ISSUE THREAD

**Issue by kizl01** [ladislav-zezula/StormLib#365]
Original map file: https://drive.google.com/file/d/1Uzzu4jVZpdCVbAXeJcnZDHQmaMdJuqzP/view?usp=sharing

Hi, I encountered an issue while trying to open this china map with MPQ Editor. It's resulted to open successfully but there're many of .mdx files that has the same file's name.

When I export these files, their names change to "%7C..." which does not match the original.
![image_2024-10-26_213426041](https://github.com/user-attachments/assets/d3cb0307-6d06-489d-8c95-4d5ba9a0b5e4)

If I make any changes to war3map.j, the model files become invisible (see image above).

There's a Chinese tool that encrypts models in this way, but it's old, and I’m not sure if it's related to this kind of protection. Here is the tool: https://github.com/sumneko/Model_Encrypt

Can you take a look at this?
Much appreciate

**Comment by ladislav-zezula** [comment]
The map doesn't have multiple MDX files with the same name. Those `File00000091.mdx` are generic file names that allow to open those files without knowing their names.

If you want to modify them, you will have to find out the names, then add them to the listfile and then reopen the map again.

**Comment by kizl01** [comment]
Sorry I didn't made it clear, there're many files with chinese character in it, here a picture about it
![image](https://github.com/user-attachments/assets/12dbdd98-ddb2-4956-847a-19e7d712d842)

**Comment by ladislav-zezula** [comment]
I can see the first MDX file (the one with 888 664 bytes) as `File00000577.mdx`. Given that the map doesn't have a listfile, it must have been the specific listfile that you use. Can you send it to me?

![image](https://github.com/user-attachments/assets/1b6117aa-15d3-40d4-8474-2feb885684f3)

**Comment by kizl01** [comment]
I use W3x Name Scanner from MPQ Editor, here is the listfile
[list.txt](https://github.com/user-attachments/files/17533102/list.txt)

Thank you

**Comment by ladislav-zezula** [comment]
Looking at the listfile in UTF-8, I can see some Chinese file names. Can you confirm they are correct?

![image](https://github.com/user-attachments/assets/3f08c3d7-89f5-45e9-833c-0479227f0f4e)

**Comment by kizl01** [comment]
Yes, they're correct.
There're 1206 files in total, if I extract these file, MPQ will say that file already exist and resulted extract only 4 files.
![image](https://github.com/user-attachments/assets/37ae50f7-f7ed-466c-8546-336df19f4c79)

![image](https://github.com/user-attachments/assets/a2a84884-4899-4ea6-b484-6a7dec272c79)

**Comment by ladislav-zezula** [comment]
Ok. I now have enough information to investigate. I'll play with the MPQ and listfile a bit, will also add that map (with the listfile) to StormLib regression tests. Give me some time :-)

**Comment by kizl01** [comment]
Great to hear that, hope you find out how they did this kind of protection.

Thank you for your help

**Comment by ladislav-zezula** [comment]
The "protection" is actually quite simple. Multiple files in that map have a file name that is an invalid UTF-8 string. MPQEditor converts file names into UNICODE UTF-16 using [MultiByteToWideChar](https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar). That function has one caveat - it converts all invalid UTF-8 characters into 0xFFFD. 

In short, various different invalid chars are converted into the same char 0xFFFD.
That's how we get multiple occurrences of the same file in the output directory.

The solution is to replace [MultiByteToWideChar](https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar) with an own conversion function, which will turn the MPQ UTF-8 file names into a file-name-safe string. Ideally, that function should work bi-directional, so adding the file back will preserve the file name.

**Comment by kizl01** [comment]
Oh, so it's on the Windows side, not the MPQ side, never thought of that before.

I think I know what to do next, so thank you for your help and sorry for the late reply.

Much appreciated!

**Comment by ladislav-zezula** [comment]
I added [translation functions](https://github.com/ladislav-zezula/StormLib/blob/86f9b99ffe4d3417dad16d00541cf6f2e3d7bf79/src/SMemUtf8.cpp#L347) between MPQ-UTF-8 and safe file names into StormLib.
Also, the presence of invalid UTF-8 sequences made me re-check quite some places in the MPQ Editor code.

Obviously, due to the invalid sequences or unallowed characters, these functions must encode these file names into something file-name-safe (and decode back when adding the file to MPQ).

![image](https://github.com/user-attachments/assets/ff41c27f-a0a9-44ac-baec-10e1623b2f10)
