### ISSUE TITLE
Issues with the latest release.

### ISSUE THREAD

**Issue by wroldLove** [ladislav-zezula/StormLib#368]
Using version 9.30 fails to open mpq files, while version 9.25 runs everything normally.

This is my DLL code declaration.
` [DllImport(STORMLIB, CallingConvention = CallingConvention.Winapi, ExactSpelling = true, PreserveSig = true, SetLastError = true, ThrowOnUnmappableChar = false)]` 
` public static extern bool SFileOpenArchive([MarshalAs(UnmanagedType.LPStr)] string szMpqName, uint dwPriority, SFileOpenArchiveFlags dwFlags, out IntPtr phMPQ);`

**Comment by ladislav-zezula** [comment]
Can you send me an example of MPQ that you cannot open?

**Comment by wroldLove** [comment]
> * Can you send me an example of MPQ that you cannot open?
> * After the failed call, what does GetLastError return?

GetLastError returns a result of 6

The call to SFileOpenArchive completely failed.

I tested various maps and the result is the same; this issue only occurs in 9.30.

**Comment by ladislav-zezula** [comment]
`SFileOpenArchive([MarshalAs(UnmanagedType.LPStr)] ...`
It seems that the prototype orders to send LPSTR as name of the MPQ. But the DLL takes LPTSTR and it's built with UNICODE support, so the real parameter should be LPWSTR. Can you try?

**Comment by wroldLove** [comment]
> `SFileOpenArchive([MarshalAs(UnmanagedType.LPStr)] ...` It seems that the prototype orders to send LPSTR as name of the MPQ. But the DLL takes LPTSTR and it's built with UNICODE support, so the real parameter should be LPWSTR. Can you try?

Before I built this topic, I tested it, and using LPWStr would get stuck on opening the mpq file, unable to proceed, and the memory kept increasing.

**Comment by ladislav-zezula** [comment]
This works for me just fine:
```
    static class Program
    {
        [DllImport("StormLib.dll", CallingConvention = CallingConvention.Winapi, ExactSpelling = true, PreserveSig = true, SetLastError = true, ThrowOnUnmappableChar = false)]
        public static extern bool SFileOpenArchive([MarshalAs(UnmanagedType.LPWStr)] string szMpqName, uint dwPriority, uint dwFlags, out IntPtr phMPQ);

        [DllImport("StormLib.dll", CallingConvention = CallingConvention.Winapi, ExactSpelling = true, PreserveSig = true, SetLastError = true, ThrowOnUnmappableChar = false)]
        public static extern bool SFileCloseArchive(IntPtr phMPQ);

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main(string[] Args)
        {
            IntPtr hMpq;

            if (SFileOpenArchive("c:\\map.w3x", 0, 0, out hMpq))
            {
                Console.WriteLine("Opening MPQ succeeded.");
                SFileCloseArchive(hMpq);
            }
        }
    }
```

**Comment by wroldLove** [comment]
> This works for me just fine:
> 
> ```
>     static class Program
>     {
>         [DllImport("StormLib.dll", CallingConvention = CallingConvention.Winapi, ExactSpelling = true, PreserveSig = true, SetLastError = true, ThrowOnUnmappableChar = false)]
>         public static extern bool SFileOpenArchive([MarshalAs(UnmanagedType.LPWStr)] string szMpqName, uint dwPriority, uint dwFlags, out IntPtr phMPQ);
> 
>         [DllImport("StormLib.dll", CallingConvention = CallingConvention.Winapi, ExactSpelling = true, PreserveSig = true, SetLastError = true, ThrowOnUnmappableChar = false)]
>         public static extern bool SFileCloseArchive(IntPtr phMPQ);
> 
>         /// <summary>
>         /// The main entry point for the application.
>         /// </summary>
>         [STAThread]
>         static void Main(string[] Args)
>         {
>             IntPtr hMpq;
> 
>             if (SFileOpenArchive("c:\\map.w3x", 0, 0, out hMpq))
>             {
>                 Console.WriteLine("Opening MPQ succeeded.");
>                 SFileCloseArchive(hMpq);
>             }
>         }
>     }
> ```

Alright, I'll try to track down where the problem is coming from. Thank you, ladislav-zezula.

**Comment by ladislav-zezula** [comment]
Oki. If you need, I can make you a debug version of the DLL that prints stuff to the debug console. Let me know if you would use that.

**Comment by wroldLove** [comment]
> 冲。如果需要，我可以为您制作一个 DLL 的调试版本，用于将内容打印到调试控制台。如果你愿意使用它，请告诉我。

Yes, I need it, thank you very much. ladislav-zezula

**Comment by wroldLove** [comment]
Hi, Ladislav-Zezula, I found that executing SFileFindFirstFile completely freezes the program and can only be forcefully terminated.

**Comment by ladislav-zezula** [comment]
Ok, here's how we best solve it:

- Make a debug version of your app that tries to open a given MPQ in C:\ folder, then it tries to list the files.
- Pack the app and the MPQ into a ZIP file and attach it here.

I'll run your app with the debug version of the DLL and look where the deadlock comes from.

**Comment by wroldLove** [comment]
I have uploaded the file to Google Drive.[https://drive.google.com/file/d/1qts35P8whWep2g_ndEl_dkynZKujTUzp/view?usp=drive_link](url)

**Comment by ladislav-zezula** [comment]
I need access for downloading. Best to give it to anyone who has link.

**Comment by wroldLove** [comment]
> I need access for downloading. Best to give it to anyone who has link.

Permission has been granted.

**Comment by ladislav-zezula** [comment]
As for the definition of `SFILE_FIND_DATA`: 
```
        public unsafe struct SFILE_FIND_DATA
        {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
            public string cFileName;
            public IntPtr szPlainName;
            public uint dwHashIndex;
            public uint dwBlockIndex;
            public uint dwFileSize;
            public uint dwFileFlags;
            public uint dwCompSize;
            public uint dwFileTimeLo;
            public uint dwFileTimeHi;
            public uint lcLocale;
        }
```
Are you sure that `char   cFileName[MAX_PATH];` can be marshalled as "public string cFileName'? Moreover, it's not TSTR, but an ANSI string. More precisely, it's an UTF-8 string.

**Comment by wroldLove** [comment]
> As for the definition of `SFILE_FIND_DATA`:
> 
> ```
>         public unsafe struct SFILE_FIND_DATA
>         {
>             [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
>             public string cFileName;
>             public IntPtr szPlainName;
>             public uint dwHashIndex;
>             public uint dwBlockIndex;
>             public uint dwFileSize;
>             public uint dwFileFlags;
>             public uint dwCompSize;
>             public uint dwFileTimeLo;
>             public uint dwFileTimeHi;
>             public uint lcLocale;
>         }
> ```
> 
> Are you sure that `char cFileName[MAX_PATH];` can be marshalled as `public string cFileName`? Moreover, it's not TSTR, but an ANSI string. More precisely, it's an UTF-8 string.

How to correctly declare,Thank

**Comment by ladislav-zezula** [comment]
No idea how to tell C#. You need to do your own googling. BTW, your test program works perfectly on my PC, it just prints nonsenses. That being said, please, fix the marshalling first, then we'll debug.

**Comment by wroldLove** [comment]
> No idea how to tell C# that it should use char array. You need to do your own googling.
> 
> BTW, your test program works perfectly on my PC, it just prints nonsenses. That being said, please, fix the marshalling first, then we'll debug.

Thank you, I will go look for information.

**Comment by ladislav-zezula** [comment]
Change from:
```
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public unsafe struct SFILE_FIND_DATA
        {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
            public string cFileName;
            public IntPtr szPlainName;
            public uint dwHashIndex;
            ...
```
into
```
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public unsafe struct SFILE_FIND_DATA
        {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
            public string cFileName;
            public IntPtr szPlainName;
            public uint dwHashIndex;
            ...
```
made the program start printing proper file names.
