### ISSUE TITLE
Another MPQ that works in War3 but not in StormLib

### ISSUE THREAD

**Issue by Ralle** [ladislav-zezula/StormLib#369]
Hello,

Here is a War3 map file that cannot be opened by StormLib, but works in War3 all the same. Would appreciate it if you looked into it.
https://drive.google.com/file/d/1Kcp5JodSFQA2CJilfyoOEDWknH6cfXEW/view?usp=sharing

The author was using https://w3protect.eu/ to protect the map. It's a paid service.

**Comment by ladislav-zezula** [comment]
MPQ Editor can open the map just fine. And file extraction works too.

![image](https://github.com/user-attachments/assets/9d4d9541-5545-41d9-9ba5-c189367b1a7e)

**Comment by Ralle** [comment]
The heck? Sorry to have wasted your time then. I will need to investigate what trouble I am having more then. Thanks for the response.
