### ISSUE TITLE
Hashes instead of minimap names

### ISSUE THREAD

**Issue by freekode** [ladislav-zezula/StormLib#37]
I already asked about it in Kanma/MPQExtractor#9.

Which method used for hashing the filenames?

**Comment by Deaod** [comment]
If i had to guess, id say that its an MD5 hash, which was not used for MPQs of format 0. So i dont know how you came by these files, but im pretty sure the file name was not produced by StormLib. Its either in the listfile verbatim, or something renamed it for you after extracting it using StormLib.

**Comment by freekode** [comment]
Ok. Theoretically, if I use StormLib directly (not over MPQExtractor) with my code, it will generate normal filenames?

Is there any information about minimap files in other files, like WMO, DBC and so on? Maybe I can obtain some info from them (how to put together this minimap tails)?

**Comment by xboi209** [comment]
>When the caller doesn't know the proper file name, a pseudo name can be used. The pseudo name is in the form of File%08u.xxx (case sensitive). The numeric part of the file is the index in the file table.
http://www.zezula.net/en/mpq/stormlib/sfileopenfileex.html

**Comment by ladislav-zezula** [comment]
From what I remember, these file names really were there, they were even on the listfile included in the MPQ. No, MD5 is not used much in MPQs (except for integrity check).

**Comment by timkurvers** [comment]
> Is there any information about minimap files in other files, like WMO, DBC and so on? Maybe I can obtain some info from them (how to put together this minimap tails)?

This seems to be for Cataclysm rather than Vanilla, but this blog-post goes into details on generating a (mini)map: http://www.iamcal.com/world-of-mapcraft/

**Comment by freekode** [comment]
@timkurvers already have read it :)

I have downloaded listfiles from [here](http://www.zezula.net/en/mpq/download.html)
```bash
$ cat World\ of\ Warcraft\ 1x.txt | grep 'textures\\Minimap'
textures\Minimap\md5translate.trs

$ cat World\ of\ Warcraft\ 2x.txt | grep 'textures\\Minimap'
....
textures\Minimap\ff8a6a20c2ad62d65b964f3eaffca1e8.blp
...
```
Maybe I'm doing something wrong, I tried with The Burning Crusade (with listfile and without):
```bash
$ MPQExtractor -e "textures\Minimap\*" \
    -p WoW_BC/Data/patch.MPQ WoW_BC/Data/patch-2.MPQ \
    -f -o out \ 
    WoW_BC/Data/common.MPQ

Opening 'WoW_BC/Data/common.MPQ'...

Searching for 'textures\Minimap\*'...

Found files:
  - textures\Minimap\000c0abfbdd4893e4467425d0f645cbd.blp
...
```

As you can see, nothing interesting.
