### ISSUE TITLE
last ver MPQ file replacement failed

### ISSUE THREAD

**Issue by jzy-chitong56** [ladislav-zezula/StormLib#370]
I am glad that the new version has fixed the issue of the replacement prompt box being too large
But new problems have arisen
He said the file already exists and cannot be created. In theory, I don't need to create it, but just replace it. He didn't even ask for replacement, so he couldn't create it directly

![image](https://github.com/user-attachments/assets/ad834b78-08c8-4e36-8786-0545e4cfefef)

![image](https://github.com/user-attachments/assets/0afbf607-5a1a-46ab-949d-c0445003df67)

--------------------------------------------------------------
Also, may I ask if `cascview` can support remakes of Warcraft 1 and 2
If there is a plan to update, I would like to know the approximate time to prepare a new Chinese text in advance

**Comment by jzy-chitong56** [comment]
I believe that replacing any map will prompt like this. I encountered this when replacing AI and J scripts

------------------------------------------------------------------------

Battle.net cannot be downloaded for free I didn't expect you not to make a purchase
If you can register
try -- I'm not sure if there's a charge
https://www.kunkunwu.com/post/5491.html
https://www.kunkunwu.com/post/5490.html

**Comment by ladislav-zezula** [comment]
I fixed the replace dialog in MPQ Editor. However, there are known issues in displaying message box that I still need to fix.

**Comment by ladislav-zezula** [comment]
I added support for Warcraft I Remastered and Warcraft II Remastered to CascView. Enjoy.
