### ISSUE TITLE
Compilation error: RC1015 cannot open include file 'afxres.h'

### ISSUE THREAD

**Issue by myheadisempty** [ladislav-zezula/StormLib#371]
Hello,
I'm encountering a compilation issue with the StormLib.dll project. During the build process, the following error occurs:
`src\DllMain.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.`
This seems to be due to the inclusion of `afxres.h`, which requires MFC support to be installed in Visual Studio. The error can be resolved by replacing `#include "afxres.h"` with `#include "winres.h"`.
However, I want to know if there is a way to resolve this issue without modifying the source code. Is there an alternative configuration or setup that would allow successful compilation without requiring changes to the codebase?
Any guidance would be appreciated. Thank you!

**Comment by ladislav-zezula** [comment]
Just install MFC support. Probably the easiest and fastest solution.
