### ISSUE TITLE
not building bzip2 on linux

### ISSUE THREAD

**Issue by Mistranger** [ladislav-zezula/StormLib#38]
bzip2 sublibrary (in src/bzip2 folder) isn't compiling on Linux when running make. I'm use StormLib as a static library in my project and that gives me a compiling error when I'm trying to build my project with static libstorm.a
/usr/local/lib/libstorm.a(SCompression.cpp.o): In function `Compress_BZIP2(void*, int*, void*, int, int*, int)':
SCompression.cpp:(.text+0x7cb): undefined reference to `BZ2_bzCompressInit'
SCompression.cpp:(.text+0x814): undefined reference to `BZ2_bzCompress'
SCompression.cpp:(.text+0x831): undefined reference to `BZ2_bzCompressEnd'
/usr/local/lib/libstorm.a(SCompression.cpp.o): In function `Decompress_BZIP2(void*, int*, void*, int)':
SCompression.cpp:(.text+0x888): undefined reference to `BZ2_bzDecompressInit'
SCompression.cpp:(.text+0x8be): undefined reference to `BZ2_bzDecompress'
SCompression.cpp:(.text+0x8db): undefined reference to `BZ2_bzDecompressEnd'
I made a workaround by adding ${ZLIB_BZIP2_FILES} in CMakeLists.txt, line 286.

**Comment by wheybags** [comment]
Yo're supposed to use system bzip on linux.
Add -lbzip2 (or whatever the actua flag is, can't remember) to the gcc
command line

**Comment by Mistranger** [comment]
yes, I've built my broject with bzip and everything is ok now
