### ISSUE TITLE
MPQ file opening too slow

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#40]
Hello again, yes it's me with another mpq that is being processed way too slow. The reason for it is, due to 3 heades and a spazzler making MPQ Ediotr loop in file processing. So basically it can be opened, but it consumes up to 4 gb of Ram in order to continue checking files and nearly kills CPU with work.

To download the file click: http://dropmefiles.com/nCawx 

With my 1.8 Ghz processor it took 30 minutes to process it half-way. ><''

**Comment by ladislav-zezula** [comment]
Fixed in commit 93370897471cb7bff861f9e961ff36e6ce46a5e8.
MPQ Editor also rebuilt, that map opens way faster now when those malformed compressed files are ignored.
