### ISSUE TITLE
Consider fixing resource leaks from coverity scan

### ISSUE THREAD

**Issue by Meai** [ladislav-zezula/StormLib#44]
![stormlib](https://cloud.githubusercontent.com/assets/649922/7668195/380a904c-fc2b-11e4-9c0b-f8f62d64ea24.png)

there seem to be around 50 issues that have been detected by a free online coverity scan.
if you dont want to set it up i can send you an invite i guess so you can look at the issues
im still very new to the project so i doubt any fixes coming from me would be that good

http://www.coverity.com/products/coverity-scan/

**Comment by ladislav-zezula** [comment]
I'll try to set it up on my own, if I fail, I'll let you know.
