### ISSUE TITLE
Functions fail on empty files

### ISSUE THREAD

**Issue by xboi209** [ladislav-zezula/StormLib#45]
````SFileVerifyFile```` fail when specifying an empty file(in my case, a .txt file with no text inside it).

**Comment by ladislav-zezula** [comment]
I created a new MPQ with an empty file. Then reopened the archive and called SFileVerifyFile (returned 0). Then I opened the file and called SFileGetFileSize. Returned 0 as well.

Is it any special MPQ where the functions failing?

**Comment by xboi209** [comment]
Sorry I didn't mean the SFileGetFileSize function. Also I just realized I overlooked the return values: http://www.zezula.net/en/mpq/stormlib/sfileverifyfile.html
I only looked at the table for return values but not the little text above it
