### ISSUE TITLE
why not use premake to generate project file?

### ISSUE THREAD

**Issue by leeonix** [ladislav-zezula/StormLib#46]
you have so many project file and makefile:
```
StormLib.xcodeproj\
Makefile.linux
Makefile.mac
makefile.w32
StormLib.vcproj
StormLib.vcxproj
StormLib.vcxproj.filters
StormLib_dll.vcproj
StormLib_dll.vcxproj
StormLib_dll.vcxproj.filters
StormLib_test.vcproj
StormLib_test.vcxproj
StormLib_test.vcxproj.filters
StormLib_v09.sln
StormLib_v11.sln
```

why not write a [premake-4](https://github.com/premake/premake-4.x) or [premake-5](https://github.com/premake/premake-core) file to generate these file automatic?

If you need, I'll write one to submit a PR.

Blizzard use it too.

**Comment by ladislav-zezula** [comment]
You gonna have to live with it. There is many people who build StormLib, I'd like to keep it that way so you can change settings in one platform without screwing all others.

**Comment by leeonix** [comment]
people use those files, it isn't a problem.
Becaure `Premake` can generate same name files like this
```
StormLib.vcproj
StormLib.vcxproj
StormLib.vcxproj.filters
StormLib_dll.vcproj
StormLib_dll.vcxproj
StormLib_dll.vcxproj.filters
StormLib_test.vcproj
StormLib_test.vcxproj
StormLib_test.vcxproj.filters
```
you can see #47
the problem is. if you add or delete some file, or other operaion.
it is not clearly, it is so complex.
like your `StormLib.vcxproj` plateform x64, also define `WIN32` no `WIN64`
plz try it.

**Comment by leeonix** [comment]
I use premake's some reason:
1. add new file
2. modify some option.
3. crosss platform
4. not like cmake, just only generate file. other option I modify the project file
