### ISSUE TITLE
Framework and dylib do not build via xcodebuild

### ISSUE THREAD

**Issue by RyuKojiro** [ladislav-zezula/StormLib#50]
They only build via the Makefile, I'm assuming (based on the git history) that the Xcode project file has been neglected, while the rest of the project had advanced.

This PR (https://github.com/ladislav-zezula/StormLib/pull/49) fixes it.

**Comment by timkurvers** [comment]
It's worth mentioning that `cmake CMakeLists.txt` generates a functional Xcode project as far as I'm aware.

**Comment by RyuKojiro** [comment]
With -G Xcode, yes. However, the output of cmake is an xcode project with lots of absolute paths in it. On top of that, the Xcode project file is source controlled, so why not have the working one in the repo?

**Comment by ladislav-zezula** [comment]
Sure it is good to have a working XCode project. It was outdated because I am not a Mac programmer, so I cannot fix it.

**Comment by RyuKojiro** [comment]
Ignore me! I only saw that this got closed, and not the PR :P

**Comment by ladislav-zezula** [comment]
:-)
