### ISSUE TITLE
Can StormLib support write Encrypted MPQ file? 

### ISSUE THREAD

**Issue by gxlmyacc** [ladislav-zezula/StormLib#51]
Hi, your project is very great.
and can it support write Encrypted MPQ file that use a custom password? I think ti is a very necessary function

**Comment by ladislav-zezula** [comment]
The fact that you are the first person requiring that since release of Starcraft 2, makes me doubt that it's so necessary.

**Comment by jleclanche** [comment]
@ladislav-zezula I wouldn't be against it either tbh. It's useful.

**Comment by ladislav-zezula** [comment]
I'll think about it. No promises though. There would have to be an extension to the interface for it, which I usually dislike to do.

**Comment by gxlmyacc** [comment]
Hi, because I want to use StromLib as a compressed file, it's a similar Zip. and read/load file MPQ file is faster than zip, but I also hope that MPQ file which I generated is encrypted, so that the other people can not read my file
