### ISSUE TITLE
SFileAddFileEx ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by PurgeGit** [ladislav-zezula/StormLib#52]
I was trying to use SFileAddFileEx(...) to add a file to my map. Even though SFileAddFileEx returns true (which should imply that GetLastError() == ERROR_SUCCESS), GetLastError() gives an error code of 2 (which on Mac/Linux is ERROR_FILE_NOT_FOUND).

* I opened the archive as BASE_PROVIDER_FILE 
* I tried different flags for SFileAddFileEx. I'm currently using MPQ_FILE_REPLACEEXISTING, but I tested it with 0 and it still gives that error code.
* The file I'm adding exists on my hard drive, and it is successfully added to the mpq. It is listed if I use SFileFind.

I'm pretty lost. I can always just use SetLastError(0) after adding the file (and things seem to work okay), but that probably isn't the way to approach it. Does anyone else get this?

Here is the relevant code if anyone is interested:
``` Objective-C
-(BOOL)addFile:(NSString*)file archivePath:(NSString*)path flags:(unsigned int)flags compression:(unsigned int)compression error:(NSError **)errorPtr {
    const char *fileName = [file UTF8String];
    const char *archivedName = [path UTF8String];
    
    if (!SFileAddFileEx(_archive, fileName, archivedName, flags, compression, compression)) {
        *errorPtr = [MPQ getError];
        return NO;
    }
    //if (GetLastError() == ERROR_FILE_NOT_FOUND) {
    //    SetLastError(0);
    //}
    *errorPtr = nil;
    return YES;
}
```
``` Objective-C
NSString *fileToAdd = @"/Users/j/Downloads/Warcraft III Stuff/test.j";
    unsigned int flags = MPQ_FILE_REPLACEEXISTING;
    [mpq addFile:fileToAdd archivePath:@"test.j" flags:flags compression:MPQ_COMPRESSION_ZLIB error:&error];
    if (error != nil) { // error is nil
        NSLog(@"Add file fail.");
        [ViewController alert:error];
        [mpq close:&error];
        return;
    }
    NSLog(@"%d", GetLastError()); // prints '2'
```

Thanks for any and all help. Chances are that this is some silly mistake on my end, but I can't seem to resolve it.

**Comment by ladislav-zezula** [comment]
The logic of GetLastError is that it returns error code of last failed operation. Because your call to SFileAddFileEx succeeded, your call to GetLastError returns something that failed before.

You should only do this:

int nError = ERROR_SUCCESS;

if(!SFileAddFileEx(...))
    nError = GetLastError();

...

**Comment by PurgeGit** [comment]
That makes sense. Thank you!
