### ISSUE TITLE
The map can not be edited. New protector?

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#54]
http://rghost.ru/private/8x5zXskXH/d86be3f27c682f9f5e6d7c2d7e7d244e
Fix it! Please :)

**Comment by Tailer007** [comment]
Make sure you are using the latest version. I've opened it and edited it without any problem.

![2](https://cloud.githubusercontent.com/assets/11413837/10483995/25ccbf6e-728b-11e5-94a7-49692d28a681.jpg)
![3](https://cloud.githubusercontent.com/assets/11413837/10483994/25cac916-728b-11e5-9807-dfde66caf5f3.jpg)
![1](https://cloud.githubusercontent.com/assets/11413837/10483993/25ca4fb8-728b-11e5-9342-c688cf05d6ed.jpg)

**Comment by Karaulov** [comment]
http://i.imgur.com/4073nOy.png
http://i.imgur.com/tU5LBoR.png
http://i.imgur.com/NywWHCa.png

**Comment by Tailer007** [comment]
Try using this version then, for me even latest one is opening just fine. I've tested this one just now, it doesn't have read-only mode for any protected map. But it can't open somj protection. So use this one for Dota.

![1](https://cloud.githubusercontent.com/assets/11413837/10484966/dc885be6-7290-11e5-90ed-214d3da05851.jpg)

**Comment by Karaulov** [comment]
Not working! Only read-only mode.

**Comment by Tailer007** [comment]
Have you tried runnin MPQ Editor as administrator? I'm really confused :D As it should be working fine on older versions. Let's wait for Zezula to give a proper answer.

**Comment by ladislav-zezula** [comment]
Stormlib is written so it opens all malformed MPQs (which includes protected maps, as every protection is also a malformation) in read-only mode. If you want to edit it, extract all files and create new map.
