### ISSUE TITLE
W3X Name Scanner not working?

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#55]
ladislav-zezula, Your scanner is not found over three hundred files.

Perhaps the reason is that some files do not require the extension and  the game autosearch extensions for textures ?

For example "Directory1\File1.blp" can be written as "Directory1\File1". The game itself adds the extension ".blp, .tga". Maybe it makes sense to add extensions bruteforce?

Or maybe you can to add bruteforce buttons?:
        BTN
        PASBTN
        PAS
        DIS
        DISBTN
        DISPASBTN
        DISPAS
	

You can somehow improve the scanning of files?

Example of map where bigger that 300 files can't be found : http://www.mediafire.com/download/4lr8rtkn25xr25z/36_The_Blood_Way_O.w3x

**Comment by ladislav-zezula** [comment]
It does work fairly well. At least the one included in MPQ Editor.
See the screenshot.
![map-scanner](https://cloud.githubusercontent.com/assets/3244359/10911115/8516a076-8243-11e5-858f-8cf3653cc540.png)

**Comment by Karaulov** [comment]
With default listfile.txt 
![1](https://cloud.githubusercontent.com/assets/6445336/10912659/868215f4-825b-11e5-9d83-1ed59d3c3366.png)
After W3X Name Scanner 
![2](https://cloud.githubusercontent.com/assets/6445336/10912660/86a2e69e-825b-11e5-809f-c8cca681229b.png)
After my own name scanner (Read all string files from all files, bruteforce extensions, bruteforce button types and etc):
![3](https://cloud.githubusercontent.com/assets/6445336/10912661/86add00e-825b-11e5-9125-f6f7ad4e3b93.png)

But I would like to get 100% listfile, is this possible? You try to improve your scanner?

**Comment by ladislav-zezula** [comment]
Well, mine ended up at 36 unknowns, but I used the Warcraft III Maps.txt listfile as start. You can probably never get 100% listfile, because there might be files that are not referenced anywhere.
Normally, I don't deal with name scanning, so I don't normally update it.

**Comment by Karaulov** [comment]
Only 36 unknown files?

You can give your listfile.txt? What is the version Mpq Editor?

**Comment by ladislav-zezula** [comment]
Download the listing pack from my web and use Warcraft III maps.txt.

**Comment by ladislav-zezula** [comment]
*listing = listfile
