### ISSUE TITLE
Rebuild map with only button ?

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#56]
Add please rebuild w3x map by one click. (For protected archives)
It's very simple? You can add this?

**Comment by ladislav-zezula** [comment]
Regardless of what does "rebuild map" actually mean, I have no plans to extend the map scanner.

**Comment by Karaulov** [comment]
Rebuild map:

1. Create empty w3x map archive with same name in header.
2. Paste into this map all known files.
3. Compact archive
