### ISSUE TITLE
StormLib bad! See no files...

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#57]
Please fix it :anguished:  ! For example in WinMpq well see these files. Please add viewmode as in Winmpq!
This new protection against StormLib go bypass it!

http://www.mediafire.com/download/c7pxid2cc611qf6/fixme.mpq with (filelist)

**Comment by Karaulov** [comment]
And fixme v2, mpq with 8 files!!!! Try open it in MpqEditor and then in WinMpq, see the difference

http://www.mediafire.com/download/a4hf40m9200c26d/fixmev2.0.mpq

**Comment by Karaulov** [comment]
possible fix this?

**Comment by ladislav-zezula** [comment]
Fixed in commit dae6c5e315445b0c25d6a500deb7e7e625d8df90.
As for the file containing the special character 0xB9, that one causes crash in storm.dll and thus cannot be in any MPQ. WinMPQ cannot extract it either.

**Comment by Karaulov** [comment]
Maybe add the label "known" / "unknown" file.
First you need to display known files, and then the unknown.
If you rename a file in File00000001.blp it causes problems!
![r4al3eh 1](https://cloud.githubusercontent.com/assets/6445336/11019208/3074d62c-85ff-11e5-9888-88ebb3c84ccb.png)
