### ISSUE TITLE
How to preserve directory structure with MPQEditor /extract?

### ISSUE THREAD

**Issue by jleclanche** [ladislav-zezula/StormLib#60]
`MPQEditor.exe /extract file.mpq` will extract all files into the folder it was run in. How to make it preserve the internal directory structure? (it should do that by default)

**Comment by ladislav-zezula** [comment]
MPQEditor.exe /extract file.mpq /fp

**Comment by jleclanche** [comment]
@ladislav-zezula Thanks. Please consider making it the default behaviour, though.

**Comment by ladislav-zezula** [comment]
Originally, MPQ editor commands are equal to the old WinMPQ script commands
http://d2mods.info/filecenter/content/docs/tools/ins-ext/winmpq-v164.txt - see (e)xtract.
Thats why the /fp parameter is there.
