### ISSUE TITLE
Unused define

### ISSUE THREAD

**Issue by Krakean** [ladislav-zezula/StormLib#62]
Not really issue.
#define MPQ_FILE_SIGNATURE          0x10000000  // Present on STANDARD.SNP\(signature). The only occurence ever observed

Not present in any file except StormLib.h. May be it should be removed?

Also:
#define MPQ_FILE_EXISTS             0x80000000  // Set if file exists, reset when the file was deleted
#define MPQ_FILE_REPLACEEXISTING    0x80000000  // Replace when the file exist (SFileAddFile)

Both have same value. Is it ok?

**Comment by ladislav-zezula** [comment]
Please, just leave it be.
