### ISSUE TITLE
What's difference between SFILE_VERIFY_FILE_MD5 and SFILE_VERIFY_RAW_MD5 ?

### ISSUE THREAD

**Issue by Krakean** [ladislav-zezula/StormLib#64]
Subj.

**Comment by ladislav-zezula** [comment]
SFILE_VERIFY_FILE_MD5 verifies the MD5 of the entire file within MPQ
SFILE_VERIFY_RAW_MD5 verifies the MD5 of the raw block of the file in the MPQ. Newer MPQs have files divided into blocks, each block has usually 0x4000 bytes, followed by MD5.
