### ISSUE TITLE
FileStream_Close question

### ISSUE THREAD

**Issue by Krakean** [ladislav-zezula/StormLib#65]
Hi.
...
        // Close the stream provider.
        if(pStream->StreamClose != NULL)
            pStream->StreamClose(pStream);
        
        // Also close base stream, if any
        else if(pStream->BaseClose != NULL)
            pStream->BaseClose(pStream);
...

Just curious about this part:
        // Also close base stream, if any
        else if(pStream->BaseClose != NULL)
Why here is "else if", not just "if"? There is only StreamClose or BaseClose are possible, not both (confused about "ALSO close..." part of comment, no question if it was "OR close...")?

**Comment by ladislav-zezula** [comment]
7b7c9acce2035c25064be3e83b358001182b8c47.

Happy now?

**Comment by Krakean** [comment]
Yep, thanks :)
