### ISSUE TITLE
ldconfig not run after installing libstorm.so.* by CMake build on Linux

### ISSUE THREAD

**Issue by mthuurne** [ladislav-zezula/StormLib#68]
To be able to locate libstorm at runtime on a Linux system, the dynamic linker cache needs to be updated using `ldconfig` after libstorm is installed. This is done by `Makefile.linux`, but when using CMake this step is not performed for some reason.

**Comment by ladislav-zezula** [comment]
Will have to let some Linux expert to fix it, I don't understand CMakeLists.txt that well.
