### ISSUE TITLE
Couldn't be write the mpq in the new version stormlib.

### ISSUE THREAD

**Issue by actboy168** [ladislav-zezula/StormLib#71]
Because the mpq has a flag MPQ_FLAG_MALFORMED.But it can be write in the old version stormlib 

[map.zip](https://github.com/ladislav-zezula/StormLib/files/158314/map.zip)

**Comment by ladislav-zezula** [comment]
Malformed MPQ are open for reading only. It was necessary to introduce this change due to increasing amount of so called MPQ protectors (read: corruptors), which malform the MPQ in some way in order to make them unreadable for StormLib.
