### ISSUE TITLE
Read-Only problem and New Wc3 MPQ protection

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#72]
Hello, it's me again and yes it's again wc3 related. I hope that you will spare some of your patience and look at it. So here is what happens: 

![error](https://cloud.githubusercontent.com/assets/11413837/13787958/18f7ed54-eaef-11e5-868e-848d29644986.jpg)

![noheaderattop](https://cloud.githubusercontent.com/assets/11413837/13787960/19145804-eaef-11e5-9bbc-8c27793d024c.jpg)

![mpqattheend](https://cloud.githubusercontent.com/assets/11413837/13787959/18fb5d0e-eaef-11e5-8255-0a9893b94aa8.jpg)

Here is the map.

[WME.zip](https://github.com/ladislav-zezula/StormLib/files/174490/WME.zip)

Another issue is, that older MPQ editor that I still have is able to open some protected maps without read-only mode. Here is a screenshot of the version:

![mpqeditorversion](https://cloud.githubusercontent.com/assets/11413837/13788060/793eaa04-eaef-11e5-9a0a-2f4e0646d5e1.jpg)

So my question is, can you force a normal mode over the read-only? Would really appreciate it. Thanks in advance!

**Comment by Tailer007** [comment]
Bump.

**Comment by ladislav-zezula** [comment]
Lol, hash table offset set to zero.
Fixed in commit ed195c0d727ef4ea7d74d663b0f437bbac32233a
