### ISSUE TITLE
An updated Somj2hM16 type of protection

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#74]
Hello! 

It's me again, yet again with another interesting type of protection. this time it was developed by Russians, based on Korean protection Somj2hM16, they use the same program, but they have updated it or maybe somehow modified it. Let's get down to business, so:

1) ![normalheader](https://cloud.githubusercontent.com/assets/11413837/15578580/a77ed6e8-2369-11e6-9b43-10d0f14662eb.jpg)

The first part is exactly the same as a regular somj protection, but the line 220 doesn't have a duplicate as it normally should have. Meaning doing the unhex - is impossible, without finding the EXACT spot from where data has to be removed.

2) ![bn3header](https://cloud.githubusercontent.com/assets/11413837/15578579/a779f7d6-2369-11e6-8367-fc4220d60787.jpg)

Basic BN3.Somj, same way as it is on a normal one.

3) ![somjheader1](https://cloud.githubusercontent.com/assets/11413837/15578582/a7888b20-2369-11e6-8c7e-701a962804d9.jpg)

First Somj header, normally this one has to be the one dragged to line 220, and the other one deleted with the dupliacte data.

4) ![somjheader2](https://cloud.githubusercontent.com/assets/11413837/15578581/a782d4fa-2369-11e6-90c2-421b7089c3d5.jpg)

Second somj header, the one that should be removed.

The problem is, that MPQ Editor is able to open the file, but doesn't see its contents, I hope you can fix it, as it would break another MPQ protection. And I hope I'm not annoying you with this, as all I want is to make this tool unbeatable ;) 

Map file: 
[SomjProtectedMap.zip](https://github.com/ladislav-zezula/StormLib/files/284755/SomjProtectedMap.zip)

**Comment by ladislav-zezula** [comment]
You are not annoying. I already have a nice collection of variously screwed maps, which I test the library against.

**Comment by Tailer007** [comment]
If you will need any aditional info I will be glad to give you. And thanks for such a fast answer, it's just funny how people are still trying to find new ways how to screw MPQ in a way that it can't be edited, at least it's funny to me.

**Comment by ladislav-zezula** [comment]
Yeah, it's funny for me as well. Notably because developing such protection takes far more time than me breaking it. I think.

**Comment by ladislav-zezula** [comment]
Ok, the protection is based on some flags, that can exist in MPQs, but Warcraft III ignores them (namely MPQ_FILE_SINGLE_UNIT and MPQ_FILE_PATCH_FILE). The commit f1655f8afe2ef76d4906eb3e94dfd3c2b5241eb4 fixes the problem.
