### ISSUE TITLE
A problem with new version of MPQ Editor

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#75]
Hello!

Well, I've found another problem, with another Chinese Map that has another silly protection, that just pretty much corrupts the header and hides it at the end of the file, the real problem is, that the version 799 is able to open it, but only sees the files after you apply the listfile. 

Map Link: https://vk.com/doc-79267218_437543487

However, it opens in a Read-Only mode, but this time it's not able to even extract files, it just gives a problem "Failed to extract the file "XXXX". The Request is not supported.
![requestedisnotsupported](https://cloud.githubusercontent.com/assets/11413837/15607487/c4e5ab6e-241b-11e6-9c8d-42cf2d6cacc5.jpg)

The newer version, that you have updated, is straight up crashing on this map (64 bit version though), the 32 bit version is opening in the same way as the 799 version, which is strange.

Now it's time to go into detail.

1) ![mpqheadermissing](https://cloud.githubusercontent.com/assets/11413837/15607372/ef4583f8-241a-11e6-919e-4fcaff24a63c.jpg)

As you can see the offset 200/210/220 don't have any indication about MPQ Header, possibly they are just a "ripped" part and the real header was moved somewhere else

2) ![mpqheaderattheend](https://cloud.githubusercontent.com/assets/11413837/15607371/ef453696-241a-11e6-92eb-84f3c17cc625.jpg)

Here is the MPQ header at the bottom, but its data is corrupted, the FF FF FF FF isn't a normal hex code for any MPQ, so I guess it's masked?

And another map with a protection that crashes MPQ Editor.

[AnotherProtectedMap.zip](https://github.com/ladislav-zezula/StormLib/files/286426/AnotherProtectedMap.zip)

Most probably it uses other flags, I will try opening it with 32 bit version, maybe that was the case.

EDIT: Yes, 32 bit was able to open and even extract the files, so the main problem lays somehow in 64 bit version, as the protection is being read in a different manner, I guess?

On a side note, are you able to make the possibility of removing and replacing internal files:

(attributes)
(listfile)

Meaning, if for example the map doesn't have a (listfile), that was removed with Vexorian or WinMPQ, we could add it back, or just add one to other files like .mix This would help me a lot, I hope you can do it.

Thank you for your time, I hope this was helpful ;)

**Comment by ladislav-zezula** [comment]
> Map Link: https://vk.com/doc-79267218_437543487

This map is (amongst others) abusing the fact that block index gets shifted by 0x04 (aka multiplied by 16), which, in 32-bit Warcraft III, means they get ignored. 64-bit MPQEditor went out of bounds and thus crashed. All block indexes in the hash table are like 0x8000xxxx

> AnotherProtectedMap.zip

The same like before. Except that all block indexes in the hash table are like 0x4000xxxx.

Both fixed in commit 47b6b6eb4addd82a89d6bcd8fa92f9c0a09a5781.

**Comment by ladislav-zezula** [comment]
As for the (listfile) thing:
It is hard-set that the listfile is maintained by StormLib. As for adding listfile back, it is not possible to add a listfile to those corrupted maps. It's next to impossible to make such MPQs editable, without knowing all file names.

If we would speak about a non-corrupted MPQs, it should be possible to add the listfile to the MPQ (MPQEditor: Operations\Use Additional Listfile) and then compact the MPQ.
