### ISSUE TITLE
W3X Name Scanner not see files like this

### ISSUE THREAD

**Issue by Heivor** [ladislav-zezula/StormLib#76]
\/\\BFNS.mdl
\/\\T3LRJZ.mdl
\/\\HumanCampaignGuard_bW.mdl
\/\\WoWFelGuard.mdl
\/\\andonidas.mdl
\/\\Ksardas.mdl
\/\\CalciumTerror.mdl
![clipboard0122](https://cloud.githubusercontent.com/assets/19757392/15804005/df5dae78-2b01-11e6-8e25-77a60651d40a.jpg)
site show one slash instead of two
Map http://rgho.st/private/7vXp4yXjS/e363fa91c3e999f2e81d7bfce589f9b6

**Comment by ladislav-zezula** [comment]
Fixed in build 3.5.1.814
