### ISSUE TITLE
Failed to rebuild protected or containing unknown file names archives!

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#77]
ladislav-zezula, you can add the feature to rebuild archives, protected or containing unknown file names?

Winmpq have this feature. But don't support new protection methods. You can move this feature from winmpq to Mpq Editor if You can't write own.

**Comment by ladislav-zezula** [comment]
I don't plan to add such feature.

**Comment by Karaulov** [comment]
But it possibled!
