### ISSUE TITLE
Another W3X protection

### ISSUE THREAD

**Issue by Tailer007** [ladislav-zezula/StormLib#81]
Hello once again, I bring you another type of protection from another Chinese map. This time it's nothing really new, just header corruption. What it does is pretty simple, you can open the w3x in latest MPQ Editor, but you can only see the (listfile)

Header:

![mpqheadercorruption](https://cloud.githubusercontent.com/assets/11413837/16715091/66e50b54-46df-11e6-9471-e822c64d68ae.jpg)

Displayed files:

![files](https://cloud.githubusercontent.com/assets/11413837/16715099/8d60435c-46df-11e6-84fc-7a2550e82a85.jpg)

http://dropmefiles.com/QkGce

**Comment by ladislav-zezula** [comment]
I'll look at it. Gimme few days.

**Comment by ladislav-zezula** [comment]
Fixed in commit 7597fe1702e4f27faf51d201b566139e17ad4342.
MPQ Editor rebuilt. Apart from long listfile loading, it loads perfectly now.
