### ISSUE TITLE
MPQ Editor can't open this

### ISSUE THREAD

**Issue by tutszord** [ladislav-zezula/StormLib#82]
I tried to open that map (ins't the original one) and got a fatal error.
Can't open even in read-only
Header
![ss 2016-07-13 at 08 42 39](https://cloud.githubusercontent.com/assets/16712765/16802189/ca10205e-48d5-11e6-9a5d-8d0c47fe6b8b.png)
New type of hex, i think.
https://www.dropbox.com/s/stedy9zpt3zlyqb/59_Hero_of_The_Emp.w3x?dl=0

**Comment by ladislav-zezula** [comment]
Warcraft III v 1.27 is unable to open this as well.
Both block table and hash table offsets are beyond the end of the file.
Verdict: The file is cut.
