### ISSUE TITLE
Lost casing?

### ISSUE THREAD

**Issue by RElesgoe** [ladislav-zezula/StormLib#83]
Attempting to extract ````ver-IX86-1.dll```` causes MPQ Editor to lowercase the file to ````ver-ix86-1.dll````.
Using version 3.5.1.793
[ver-IX86-1.zip](https://github.com/ladislav-zezula/StormLib/files/382995/ver-IX86-1.zip)

**Comment by ladislav-zezula** [comment]
Hi, using version 3.5.1.816 it works perfectly. Could you check with the new version?

**Comment by RElesgoe** [comment]
Download page shows 3.5.1.814: http://www.zezula.net/en/mpq/download.html
File version show 3.5.1.815, there is no 3.5.1.816

I did some testing again, and this only occurs when you drag and drop the file to extract it, the filename does not lose casing when you click on the Extract button.

**Comment by ladislav-zezula** [comment]
I dragged the file to both Windows Explorer and Total Commander, both kept casing.
Could you please post your Windows Version (also if 32 or 64bit)?

**Comment by RElesgoe** [comment]
Windows 10.0.10586 x64

**Comment by RElesgoe** [comment]
Nevermind, I had modified one of my list files and added ````ver-ix86-1.dll```` to it, I just deleted it and deleted my temp folder, now MPQEditor extracts properly.
