### ISSUE TITLE
Hidden file. (Zero size after open)

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#88]
Mpq Editor cant read war3map.j from this map. 

Link : http://www.mediafire.com/download/splgvk55mpnx649/123.zip

**Comment by Karaulov** [comment]
this map have 2 files with same name , war3map.j , MPQ Editor read bad file, please fix it!

**Comment by ladislav-zezula** [comment]
MPQ Editor loads the correct file. The one with zero size.
If you try with Storm.lib from the latest Warcraft III, it will also read the zero size file.

**Comment by Karaulov** [comment]
Just try open map in game :)

**Comment by Karaulov** [comment]
NO!!!!!!!!! Just open map in game! ))

2016-09-29 15:28 GMT+02:00 Ladislav Zezula <notifications@github.com>:

**Comment by ladislav-zezula** [comment]
After more investigation, you are right. Warcraft III opens the files in the map with a non-zero locale, which makes it ignore the first "war3map.j" an selects the last one (the best one).
Fixed in commit b8fb98fcc4aa2d1c6ab6ce57b6b2e10a25861a56
