### ISSUE TITLE
New patch, protected?

### ISSUE THREAD

**Issue by Karaulov** [ladislav-zezula/StormLib#94]
http://ftp.blizzard.com/pub/war3x/patches/pc/War3TFT_127b_Russian.exe

I can't see MPQ files in archive for example War3patch.mpq.

**Comment by Karaulov** [comment]
1.26a contain war3patch.mpq : http://i.imgur.com/p8NMYTv.png

**Comment by RElesgoe** [comment]
MPQ Editor is seeing War3patch.mpq as free space but WinMPQ is reading it correctly.

**Comment by Tailer007** [comment]
Well, I have checked what you said, so let me repeat what I said like a year ago ;D

New editor is indeed superior as it ignores most of protections, however there are some downfalls.

1. Now any file that has even slightest corruption is Read-Only, even the ones that the old versions were able to open and edit.
2. Some of the files may not be displayed, as they are blocked from view in Read-Only mode (yes this happens).
3. A lot of MPQs have MPQs inside of them that also have protection, which causes the MPQ Editor to go ape and unable to see the file.

Screenshot attached: On the left - new version. On the right - my old and trustworthy old version ;)
![123](https://cloud.githubusercontent.com/assets/11413837/21183562/f715d600-c221-11e6-9a49-a0c826f6ff13.jpg)

**Comment by RElesgoe** [comment]
@ladislav-zezula Any plans for this?

**Comment by ladislav-zezula** [comment]
Fixed in commit 9915997070a0b7e6c487d0bd5252eb2f8dab5573
