### ISSUE TITLE
Bump bundled versions of bzip2 and zlib

### ISSUE THREAD

**Issue by fallenoak** [ladislav-zezula/StormLib#95]
Currently, the bundled version of bzip2 is `1.0.5`, and the current version is `1.0.6`. Similarly, the bundled version of zlib is `1.2.5` and the current version is `1.2.8`.

I'd be happy to open PRs to bump these versions, assuming you're okay with it, @ladislav-zezula.

(Thanks for StormLib, btw!)

**Comment by ladislav-zezula** [comment]
Any work done on that would bring absolutely zero value to anyone.

**Comment by fallenoak** [comment]
As is, bzip2 cannot be compiled using `emcc`, which is the only blocking issue for compiling StormLib with `emscripten`.

If you don't see any reason to maintain your bundled libs, why are you bundling them in the first place?

**Comment by ladislav-zezula** [comment]
> why are you bundling them in the first place?
Because they are needed to build the library. Not everyone uses Linux where all the libraries are part of the system.

So the newer bzip2 can be compiled with emcc?

**Comment by fallenoak** [comment]
Correct. bzip2 `1.0.6` compiles fine with `emcc`.

**Comment by ladislav-zezula** [comment]
Updated in commit 0e138c27d3086061671ca57d8bba62ab14050b5d.
Could you please check if it compiles OK with emcc?

**Comment by fallenoak** [comment]
@ladislav-zezula Thanks! I've verified it compiles without error now.
