### ISSUE TITLE
SListFileFindNextFile during write

### ISSUE THREAD

**Issue by realmonster** [ladislav-zezula/StormLib#98]
Function SListFileFindNextFileError suddenly returns non zero
And GetLastError() == 0x12 ERROR_NO_MORE_FILES
But I'm sure, there are much more files in list.

My code looks like following
```cpp
HANDLE find_h = SListFileFindFirstFile(...);
if (find_h != NULL)
{
    do {
         if (wanna_rewrite(file_name))
            rewrite(file_name);
    } while (SListFileFindNextFile(...));
    SListFileFindClose(find_h)
}
```
Workaround: walk across SListFileFind and cache things before all modifications.

**Comment by ladislav-zezula** [comment]
Don't do that. If you really need to search & modify files, store them in the list.
