### ISSUE TITLE
When using cmake with Visual Studio, StormLib.h uses pragma comment(lib) on non-existent files

### ISSUE THREAD

**Issue by namreeb** [ladislav-zezula/StormLib#99]
CMake currently builds `storm.lib`, but `src/StormLib.h` will use `#pragma comment(lib, "xyz")` to select a different name which does not exist.

**Comment by ladislav-zezula** [comment]
This is because under Windows, you need to have LIB file build under the same conditions (rebug/release, ANSI/UNICODE, statically/dynamicakky linked CRT). Dunno how that works under CMake.

**Comment by namreeb** [comment]
If I can make it work that way with cmake, would you accept a PR for it?

What is the intent of `BUILD_SHARED_LIBS`?  The name is a bit misleading since it seems to control whether StormLib is itself compiled as a dynamic or static library.

**Comment by ladislav-zezula** [comment]
> If I can make it work that way with cmake, would you accept a PR for it?

Sure. I can provide you with more exact info, if necessary.

**Comment by namreeb** [comment]
I opened PR #100

**Comment by ladislav-zezula** [comment]
Wait - the only purpose for CMakeLists.txt, when used with Windows CMAKE, is to generate a project for Visual Studio 2015?
